/**
 * CR-59 - authored ADVANCED English items (difficulty 4-5), Global Success
 * aligned. Extra shapes beyond mcq:
 *   {tf:true, passage, statement, bool}        -> true-false reading
 *   {ro:true, tokens:[...], text:'...'}        -> reorder
 *   {ta:true, accept:[...]}                    -> text-answer
 */
export const ITEMS = [
  // ---------- GRADE 1 ----------
  { g: 1, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'school', d: 4,
    q: 'Which one is NOT a school thing?', c: ['pencil', 'ruler', 'cat', 'book'], a: 2,
    ex: "'Cat' là con mèo - động vật. Pencil, ruler, book đều là đồ dùng học tập.",
    lo: 'Phân biệt đồ dùng học tập với động vật.' },
  { g: 1, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'colors', d: 4,
    q: 'A banana is yellow. A strawberry is ___.', c: ['yellow', 'red', 'blue', 'green'], a: 1,
    ex: 'Dâu tây (strawberry) màu đỏ - red. Chuối vàng, nhưng dâu không vàng.',
    lo: 'Ghép màu sắc với đồ vật thật.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'family', d: 4,
    q: "My mother's son is my ___.", c: ['sister', 'brother', 'father', 'grandma'], a: 1,
    ex: "Con trai của mẹ mình là anh/em trai - brother. Câu đố quan hệ gia đình.",
    lo: 'Suy luận quan hệ gia đình.' },
  { g: 1, skill: 'grammar-use-of-english', dom: 'grammar', top: 'to-be', d: 4,
    q: 'Choose the correct sentence.', c: ['I is a student.', 'I am a student.', 'I are a student.', 'I be a student.'], a: 1,
    ex: "Động từ 'to be' với I luôn là 'am': I am a student. Bẫy kinh điển của be.",
    lo: 'Dùng đúng am/is/are với chủ ngữ I.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'numbers', d: 4,
    q: 'How many legs do TWO cats have?', c: ['four', 'six', 'eight', 'ten'], a: 2,
    ex: 'Mỗi con mèo 4 chân, 2 con = 4 + 4 = 8 chân - eight. Câu tổng hợp từ vựng số + kiến thức thật.',
    lo: 'Kết hợp từ vựng số với kiến thức thực tế.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'body', d: 4,
    q: 'Touch your ___. It is between your eyes and your mouth.', c: ['nose', 'ear', 'hand', 'foot'], a: 0,
    ex: 'Mũi (nose) nằm giữa mắt và miệng - mô tả vị trí trên mặt.',
    lo: 'Hiểu mô tả vị trí bộ phận cơ thể.' },
  { g: 1, skill: 'functional-language', dom: 'communication', top: 'greetings', d: 4,
    q: 'A: "Hello, what\'s your name?"  B: "___"', c: ['I am seven years old.', 'My name is Linh.', 'I am fine, thanks.', 'Goodbye!'], a: 1,
    ex: "Hỏi tên (what's your name) → trả lời tên: 'My name is Linh.' Các câu khác trả lời tuổi hoặc sức khỏe.",
    lo: 'Trả lời đúng câu hỏi tên.' },
  { g: 1, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'animals', d: 4,
    q: 'Which animal says "woof woof"?', c: ['a cat', 'a bird', 'a dog', 'a fish'], a: 2,
    ex: "'Woof woof' là tiếng chó sủa - dog. Mèo kêu 'meow', chim 'tweet'.",
    lo: 'Ghép tiếng kêu với động vật.' },
  { g: 1, skill: 'grammar-use-of-english', dom: 'grammar', top: 'plurals', d: 4,
    q: 'I can see two ___.', c: ['cat', 'cats', 'a cat', 'cates'], a: 1,
    ex: "Sau 'two' cần danh từ số nhiều: cats. 'Cates' là dạng sai - không có từ này.",
    lo: 'Dùng danh từ số nhiều sau số lượng.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'toys', d: 4,
    q: 'You can bounce and kick this toy. What is it?', c: ['a doll', 'a ball', 'a teddy bear', 'a kite'], a: 1,
    ex: 'Bóng (ball) có thể nảy (bounce) và đá (kick). Búp bê và gấu bông không dùng để đá.',
    lo: 'Suy luận đồ vật từ mô tả hành động.' },
  { g: 1, skill: 'phonics-pronunciation', dom: 'phonics', top: 'sounds', d: 4,
    q: 'Which word starts with the same sound as "cat"?', c: ['city', 'cake', 'chair', 'cent'], a: 1,
    ex: "'Cat' và 'cake' cùng âm /k/ ở đầu. 'City' và 'cent' đọc /s/ - bẫy chữ c hai cách đọc.",
    lo: 'Nhận biết âm đầu /k/ của chữ c.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'school', d: 4,
    q: 'You write on it with chalk or a pen. What is it?', c: ['a board', 'a bag', 'a desk', 'a pencil'], a: 0,
    ex: 'Viết lên bằng phấn hoặc bút → bảng (board). Bút chì là dụng cụ viết, không phải bề mặt.',
    lo: 'Phân biệt đồ vật trong lớp học.' },
  { g: 1, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'This is my dog. It is black. It has a long tail.',
    statement: 'The dog has a short tail.', bool: false,
    ex: "Bài đọc nói 'a long tail' - đuôi DÀI, nên câu 'short tail' là Sai.",
    lo: 'Đọc hiểu chi tiết trong đoạn 3 câu.' },
  { g: 1, skill: 'writing', dom: 'writing', top: 'word-order', d: 4, ro: true,
    tokens: ['is', 'my', 'This', 'pencil'],
    text: 'This is my pencil.',
    ex: "Cấu trúc giới thiệu: This is + đồ vật. 'This is my pencil.' - giới thiệu bút chì của mình.",
    lo: 'Sắp xếp câu giới thiệu đồ vật.' },
  { g: 1, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'face', d: 4,
    q: 'Which one is NOT on your face?', c: ['eyes', 'nose', 'knee', 'mouth'], a: 2,
    ex: 'Knee (đầu gối) ở chân, không phải trên mặt. Mắt, mũi, miệng đều trên mặt.',
    lo: 'Phân biệt bộ phận mặt và bộ phận khác.' },
  { g: 1, skill: 'functional-language', dom: 'communication', top: 'polite', d: 4,
    q: 'Your friend gives you a pencil. What do you say?', c: ['Goodbye!', 'Thank you!', 'I am sorry.', 'What is this?'], a: 1,
    ex: "Được tặng đồ → nói cảm ơn: 'Thank you!'. Phép lịch sự cơ bản.",
    lo: 'Dùng lời cảm ơn đúng tình huống.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'numbers', d: 5,
    q: 'I have ten fingers. I hide three fingers. How many fingers can you see?', c: ['three', 'seven', 'ten', 'thirteen'], a: 1,
    ex: '10 - 3 = 7 ngón còn nhìn thấy - seven. Câu vừa tính vừa đọc hiểu.',
    lo: 'Kết hợp phép trừ đơn giản với từ vựng số.' },
  { g: 1, skill: 'grammar-use-of-english', dom: 'grammar', top: 'this-that', d: 5,
    q: 'Choose the correct sentence about a dog FAR away.', c: ['This is a dog.', 'That is a dog.', 'These is a dog.', 'Dog that is.'], a: 1,
    ex: "Vật ở XA dùng 'that' - 'That is a dog'. 'This' dùng cho vật gần.",
    lo: 'Phân biệt this (gần) và that (xa).' },
  { g: 1, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'food', d: 4,
    q: 'Which one is a drink?', c: ['rice', 'bread', 'milk', 'egg'], a: 2,
    ex: 'Milk (sữa) là đồ UỐNG. Cơm, bánh mì, trứng là đồ ăn.',
    lo: 'Phân biệt đồ ăn và đồ uống.' },
  { g: 1, skill: 'reading', dom: 'reading', top: 'mini-read', d: 5, tf: true,
    passage: 'I have three pets: a cat, a dog and a bird. The cat is small. The dog is big.',
    statement: 'The bird is small.', bool: false,
    ex: "Bài chỉ nói mèo nhỏ, chó to - KHÔNG nói chim nhỏ. Không có thông tin nên câu này sai.",
    lo: 'Phân biệt thông tin có và không có trong bài đọc.' },

  // ---------- GRADE 2 ----------
  { g: 2, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'weather', d: 4,
    q: 'Which one is NOT a kind of weather?', c: ['sunny', 'rainy', 'windy', 'hungry'], a: 3,
    ex: "'Hungry' (đói) là cảm giác, không phải thời tiết. Sunny, rainy, windy đều là thời tiết.",
    lo: 'Phân biệt từ chỉ thời tiết và cảm giác.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'clothes', d: 4,
    q: 'It is cold and snowy. What do you wear?', c: ['a T-shirt', 'shorts', 'a coat', 'a swimsuit'], a: 2,
    ex: 'Trời lạnh có tuyết → mặc áo khoác (coat). Áo phông, quần đùi, đồ bơi dành cho trời nóng.',
    lo: 'Chọn trang phục theo thời tiết.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'present-continuous', d: 4,
    q: 'Look! The baby ___ now.', c: ['sleep', 'sleeps', 'is sleeping', 'sleeping'], a: 2,
    ex: "'Look!' + 'now' báo hiệu thì hiện tại tiếp diễn: is + V-ing = 'is sleeping'.",
    lo: 'Dùng thì hiện tại tiếp diễn với dấu hiệu Look!.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'food', d: 4,
    q: 'Which one is a vegetable?', c: ['an apple', 'a carrot', 'a banana', 'a grape'], a: 1,
    ex: 'Cà rốt (carrot) là RAU. Táo, chuối, nho đều là trái cây.',
    lo: 'Phân biệt rau và trái cây.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'can', d: 4,
    q: 'A fish ___ fly.', c: ["can", "can't", "is", "does"], a: 1,
    ex: "Cá không thể bay → chọn can't, dạng phủ định của can. 'Can' khẳng định không phù hợp.",
    lo: "Dùng can't cho khả năng không có." },
  { g: 2, skill: 'functional-language', dom: 'communication', top: 'requests', d: 4,
    q: 'You want some water. What do you say politely?', c: [
      'Give me water now!',
      'Can I have some water, please?',
      'Water! Water!',
      'I hate water.',
    ], a: 1,
    ex: "'Can I have..., please?' là cách xin lịch sự. Các câu còn lại thô hoặc sai ý.",
    lo: 'Dùng câu xin phép lịch sự.' },
  { g: 2, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'house', d: 4,
    q: 'Where do you sleep?', c: ['in the kitchen', 'in the bathroom', 'in the bedroom', 'in the garden'], a: 2,
    ex: 'Ngủ trong phòng ngủ (bedroom). Bếp nấu ăn, phòng tắm để tắm.',
    lo: 'Ghép hoạt động với phòng trong nhà.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'days', d: 4,
    q: 'Today is Friday. Tomorrow is ___.', c: ['Thursday', 'Saturday', 'Sunday', 'Monday'], a: 1,
    ex: 'Sau thứ Sáu (Friday) là thứ Bảy (Saturday).',
    lo: 'Biết thứ tự các ngày trong tuần.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'there-is', d: 4,
    q: 'Choose the correct sentence.', c: [
      'There is two cats in the garden.',
      'There are two cats in the garden.',
      'There be two cats in the garden.',
      'There two cats are in the garden.',
    ], a: 1,
    ex: "'Two cats' số nhiều → 'There are'. 'There is' chỉ dùng số ít.",
    lo: 'Dùng there is/are theo số ít - số nhiều.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'activities', d: 4,
    q: 'You do this in the pool with a swimsuit. What is it?', c: ['riding a bike', 'swimming', 'flying a kite', 'reading'], a: 1,
    ex: 'Trong hồ bơi với đồ bơi → bơi (swimming). Các hoạt động khác không làm trong hồ.',
    lo: 'Suy luận hoạt động từ địa điểm và dụng cụ.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'possessives', d: 4,
    q: 'This is Mai. ___ bag is pink.', c: ['His', 'Her', 'Its', 'Your'], a: 1,
    ex: 'Mai là bạn gái → tính từ sở hữu Her. His cho nam, Its cho vật/động vật.',
    lo: 'Chọn đúng tính từ sở hữu theo giới tính.' },
  { g: 2, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'On Mondays, Lan has English and Math. On Tuesdays, she has Music and Art. Her favorite day is Tuesday.',
    statement: 'Lan has English on Tuesdays.', bool: false,
    ex: 'Lan học Tiếng Anh vào THỨ HAI (Monday), không phải thứ Ba. Đọc kỹ ngày của từng môn.',
    lo: 'Đọc hiểu lịch học theo ngày.' },
  { g: 2, skill: 'writing', dom: 'writing', top: 'word-order', d: 4, ro: true,
    tokens: ['sunny', 'It', 'today', 'is'],
    text: 'It is sunny today.',
    ex: "Cấu trúc thời tiết: It is + tính từ thời tiết + today. 'It is sunny today.'",
    lo: 'Sắp xếp câu nói về thời tiết.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'jobs', d: 4,
    q: 'This person helps sick people in a hospital. Who is it?', c: ['a teacher', 'a farmer', 'a doctor', 'a driver'], a: 2,
    ex: 'Bác sĩ (doctor) giúp người bệnh ở bệnh viện.',
    lo: 'Ghép nghề nghiệp với công việc và nơi làm việc.' },
  { g: 2, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'animals', d: 4,
    q: 'Which animal has a very long neck?', c: ['a giraffe', 'a monkey', 'a tiger', 'a rabbit'], a: 0,
    ex: 'Hươu cao cổ (giraffe) có cổ rất dài - đặc điểm dễ nhận ra nhất của nó.',
    lo: 'Ghép đặc điểm cơ thể với động vật.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'like-ing', d: 5,
    q: 'I like ___ football with my friends.', c: ['play', 'plays', 'playing', 'played'], a: 2,
    ex: "Sau 'like' dùng V-ing: 'like playing'. Bẫy hay gặp của lớp 2-3.",
    lo: 'Dùng danh động từ sau like.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'weather', d: 5,
    q: 'The opposite of "hot" is ___.', c: ['warm', 'cold', 'cool', 'sunny'], a: 1,
    ex: 'Trái nghĩa của nóng (hot) là lạnh (cold). Warm là ấm, cool là mát - gần nghĩa chứ không trái nghĩa.',
    lo: 'Tìm từ trái nghĩa cặp nhiệt độ.' },
  { g: 2, skill: 'reading', dom: 'reading', top: 'mini-read', d: 5, tf: true,
    passage: 'Tom gets up at 6:30. He eats breakfast at 7:00. He goes to school at 7:30. His school starts at 8:00.',
    statement: 'Tom gets to school one hour late.', bool: false,
    ex: 'Tom đến trường 7:30, giờ học 8:00 → đến SỚM 30 phút, không muộn. Tính giờ trong bài đọc.',
    lo: 'Suy luận thời gian từ bài đọc.' },
  { g: 2, skill: 'functional-language', dom: 'communication', top: 'suggestions', d: 5,
    q: 'A: "Let\'s play football!"  B wants to say YES. B says: ___', c: [
      'No, thanks.',
      'That\'s a good idea!',
      'I don\'t like it.',
      'Maybe later.',
    ], a: 1,
    ex: "Đồng ý lời rủ → 'That's a good idea!'. Các câu khác đều từ chối hoặc né tránh.",
    lo: 'Đáp lại lời rủ chơi.' },
  { g: 2, skill: 'phonics-pronunciation', dom: 'phonics', top: 'rhymes', d: 4,
    q: 'Which word does NOT rhyme with "cake"?', c: ['lake', 'make', 'look', 'snake'], a: 2,
    ex: "'Cake', 'lake', 'make', 'snake' đều vần /eik/. 'Look' vần /uk/ - khác hẳn.",
    lo: 'Nhận biết vần điệu trong từ.' },

  // ---------- GRADE 3 ----------
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'present-simple', d: 4,
    q: 'She ___ to school by bus every day.', c: ['go', 'goes', 'going', 'went'], a: 1,
    ex: "Ngôi 3 số ít (she) + thói quen 'every day' → goes. Bẫy điển hình của hiện tại đơn.",
    lo: 'Chia động từ ngôi 3 số ít thì hiện tại đơn.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'present-continuous', d: 4,
    q: 'They ___ football in the park now.', c: ['play', 'plays', 'are playing', 'is playing'], a: 2,
    ex: "'They' số nhiều + 'now' → are playing. Nhiễu 'is playing' sai vì they cần are.",
    lo: 'Hiện tại tiếp diễn với chủ ngữ số nhiều.' },
  { g: 3, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'hobbies', d: 4,
    q: 'Which hobby uses a camera?', c: ['dancing', 'taking photos', 'cooking', 'singing'], a: 1,
    ex: 'Chụp ảnh (taking photos) dùng máy ảnh. Các sở thích khác không cần camera.',
    lo: 'Ghép sở thích với dụng cụ.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'prepositions', d: 4,
    q: 'The cat is ___ the table - you cannot see its head.', c: ['on', 'under', 'next to', 'in front of'], a: 1,
    ex: "Không thấy đầu mèo vì nó ở DƯỚI bàn (under). 'On' là trên mặt bàn - thấy rõ, không phù hợp.",
    lo: 'Chọn giới từ chỉ vị trí theo ngữ cảnh.' },
  { g: 3, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'time', d: 4,
    q: '"Half past seven" means ___.', c: ['7:00', '7:15', '7:30', '7:45'], a: 2,
    ex: 'Half past = 30 phút qua giờ → 7:30. Quarter past = 15 phút, quarter to = kém 15.',
    lo: 'Đọc giờ kém - hơn bằng half/quarter past.' },
  { g: 3, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'The zoo opens at 9 a.m. Tickets cost $5 for children and $10 for adults. The lion show is at 11 a.m.',
    statement: 'A ticket for a child costs ten dollars.', bool: false,
    ex: 'Vé trẻ em là $5, người lớn mới $10. Đổi chỗ giá - bẫy đọc lướt.',
    lo: 'Đọc hiểu chi tiết số tiền trong thông báo.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'have-got', d: 4,
    q: 'Choose the correct sentence.', c: [
      'He have got a new bike.',
      'He has got a new bike.',
      'He haves a new bike.',
      'He is have a new bike.',
    ], a: 1,
    ex: "Ngôi 3 số ít dùng 'has got' - 'He has got a new bike.' 'Have' đi với I/you/we/they.",
    lo: 'Dùng have got/has got đúng ngôi.' },
  { g: 3, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'places', d: 4,
    q: 'You borrow books here but you must be quiet. Where is it?', c: ['a stadium', 'a library', 'a market', 'a cinema'], a: 1,
    ex: 'Thư viện (library) - mượn sách và phải yên tĩnh. Sân vận động, chợ, rạp chiếu phim đều ồn được.',
    lo: 'Suy luận địa điểm từ hoạt động và quy tắc.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'adjectives', d: 4,
    q: 'An elephant is ___ than a mouse.', c: ['small', 'smaller', 'big', 'bigger'], a: 3,
    ex: "So sánh hơn dùng 'bigger than'. 'Big' thiếu so sánh; 'smaller' ngược ý.",
    lo: 'Dùng tính từ so sánh hơn với than.' },
  { g: 3, skill: 'writing', dom: 'writing', top: 'word-order', d: 4, ro: true,
    tokens: ['are', 'What', 'doing', 'you', '?'],
    text: 'What are you doing?',
    ex: "Câu hỏi hiện tại tiếp diễn: What + are + chủ ngữ + doing? 'What are you doing?'",
    lo: 'Sắp xếp câu hỏi What are you doing.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'must', d: 5,
    q: 'At school, students ___ wear a uniform.', c: ['must', 'cans', 'likes', 'are'], a: 0,
    ex: "'Must' diễn tả bắt buộc - học sinh PHẢI mặc đồng phục. 'Cans' là dạng sai.",
    lo: 'Dùng must cho quy định bắt buộc.' },
  { g: 3, skill: 'functional-language', dom: 'communication', top: 'asking-way', d: 5,
    q: 'A: "Excuse me, where is the library?"  B: "___"', c: [
      'I am a student.',
      'It is next to the park.',
      'Yes, it is.',
      'I like books.',
    ], a: 1,
    ex: "Hỏi đường → trả lời vị trí: 'It is next to the park.' Các câu khác không trả lời where.",
    lo: 'Trả lời câu hỏi đường đúng.' },

  // ---------- GRADE 4 ----------
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'past-simple', d: 4,
    q: 'Yesterday, we ___ to the beach.', c: ['go', 'goes', 'went', 'going'], a: 2,
    ex: "'Yesterday' → quá khứ đơn: went (bất quy tắc của go). Bẫy 'goed' không tồn tại.",
    lo: 'Dùng động từ bất quy tắc thì quá khứ.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'past-simple', d: 4,
    q: 'She ___ TV last night.', c: ["didn't watched", "didn't watch", "doesn't watch", "not watched"], a: 1,
    ex: "Phủ định quá khứ: didn't + V nguyên mẫu. 'Didn't watched' sai vì watched đã chia.",
    lo: 'Phủ định thì quá khứ đơn với didn\'t + V.' },
  { g: 4, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'abilities', d: 4,
    q: 'He can swim very fast. He is a good ___.', c: ['singer', 'swimmer', 'driver', 'writer'], a: 1,
    ex: 'Bơi giỏi → swimmer (vận động viên/người bơi). Danh từ chỉ người từ động từ swim.',
    lo: 'Tạo danh từ chỉ người từ động từ.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'comparatives', d: 4,
    q: 'The cheetah is ___ animal on land.', c: ['the fast', 'the faster', 'the fastest', 'faster than'], a: 2,
    ex: "So sánh nhất trong một nhóm → 'the fastest'. 'Faster than' chỉ so 2 con.",
    lo: 'Dùng so sánh nhất với the + -est.' },
  { g: 4, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'routines', d: 4,
    q: 'I brush my teeth ___ a day - in the morning and before bed.', c: ['once', 'twice', 'three times', 'never'], a: 1,
    ex: 'Sáng + trước khi ngủ = 2 lần → twice. Once là 1 lần.',
    lo: 'Dùng once/twice/times cho tần suất.' },
  { g: 4, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'Pandas live in China. They eat bamboo for 12 hours every day. A baby panda is pink and very small - it cannot see when it is born.',
    statement: 'A baby panda can see when it is born.', bool: false,
    ex: "Bài nói rõ gấu trúc con 'cannot see when it is born' - mới sinh chưa nhìn được. Đọc kỹ phần phủ định.",
    lo: 'Đọc hiểu chi tiết có phủ định.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'going-to', d: 4,
    q: 'Look at those black clouds! It ___ rain.', c: ['is going to', 'goes to', 'will to', 'rains to'], a: 0,
    ex: "Dự đoán có dấu hiệu (mây đen) → 'be going to': 'It is going to rain.'",
    lo: 'Dùng be going to cho dự đoán có bằng chứng.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'questions', d: 4,
    q: '___ did you go last Sunday? - I went to my grandma\'s house.', c: ['What', 'Where', 'When', 'Who'], a: 1,
    ex: "Đáp án là ĐỊA ĐIỂM (nhà bà) → hỏi Where. Các từ khác không phù hợp: 'What' hỏi vật/việc, 'When' hỏi giờ.",
    lo: 'Chọn từ hỏi theo thông tin trả lời.' },
  { g: 4, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'directions', d: 4,
    q: 'Go straight, then turn left at the bank. The school is on your ___.', c: ['left again', 'right', 'behind', 'front of the bank'], a: 1,
    ex: 'Đi thẳng rồi rẽ trái tại ngân hàng - trường nằm phía TAY PHẢI sau khi rẽ. Bài tập đọc chỉ đường.',
    lo: 'Hiểu chỉ dẫn phương hướng nhiều bước.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'some-any', d: 5,
    q: 'There isn\'t ___ milk in the fridge. Can you buy ___?', c: ['some - any', 'any - some', 'any - any', 'some - some'], a: 1,
    ex: "Câu phủ định dùng 'any'; câu đề nghị lịch sự (Can you...) dùng 'some'. Quy tắc nâng cao của some/any.",
    lo: 'Phân biệt some/any trong câu phủ định và đề nghị.' },
  { g: 4, skill: 'functional-language', dom: 'communication', top: 'health', d: 5,
    q: 'A: "What\'s the matter?"  B: "___"', c: [
      'I am ten years old.',
      'I have a stomachache.',
      'It is sunny today.',
      'Yes, I can.',
    ], a: 1,
    ex: "'What's the matter?' hỏi bị sao/đau gì → 'I have a stomachache' (đau bụng).",
    lo: 'Trả lời câu hỏi về sức khỏe.' },
  { g: 4, skill: 'writing', dom: 'writing', top: 'word-order', d: 5, ro: true,
    tokens: ['yesterday', 'went', 'I', 'to', 'zoo', 'the', '.'],
    text: 'I went to the zoo yesterday.',
    ex: "Quá khứ: chủ ngữ + V2 + nơi chốn + thời gian. 'I went to the zoo yesterday.' - 7 từ cần sắp đúng trật tự.",
    lo: 'Sắp xếp câu quá khứ dài đúng trật tự.' },

  // ---------- GRADE 5 ----------
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'past-simple', d: 4,
    q: 'They ___ in Ha Long Bay last summer.', c: ['are', 'were', 'was', 'be'], a: 1,
    ex: "'They' số nhiều + 'last summer' → were. 'Was' chỉ đi với I/he/she/it.",
    lo: 'Dùng was/were đúng ngôi thì quá khứ.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'comparatives', d: 4,
    q: 'This book is ___ than that one.', c: ['more interesting', 'interestinger', 'most interesting', 'much interesting'], a: 0,
    ex: "Tính từ dài (interesting) so sánh hơn bằng 'more + adj'. 'Interestinger' là dạng sai kinh điển.",
    lo: 'So sánh hơn tính từ dài bằng more.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'future', d: 4,
    q: 'A: "What ___ you do this weekend?"  B: "I will visit my uncle."', c: ['do', 'will', 'did', 'are'], a: 1,
    ex: "Đáp án dùng 'will visit' → câu hỏi cũng dùng will: 'What will you do...?'",
    lo: 'Hỏi đáp thì tương lai với will.' },
  { g: 5, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'health', d: 4,
    q: 'You should see a dentist when you have a ___.', c: ['headache', 'toothache', 'stomachache', 'backache'], a: 1,
    ex: 'Đau răng (toothache) → nha sĩ (dentist). Đau đầu, đau bụng, đau lưng gặp bác sĩ khác.',
    lo: 'Ghép bệnh với chuyên khoa đúng.' },
  { g: 5, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'The Great Wall of China is more than 21,000 km long. It was built over many centuries to protect the country. Today, millions of tourists visit it every year.',
    statement: 'The Great Wall was built in one year.', bool: false,
    ex: "Bài nói 'over many centuries' - nhiều THẾ KỶ, không phải 1 năm. Chi tiết thời gian là bẫy.",
    lo: 'Đọc hiểu văn bản thông tin lịch sử.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'pronouns', d: 5,
    q: 'Minh and I are friends. ___ often play badminton together.', c: ['He', 'They', 'We', 'Us'], a: 2,
    ex: "'Minh and I' = chúng tôi → chủ ngữ We. 'Us' là tân ngữ, không đứng đầu câu.",
    lo: 'Chọn đại từ chủ ngữ thay cụm người.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'conditional', d: 5,
    q: 'If it rains tomorrow, we ___ at home.', c: ['will stay', 'stay', 'stayed', 'staying'], a: 0,
    ex: "Điều kiện loại 1: If + hiện tại đơn → vế sau dùng will + V. 'If it rains, we will stay.'",
    lo: 'Dùng câu điều kiện loại 1.' },
  { g: 5, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'environment', d: 5,
    q: 'We should ___ plastic bags to protect the ocean.', c: ['use more', 'reuse or reduce', 'throw into rivers', 'burn in the garden'], a: 1,
    ex: 'Bảo vệ đại dương → tái sử dụng hoặc giảm dùng (reuse or reduce) túi nilon. Các đáp án khác gây hại.',
    lo: 'Từ vựng chủ đề bảo vệ môi trường.' },
  { g: 5, skill: 'functional-language', dom: 'communication', top: 'advice', d: 5,
    q: 'A: "I have a bad cough."  B gives advice: "___"', c: [
      'You should drink cold Coke.',
      'You shouldn\'t see a doctor.',
      'You should drink warm water and rest.',
      'Why don\'t you run outside?',
    ], a: 2,
    ex: 'Ho → nên uống nước ấm và nghỉ ngơi. Các lời khuyên còn lại có hại hoặc vô lý.',
    lo: 'Đưa lời khuyên sức khỏe hợp lý với should.' },
  { g: 5, skill: 'writing', dom: 'writing', top: 'word-order', d: 5, ro: true,
    tokens: ['visit', 'We', 'our', 'grandparents', 'will', 'Sunday', 'next', '.'],
    text: 'We will visit our grandparents next Sunday.',
    ex: "Tương lai: chủ ngữ + will + V + tân ngữ + thời gian. 'We will visit our grandparents next Sunday.'",
    lo: 'Sắp xếp câu tương lai will + V dài.' },
];
