/**
 * CR-59 - authored ADVANCED English items (difficulty 4-5), Global Success
 * aligned. Extra shapes beyond mcq:
 *   {tf:true, passage, statement, bool}        -> true-false reading
 *   {ro:true, tokens:[...], text:'...'}        -> reorder
 *   {ta:true, accept:[...]}                    -> text-answer
 */
export const ITEMS = [
  // ---------- GRADE 1 ----------
  { g: 1, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'school', d: 4,
    q: 'Which one is NOT a school thing?', c: ['pencil', 'ruler', 'cat', 'book'], a: 2,
    ex: "'Cat' là con mèo - động vật. Pencil, ruler, book đều là đồ dùng học tập.",
    lo: 'Phân biệt đồ dùng học tập với động vật.' },
  { g: 1, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'colors', d: 4,
    q: 'A banana is yellow. A strawberry is ___.', c: ['yellow', 'red', 'blue', 'green'], a: 1,
    ex: 'Dâu tây (strawberry) màu đỏ - red. Chuối vàng, nhưng dâu không vàng.',
    lo: 'Ghép màu sắc với đồ vật thật.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'family', d: 4,
    q: "My mother's son is my ___.", c: ['sister', 'brother', 'father', 'grandma'], a: 1,
    ex: "Con trai của mẹ mình là anh/em trai - brother. Câu đố quan hệ gia đình.",
    lo: 'Suy luận quan hệ gia đình.' },
  { g: 1, skill: 'grammar-use-of-english', dom: 'grammar', top: 'to-be', d: 4,
    q: 'Choose the correct sentence.', c: ['I is a student.', 'I am a student.', 'I are a student.', 'I be a student.'], a: 1,
    ex: "Động từ 'to be' với I luôn là 'am': I am a student. Bẫy kinh điển của be.",
    lo: 'Dùng đúng am/is/are với chủ ngữ I.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'numbers', d: 4,
    q: 'How many legs do TWO cats have?', c: ['four', 'six', 'eight', 'ten'], a: 2,
    ex: 'Mỗi con mèo 4 chân, 2 con = 4 + 4 = 8 chân - eight. Câu tổng hợp từ vựng số + kiến thức thật.',
    lo: 'Kết hợp từ vựng số với kiến thức thực tế.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'body', d: 4,
    q: 'Touch your ___. It is between your eyes and your mouth.', c: ['nose', 'ear', 'hand', 'foot'], a: 0,
    ex: 'Mũi (nose) nằm giữa mắt và miệng - mô tả vị trí trên mặt.',
    lo: 'Hiểu mô tả vị trí bộ phận cơ thể.' },
  { g: 1, skill: 'functional-language', dom: 'communication', top: 'greetings', d: 4,
    q: 'A: "Hello, what\'s your name?"  B: "___"', c: ['I am seven years old.', 'My name is Linh.', 'I am fine, thanks.', 'Goodbye!'], a: 1,
    ex: "Hỏi tên (what's your name) → trả lời tên: 'My name is Linh.' Các câu khác trả lời tuổi hoặc sức khỏe.",
    lo: 'Trả lời đúng câu hỏi tên.' },
  { g: 1, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'animals', d: 4,
    q: 'Which animal says "woof woof"?', c: ['a cat', 'a bird', 'a dog', 'a fish'], a: 2,
    ex: "'Woof woof' là tiếng chó sủa - dog. Mèo kêu 'meow', chim 'tweet'.",
    lo: 'Ghép tiếng kêu với động vật.' },
  { g: 1, skill: 'grammar-use-of-english', dom: 'grammar', top: 'plurals', d: 4,
    q: 'I can see two ___.', c: ['cat', 'cats', 'a cat', 'cates'], a: 1,
    ex: "Sau 'two' cần danh từ số nhiều: cats. 'Cates' là dạng sai - không có từ này.",
    lo: 'Dùng danh từ số nhiều sau số lượng.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'toys', d: 4,
    q: 'You can bounce and kick this toy. What is it?', c: ['a doll', 'a ball', 'a teddy bear', 'a kite'], a: 1,
    ex: 'Bóng (ball) có thể nảy (bounce) và đá (kick). Búp bê và gấu bông không dùng để đá.',
    lo: 'Suy luận đồ vật từ mô tả hành động.' },
  { g: 1, skill: 'phonics-pronunciation', dom: 'phonics', top: 'sounds', d: 4,
    q: 'Which word starts with the same sound as "cat"?', c: ['city', 'cake', 'chair', 'cent'], a: 1,
    ex: "'Cat' và 'cake' cùng âm /k/ ở đầu. 'City' và 'cent' đọc /s/ - bẫy chữ c hai cách đọc.",
    lo: 'Nhận biết âm đầu /k/ của chữ c.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'school', d: 4,
    q: 'You write on it with chalk or a pen. What is it?', c: ['a board', 'a bag', 'a desk', 'a pencil'], a: 0,
    ex: 'Viết lên bằng phấn hoặc bút → bảng (board). Bút chì là dụng cụ viết, không phải bề mặt.',
    lo: 'Phân biệt đồ vật trong lớp học.' },
  { g: 1, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'This is my dog. It is black. It has a long tail.',
    statement: 'The dog has a short tail.', bool: false,
    ex: "Bài đọc nói 'a long tail' - đuôi DÀI, nên câu 'short tail' là Sai.",
    lo: 'Đọc hiểu chi tiết trong đoạn 3 câu.' },
  { g: 1, skill: 'writing', dom: 'writing', top: 'word-order', d: 4, ro: true,
    tokens: ['is', 'my', 'This', 'pencil'],
    text: 'This is my pencil.',
    ex: "Cấu trúc giới thiệu: This is + đồ vật. 'This is my pencil.' - giới thiệu bút chì của mình.",
    lo: 'Sắp xếp câu giới thiệu đồ vật.' },
  { g: 1, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'face', d: 4,
    q: 'Which one is NOT on your face?', c: ['eyes', 'nose', 'knee', 'mouth'], a: 2,
    ex: 'Knee (đầu gối) ở chân, không phải trên mặt. Mắt, mũi, miệng đều trên mặt.',
    lo: 'Phân biệt bộ phận mặt và bộ phận khác.' },
  { g: 1, skill: 'functional-language', dom: 'communication', top: 'polite', d: 4,
    q: 'Your friend gives you a pencil. What do you say?', c: ['Goodbye!', 'Thank you!', 'I am sorry.', 'What is this?'], a: 1,
    ex: "Được tặng đồ → nói cảm ơn: 'Thank you!'. Phép lịch sự cơ bản.",
    lo: 'Dùng lời cảm ơn đúng tình huống.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'numbers', d: 5,
    q: 'I have ten fingers. I hide three fingers. How many fingers can you see?', c: ['three', 'seven', 'ten', 'thirteen'], a: 1,
    ex: '10 - 3 = 7 ngón còn nhìn thấy - seven. Câu vừa tính vừa đọc hiểu.',
    lo: 'Kết hợp phép trừ đơn giản với từ vựng số.' },
  { g: 1, skill: 'grammar-use-of-english', dom: 'grammar', top: 'this-that', d: 5,
    q: 'Choose the correct sentence about a dog FAR away.', c: ['This is a dog.', 'That is a dog.', 'These is a dog.', 'Dog that is.'], a: 1,
    ex: "Vật ở XA dùng 'that' - 'That is a dog'. 'This' dùng cho vật gần.",
    lo: 'Phân biệt this (gần) và that (xa).' },
  { g: 1, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'food', d: 4,
    q: 'Which one is a drink?', c: ['rice', 'bread', 'milk', 'egg'], a: 2,
    ex: 'Milk (sữa) là đồ UỐNG. Cơm, bánh mì, trứng là đồ ăn.',
    lo: 'Phân biệt đồ ăn và đồ uống.' },
  { g: 1, skill: 'reading', dom: 'reading', top: 'mini-read', d: 5, tf: true,
    passage: 'I have three pets: a cat, a dog and a bird. The cat is small. The dog is big.',
    statement: 'The bird is small.', bool: false,
    ex: "Bài chỉ nói mèo nhỏ, chó to - KHÔNG nói chim nhỏ. Không có thông tin nên câu này sai.",
    lo: 'Phân biệt thông tin có và không có trong bài đọc.' },

  // ---------- GRADE 2 ----------
  { g: 2, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'weather', d: 4,
    q: 'Which one is NOT a kind of weather?', c: ['sunny', 'rainy', 'windy', 'hungry'], a: 3,
    ex: "'Hungry' (đói) là cảm giác, không phải thời tiết. Sunny, rainy, windy đều là thời tiết.",
    lo: 'Phân biệt từ chỉ thời tiết và cảm giác.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'clothes', d: 4,
    q: 'It is cold and snowy. What do you wear?', c: ['a T-shirt', 'shorts', 'a coat', 'a swimsuit'], a: 2,
    ex: 'Trời lạnh có tuyết → mặc áo khoác (coat). Áo phông, quần đùi, đồ bơi dành cho trời nóng.',
    lo: 'Chọn trang phục theo thời tiết.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'present-continuous', d: 4,
    q: 'Look! The baby ___ now.', c: ['sleep', 'sleeps', 'is sleeping', 'sleeping'], a: 2,
    ex: "'Look!' + 'now' báo hiệu thì hiện tại tiếp diễn: is + V-ing = 'is sleeping'.",
    lo: 'Dùng thì hiện tại tiếp diễn với dấu hiệu Look!.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'food', d: 4,
    q: 'Which one is a vegetable?', c: ['an apple', 'a carrot', 'a banana', 'a grape'], a: 1,
    ex: 'Cà rốt (carrot) là RAU. Táo, chuối, nho đều là trái cây.',
    lo: 'Phân biệt rau và trái cây.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'can', d: 4,
    q: 'A fish ___ fly.', c: ["can", "can't", "is", "does"], a: 1,
    ex: "Cá không thể bay → chọn can't, dạng phủ định của can. 'Can' khẳng định không phù hợp.",
    lo: "Dùng can't cho khả năng không có." },
  { g: 2, skill: 'functional-language', dom: 'communication', top: 'requests', d: 4,
    q: 'You want some water. What do you say politely?', c: [
      'Give me water now!',
      'Can I have some water, please?',
      'Water! Water!',
      'I hate water.',
    ], a: 1,
    ex: "'Can I have..., please?' là cách xin lịch sự. Các câu còn lại thô hoặc sai ý.",
    lo: 'Dùng câu xin phép lịch sự.' },
  { g: 2, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'house', d: 4,
    q: 'Where do you sleep?', c: ['in the kitchen', 'in the bathroom', 'in the bedroom', 'in the garden'], a: 2,
    ex: 'Ngủ trong phòng ngủ (bedroom). Bếp nấu ăn, phòng tắm để tắm.',
    lo: 'Ghép hoạt động với phòng trong nhà.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'days', d: 4,
    q: 'Today is Friday. Tomorrow is ___.', c: ['Thursday', 'Saturday', 'Sunday', 'Monday'], a: 1,
    ex: 'Sau thứ Sáu (Friday) là thứ Bảy (Saturday).',
    lo: 'Biết thứ tự các ngày trong tuần.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'there-is', d: 4,
    q: 'Choose the correct sentence.', c: [
      'There is two cats in the garden.',
      'There are two cats in the garden.',
      'There be two cats in the garden.',
      'There two cats are in the garden.',
    ], a: 1,
    ex: "'Two cats' số nhiều → 'There are'. 'There is' chỉ dùng số ít.",
    lo: 'Dùng there is/are theo số ít - số nhiều.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'activities', d: 4,
    q: 'You do this in the pool with a swimsuit. What is it?', c: ['riding a bike', 'swimming', 'flying a kite', 'reading'], a: 1,
    ex: 'Trong hồ bơi với đồ bơi → bơi (swimming). Các hoạt động khác không làm trong hồ.',
    lo: 'Suy luận hoạt động từ địa điểm và dụng cụ.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'possessives', d: 4,
    q: 'This is Mai. ___ bag is pink.', c: ['His', 'Her', 'Its', 'Your'], a: 1,
    ex: 'Mai là bạn gái → tính từ sở hữu Her. His cho nam, Its cho vật/động vật.',
    lo: 'Chọn đúng tính từ sở hữu theo giới tính.' },
  { g: 2, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'On Mondays, Lan has English and Math. On Tuesdays, she has Music and Art. Her favorite day is Tuesday.',
    statement: 'Lan has English on Tuesdays.', bool: false,
    ex: 'Lan học Tiếng Anh vào THỨ HAI (Monday), không phải thứ Ba. Đọc kỹ ngày của từng môn.',
    lo: 'Đọc hiểu lịch học theo ngày.' },
  { g: 2, skill: 'writing', dom: 'writing', top: 'word-order', d: 4, ro: true,
    tokens: ['sunny', 'It', 'today', 'is'],
    text: 'It is sunny today.',
    ex: "Cấu trúc thời tiết: It is + tính từ thời tiết + today. 'It is sunny today.'",
    lo: 'Sắp xếp câu nói về thời tiết.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'jobs', d: 4,
    q: 'This person helps sick people in a hospital. Who is it?', c: ['a teacher', 'a farmer', 'a doctor', 'a driver'], a: 2,
    ex: 'Bác sĩ (doctor) giúp người bệnh ở bệnh viện.',
    lo: 'Ghép nghề nghiệp với công việc và nơi làm việc.' },
  { g: 2, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'animals', d: 4,
    q: 'Which animal has a very long neck?', c: ['a giraffe', 'a monkey', 'a tiger', 'a rabbit'], a: 0,
    ex: 'Hươu cao cổ (giraffe) có cổ rất dài - đặc điểm dễ nhận ra nhất của nó.',
    lo: 'Ghép đặc điểm cơ thể với động vật.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'like-ing', d: 5,
    q: 'I like ___ football with my friends.', c: ['play', 'plays', 'playing', 'played'], a: 2,
    ex: "Sau 'like' dùng V-ing: 'like playing'. Bẫy hay gặp của lớp 2-3.",
    lo: 'Dùng danh động từ sau like.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'weather', d: 5,
    q: 'The opposite of "hot" is ___.', c: ['warm', 'cold', 'cool', 'sunny'], a: 1,
    ex: 'Trái nghĩa của nóng (hot) là lạnh (cold). Warm là ấm, cool là mát - gần nghĩa chứ không trái nghĩa.',
    lo: 'Tìm từ trái nghĩa cặp nhiệt độ.' },
  { g: 2, skill: 'reading', dom: 'reading', top: 'mini-read', d: 5, tf: true,
    passage: 'Tom gets up at 6:30. He eats breakfast at 7:00. He goes to school at 7:30. His school starts at 8:00.',
    statement: 'Tom gets to school one hour late.', bool: false,
    ex: 'Tom đến trường 7:30, giờ học 8:00 → đến SỚM 30 phút, không muộn. Tính giờ trong bài đọc.',
    lo: 'Suy luận thời gian từ bài đọc.' },
  { g: 2, skill: 'functional-language', dom: 'communication', top: 'suggestions', d: 5,
    q: 'A: "Let\'s play football!"  B wants to say YES. B says: ___', c: [
      'No, thanks.',
      'That\'s a good idea!',
      'I don\'t like it.',
      'Maybe later.',
    ], a: 1,
    ex: "Đồng ý lời rủ → 'That's a good idea!'. Các câu khác đều từ chối hoặc né tránh.",
    lo: 'Đáp lại lời rủ chơi.' },
  { g: 2, skill: 'phonics-pronunciation', dom: 'phonics', top: 'rhymes', d: 4,
    q: 'Which word does NOT rhyme with "cake"?', c: ['lake', 'make', 'look', 'snake'], a: 2,
    ex: "'Cake', 'lake', 'make', 'snake' đều vần /eik/. 'Look' vần /uk/ - khác hẳn.",
    lo: 'Nhận biết vần điệu trong từ.' },

  // ---------- GRADE 3 ----------
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'present-simple', d: 4,
    q: 'She ___ to school by bus every day.', c: ['go', 'goes', 'going', 'went'], a: 1,
    ex: "Ngôi 3 số ít (she) + thói quen 'every day' → goes. Bẫy điển hình của hiện tại đơn.",
    lo: 'Chia động từ ngôi 3 số ít thì hiện tại đơn.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'present-continuous', d: 4,
    q: 'They ___ football in the park now.', c: ['play', 'plays', 'are playing', 'is playing'], a: 2,
    ex: "'They' số nhiều + 'now' → are playing. Nhiễu 'is playing' sai vì they cần are.",
    lo: 'Hiện tại tiếp diễn với chủ ngữ số nhiều.' },
  { g: 3, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'hobbies', d: 4,
    q: 'Which hobby uses a camera?', c: ['dancing', 'taking photos', 'cooking', 'singing'], a: 1,
    ex: 'Chụp ảnh (taking photos) dùng máy ảnh. Các sở thích khác không cần camera.',
    lo: 'Ghép sở thích với dụng cụ.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'prepositions', d: 4,
    q: 'The cat is ___ the table - you cannot see its head.', c: ['on', 'under', 'next to', 'in front of'], a: 1,
    ex: "Không thấy đầu mèo vì nó ở DƯỚI bàn (under). 'On' là trên mặt bàn - thấy rõ, không phù hợp.",
    lo: 'Chọn giới từ chỉ vị trí theo ngữ cảnh.' },
  { g: 3, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'time', d: 4,
    q: '"Half past seven" means ___.', c: ['7:00', '7:15', '7:30', '7:45'], a: 2,
    ex: 'Half past = 30 phút qua giờ → 7:30. Quarter past = 15 phút, quarter to = kém 15.',
    lo: 'Đọc giờ kém - hơn bằng half/quarter past.' },
  { g: 3, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'The zoo opens at 9 a.m. Tickets cost $5 for children and $10 for adults. The lion show is at 11 a.m.',
    statement: 'A ticket for a child costs ten dollars.', bool: false,
    ex: 'Vé trẻ em là $5, người lớn mới $10. Đổi chỗ giá - bẫy đọc lướt.',
    lo: 'Đọc hiểu chi tiết số tiền trong thông báo.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'have-got', d: 4,
    q: 'Choose the correct sentence.', c: [
      'He have got a new bike.',
      'He has got a new bike.',
      'He haves a new bike.',
      'He is have a new bike.',
    ], a: 1,
    ex: "Ngôi 3 số ít dùng 'has got' - 'He has got a new bike.' 'Have' đi với I/you/we/they.",
    lo: 'Dùng have got/has got đúng ngôi.' },
  { g: 3, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'places', d: 4,
    q: 'You borrow books here but you must be quiet. Where is it?', c: ['a stadium', 'a library', 'a market', 'a cinema'], a: 1,
    ex: 'Thư viện (library) - mượn sách và phải yên tĩnh. Sân vận động, chợ, rạp chiếu phim đều ồn được.',
    lo: 'Suy luận địa điểm từ hoạt động và quy tắc.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'adjectives', d: 4,
    q: 'An elephant is ___ than a mouse.', c: ['small', 'smaller', 'big', 'bigger'], a: 3,
    ex: "So sánh hơn dùng 'bigger than'. 'Big' thiếu so sánh; 'smaller' ngược ý.",
    lo: 'Dùng tính từ so sánh hơn với than.' },
  { g: 3, skill: 'writing', dom: 'writing', top: 'word-order', d: 4, ro: true,
    tokens: ['are', 'What', 'doing', 'you', '?'],
    text: 'What are you doing?',
    ex: "Câu hỏi hiện tại tiếp diễn: What + are + chủ ngữ + doing? 'What are you doing?'",
    lo: 'Sắp xếp câu hỏi What are you doing.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'must', d: 5,
    q: 'At school, students ___ wear a uniform.', c: ['must', 'cans', 'likes', 'are'], a: 0,
    ex: "'Must' diễn tả bắt buộc - học sinh PHẢI mặc đồng phục. 'Cans' là dạng sai.",
    lo: 'Dùng must cho quy định bắt buộc.' },
  { g: 3, skill: 'functional-language', dom: 'communication', top: 'asking-way', d: 5,
    q: 'A: "Excuse me, where is the library?"  B: "___"', c: [
      'I am a student.',
      'It is next to the park.',
      'Yes, it is.',
      'I like books.',
    ], a: 1,
    ex: "Hỏi đường → trả lời vị trí: 'It is next to the park.' Các câu khác không trả lời where.",
    lo: 'Trả lời câu hỏi đường đúng.' },

  // ---------- GRADE 4 ----------
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'past-simple', d: 4,
    q: 'Yesterday, we ___ to the beach.', c: ['go', 'goes', 'went', 'going'], a: 2,
    ex: "'Yesterday' → quá khứ đơn: went (bất quy tắc của go). Bẫy 'goed' không tồn tại.",
    lo: 'Dùng động từ bất quy tắc thì quá khứ.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'past-simple', d: 4,
    q: 'She ___ TV last night.', c: ["didn't watched", "didn't watch", "doesn't watch", "not watched"], a: 1,
    ex: "Phủ định quá khứ: didn't + V nguyên mẫu. 'Didn't watched' sai vì watched đã chia.",
    lo: 'Phủ định thì quá khứ đơn với didn\'t + V.' },
  { g: 4, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'abilities', d: 4,
    q: 'He can swim very fast. He is a good ___.', c: ['singer', 'swimmer', 'driver', 'writer'], a: 1,
    ex: 'Bơi giỏi → swimmer (vận động viên/người bơi). Danh từ chỉ người từ động từ swim.',
    lo: 'Tạo danh từ chỉ người từ động từ.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'comparatives', d: 4,
    q: 'The cheetah is ___ animal on land.', c: ['the fast', 'the faster', 'the fastest', 'faster than'], a: 2,
    ex: "So sánh nhất trong một nhóm → 'the fastest'. 'Faster than' chỉ so 2 con.",
    lo: 'Dùng so sánh nhất với the + -est.' },
  { g: 4, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'routines', d: 4,
    q: 'I brush my teeth ___ a day - in the morning and before bed.', c: ['once', 'twice', 'three times', 'never'], a: 1,
    ex: 'Sáng + trước khi ngủ = 2 lần → twice. Once là 1 lần.',
    lo: 'Dùng once/twice/times cho tần suất.' },
  { g: 4, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'Pandas live in China. They eat bamboo for 12 hours every day. A baby panda is pink and very small - it cannot see when it is born.',
    statement: 'A baby panda can see when it is born.', bool: false,
    ex: "Bài nói rõ gấu trúc con 'cannot see when it is born' - mới sinh chưa nhìn được. Đọc kỹ phần phủ định.",
    lo: 'Đọc hiểu chi tiết có phủ định.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'going-to', d: 4,
    q: 'Look at those black clouds! It ___ rain.', c: ['is going to', 'goes to', 'will to', 'rains to'], a: 0,
    ex: "Dự đoán có dấu hiệu (mây đen) → 'be going to': 'It is going to rain.'",
    lo: 'Dùng be going to cho dự đoán có bằng chứng.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'questions', d: 4,
    q: '___ did you go last Sunday? - I went to my grandma\'s house.', c: ['What', 'Where', 'When', 'Who'], a: 1,
    ex: "Đáp án là ĐỊA ĐIỂM (nhà bà) → hỏi Where. Các từ khác không phù hợp: 'What' hỏi vật/việc, 'When' hỏi giờ.",
    lo: 'Chọn từ hỏi theo thông tin trả lời.' },
  { g: 4, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'directions', d: 4,
    q: 'Go straight, then turn left at the bank. The school is on your ___.', c: ['left again', 'right', 'behind', 'front of the bank'], a: 1,
    ex: 'Đi thẳng rồi rẽ trái tại ngân hàng - trường nằm phía TAY PHẢI sau khi rẽ. Bài tập đọc chỉ đường.',
    lo: 'Hiểu chỉ dẫn phương hướng nhiều bước.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'some-any', d: 5,
    q: 'There isn\'t ___ milk in the fridge. Can you buy ___?', c: ['some - any', 'any - some', 'any - any', 'some - some'], a: 1,
    ex: "Câu phủ định dùng 'any'; câu đề nghị lịch sự (Can you...) dùng 'some'. Quy tắc nâng cao của some/any.",
    lo: 'Phân biệt some/any trong câu phủ định và đề nghị.' },
  { g: 4, skill: 'functional-language', dom: 'communication', top: 'health', d: 5,
    q: 'A: "What\'s the matter?"  B: "___"', c: [
      'I am ten years old.',
      'I have a stomachache.',
      'It is sunny today.',
      'Yes, I can.',
    ], a: 1,
    ex: "'What's the matter?' hỏi bị sao/đau gì → 'I have a stomachache' (đau bụng).",
    lo: 'Trả lời câu hỏi về sức khỏe.' },
  { g: 4, skill: 'writing', dom: 'writing', top: 'word-order', d: 5, ro: true,
    tokens: ['yesterday', 'went', 'I', 'to', 'zoo', 'the', '.'],
    text: 'I went to the zoo yesterday.',
    ex: "Quá khứ: chủ ngữ + V2 + nơi chốn + thời gian. 'I went to the zoo yesterday.' - 7 từ cần sắp đúng trật tự.",
    lo: 'Sắp xếp câu quá khứ dài đúng trật tự.' },

  // ---------- GRADE 5 ----------
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'past-simple', d: 4,
    q: 'They ___ in Ha Long Bay last summer.', c: ['are', 'were', 'was', 'be'], a: 1,
    ex: "'They' số nhiều + 'last summer' → were. 'Was' chỉ đi với I/he/she/it.",
    lo: 'Dùng was/were đúng ngôi thì quá khứ.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'comparatives', d: 4,
    q: 'This book is ___ than that one.', c: ['more interesting', 'interestinger', 'most interesting', 'much interesting'], a: 0,
    ex: "Tính từ dài (interesting) so sánh hơn bằng 'more + adj'. 'Interestinger' là dạng sai kinh điển.",
    lo: 'So sánh hơn tính từ dài bằng more.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'future', d: 4,
    q: 'A: "What ___ you do this weekend?"  B: "I will visit my uncle."', c: ['do', 'will', 'did', 'are'], a: 1,
    ex: "Đáp án dùng 'will visit' → câu hỏi cũng dùng will: 'What will you do...?'",
    lo: 'Hỏi đáp thì tương lai với will.' },
  { g: 5, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'health', d: 4,
    q: 'You should see a dentist when you have a ___.', c: ['headache', 'toothache', 'stomachache', 'backache'], a: 1,
    ex: 'Đau răng (toothache) → nha sĩ (dentist). Đau đầu, đau bụng, đau lưng gặp bác sĩ khác.',
    lo: 'Ghép bệnh với chuyên khoa đúng.' },
  { g: 5, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'The Great Wall of China is more than 21,000 km long. It was built over many centuries to protect the country. Today, millions of tourists visit it every year.',
    statement: 'The Great Wall was built in one year.', bool: false,
    ex: "Bài nói 'over many centuries' - nhiều THẾ KỶ, không phải 1 năm. Chi tiết thời gian là bẫy.",
    lo: 'Đọc hiểu văn bản thông tin lịch sử.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'pronouns', d: 5,
    q: 'Minh and I are friends. ___ often play badminton together.', c: ['He', 'They', 'We', 'Us'], a: 2,
    ex: "'Minh and I' = chúng tôi → chủ ngữ We. 'Us' là tân ngữ, không đứng đầu câu.",
    lo: 'Chọn đại từ chủ ngữ thay cụm người.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'conditional', d: 5,
    q: 'If it rains tomorrow, we ___ at home.', c: ['will stay', 'stay', 'stayed', 'staying'], a: 0,
    ex: "Điều kiện loại 1: If + hiện tại đơn → vế sau dùng will + V. 'If it rains, we will stay.'",
    lo: 'Dùng câu điều kiện loại 1.' },
  { g: 5, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'environment', d: 5,
    q: 'We should ___ plastic bags to protect the ocean.', c: ['use more', 'reuse or reduce', 'throw into rivers', 'burn in the garden'], a: 1,
    ex: 'Bảo vệ đại dương → tái sử dụng hoặc giảm dùng (reuse or reduce) túi nilon. Các đáp án khác gây hại.',
    lo: 'Từ vựng chủ đề bảo vệ môi trường.' },
  { g: 5, skill: 'functional-language', dom: 'communication', top: 'advice', d: 5,
    q: 'A: "I have a bad cough."  B gives advice: "___"', c: [
      'You should drink cold Coke.',
      'You shouldn\'t see a doctor.',
      'You should drink warm water and rest.',
      'Why don\'t you run outside?',
    ], a: 2,
    ex: 'Ho → nên uống nước ấm và nghỉ ngơi. Các lời khuyên còn lại có hại hoặc vô lý.',
    lo: 'Đưa lời khuyên sức khỏe hợp lý với should.' },
  { g: 5, skill: 'writing', dom: 'writing', top: 'word-order', d: 5, ro: true,
    tokens: ['visit', 'We', 'our', 'grandparents', 'will', 'Sunday', 'next', '.'],
    text: 'We will visit our grandparents next Sunday.',
    ex: "Tương lai: chủ ngữ + will + V + tân ngữ + thời gian. 'We will visit our grandparents next Sunday.'",
    lo: 'Sắp xếp câu tương lai will + V dài.' },

  // ---------- GRADE 1 - CR-63 bo sung ----------
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'food', d: 4,
    q: 'I am round and sweet. Monkeys like me. What am I?', c: ['an apple', 'a banana', 'an egg', 'rice'], a: 1,
    ex: 'Tròn, ngọt, khỉ thích → chuối (banana). Câu đố kết hợp hình dạng + ai thích ăn.',
    lo: 'Đoán đồ vật từ 2 manh mối.' },
  { g: 1, skill: 'grammar-use-of-english', dom: 'grammar', top: 'plurals', d: 4,
    q: 'Look! I can see three ___ in the box.', c: ['ball', 'balls', 'a ball', 'the ball'], a: 1,
    ex: "'Three' cần danh từ số nhiều → balls. Không cần mạo từ a/the sau số đếm.",
    lo: 'Danh từ số nhiều sau three.' },
  { g: 1, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'colors', d: 4,
    q: 'Red + yellow = ?', c: ['green', 'orange', 'purple', 'black'], a: 1,
    ex: 'Đỏ trộn vàng ra cam (orange). Xanh lá = vàng + xanh dương, tím = đỏ + xanh dương.',
    lo: 'Kết hợp từ vựng màu với kiến thức pha màu.' },
  { g: 1, skill: 'phonics-pronunciation', dom: 'phonics', top: 'sounds', d: 4,
    q: 'Which word starts with the same sound as "sun"?', c: ['shoe', 'sock', 'sugar', 'sheep'], a: 1,
    ex: "'Sun' và 'sock' cùng âm /s/. 'Shoe', 'sheep' đọc /sh/, 'sugar' cũng đọc /sh/ - bẫy hay gặp.",
    lo: 'Phân biệt âm /s/ và /sh/ đầu từ.' },
  { g: 1, skill: 'functional-language', dom: 'communication', top: 'greetings', d: 4,
    q: 'It is 8 p.m. and you go to bed. What do you say to Mum?', c: ['Good morning!', 'Good afternoon!', 'Good night!', 'Hello!'], a: 2,
    ex: "8 giờ tối đi ngủ → 'Good night!'. Morning là buổi sáng, afternoon là buổi chiều.",
    lo: 'Chọn lời chào theo buổi trong ngày.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'animals', d: 4,
    q: 'This animal is big, grey, and has a long trunk. What is it?', c: ['a tiger', 'an elephant', 'a monkey', 'a snake'], a: 1,
    ex: 'To, xám, có vòi dài (trunk) → voi (elephant). Câu đố 3 manh mối.',
    lo: 'Nhận diện động vật từ đặc điểm.' },
  { g: 1, skill: 'grammar-use-of-english', dom: 'grammar', top: 'to-be', d: 4,
    q: 'My crayons ___ red and blue.', c: ['is', 'am', 'are', 'be'], a: 2,
    ex: "'Crayons' số nhiều → are. 'Is' chỉ đi với số ít, 'am' chỉ đi với I.",
    lo: 'Chia to be với danh từ số nhiều.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'school', d: 4,
    q: 'You use me to cut paper. I am not a pencil. What am I?', c: ['a ruler', 'scissors', 'an eraser', 'a bag'], a: 1,
    ex: 'Dùng để cắt giấy, không phải bút chì → kéo (scissors). Thước để đo, tẩy để xóa.',
    lo: 'Đoán dụng cụ học tập từ công dụng.' },
  { g: 1, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'This is my classroom. It has a board, ten desks and a big window. My bag is on my desk.',
    statement: 'The classroom has ten windows.', bool: false,
    ex: "Bài nói 'a big window' - chỉ 1 cửa sổ, 10 là số BÀN (desks). Bẫy đổi chỗ số lượng.",
    lo: 'Đọc kỹ số lượng đi kèm danh từ nào.' },
  { g: 1, skill: 'writing', dom: 'writing', top: 'word-order', d: 4, ro: true,
    tokens: ['like', 'I', 'juice', 'apple'],
    text: 'I like apple juice.',
    ex: "Khẳng định đơn giản: I like + đồ uống. 'Apple juice' là cụm cố định - nước táo.",
    lo: 'Sắp xếp câu sở thích I like.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'family', d: 5,
    q: "My father's mother is my ___.", c: ['sister', 'grandma', 'aunt', 'mum'], a: 1,
    ex: 'Mẹ của bố = bà nội (grandma). Câu đố gia đình khó hơn - lên một thế hệ.',
    lo: 'Suy luận quan hệ gia đình 2 tầng.' },
  { g: 1, skill: 'phonics-pronunciation', dom: 'phonics', top: 'sounds', d: 5,
    q: 'Which word has a DIFFERENT ending sound?', c: ['book', 'look', 'cook', 'moon'], a: 3,
    ex: "'Book', 'look', 'cook' kết thúc /k/. 'Moon' kết thúc /n/ - khác hẳn dù chữ gần giống.",
    lo: 'Nghe âm cuối khác biệt trong nhóm từ giống nhau.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'toys', d: 4,
    q: 'It has two wheels and you ride it to school. What is it?', c: ['a kite', 'a bike', 'a ball', 'a doll'], a: 1,
    ex: 'Hai bánh + đạp đi học → xe đạp (bike). Diều bay, bóng nảy, búp bê ôm.',
    lo: 'Đoán đồ chơi từ đặc điểm và cách dùng.' },
  { g: 1, skill: 'grammar-use-of-english', dom: 'grammar', top: 'have', d: 4,
    q: 'I ___ two eyes and one nose.', c: ['has', 'have', 'haves', 'having'], a: 1,
    ex: "'I' đi với 'have'. 'Has' chỉ dùng cho he/she/it - bẫy ngôi.",
    lo: 'Dùng have/has đúng ngôi.' },
  { g: 1, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'numbers', d: 4,
    q: 'Five and five is ___.', c: ['eight', 'nine', 'ten', 'eleven'], a: 2,
    ex: '5 + 5 = 10 → ten. Đọc phép cộng bằng tiếng Anh.',
    lo: 'Cộng số nhỏ qua từ vựng tiếng Anh.' },
  { g: 1, skill: 'functional-language', dom: 'communication', top: 'feelings', d: 4,
    q: 'You are hungry. What do you say?', c: ['I want some water.', 'I want some rice.', 'I am sleepy.', 'It is hot.'], a: 1,
    ex: 'Đói (hungry) → muốn ĂN: rice. Nước dành cho khát (thirsty).',
    lo: 'Nói nhu cầu ăn uống đúng cảm giác.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'body', d: 5,
    q: 'You have two of these. You use them to listen. What are they?', c: ['eyes', 'ears', 'hands', 'feet'], a: 1,
    ex: 'Hai cái + dùng để NGHE → tai (ears). Mắt để nhìn, tay để cầm, chân để đi.',
    lo: 'Ghép bộ phận cơ thể với chức năng.' },
  { g: 1, skill: 'reading', dom: 'reading', top: 'mini-read', d: 5, tf: true,
    passage: 'Mai has a red bag and a blue hat. Her brother has a green bag and a yellow hat.',
    statement: 'Mai has a blue bag.', bool: false,
    ex: 'Mai có túi ĐỎ (red bag) - mũ xanh (blue hat) mới đúng. Bẫy đảo màu giữa túi và mũ.',
    lo: 'Đọc kỹ màu sắc gắn với đúng đồ vật và người.' },
  { g: 1, skill: 'grammar-use-of-english', dom: 'grammar', top: 'this-that', d: 4,
    q: '___ are my shoes. (pointing at shoes near you)', c: ['This', 'That', 'These', 'Those'], a: 2,
    ex: "'Shoes' số nhiều + gần → These. 'This/That' số ít, 'Those' số nhiều nhưng xa.",
    lo: 'Chọn these/those theo số lượng và khoảng cách.' },
  { g: 1, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'weather', d: 4,
    q: 'The sun is hot and there are no clouds. It is a ___ day.', c: ['rainy', 'sunny', 'snowy', 'windy'], a: 1,
    ex: 'Nắng to, không mây → sunny. Rainy mưa, snowy tuyết, windy gió.',
    lo: 'Ghép tả trời với từ thời tiết.' },

  // ---------- GRADE 2 - CR-63 bo sung ----------
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'present-continuous', d: 4,
    q: 'Listen! The birds ___ in the tree.', c: ['sings', 'are singing', 'is singing', 'sing'], a: 1,
    ex: "'Listen!' + birds số nhiều → are singing. 'Is' sai vì birds số nhiều cần are.",
    lo: 'Hiện tại tiếp diễn với dấu hiệu Listen!.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'food', d: 4,
    q: 'It is white and cold. You drink it for strong bones. What is it?', c: ['juice', 'milk', 'water', 'tea'], a: 1,
    ex: 'Trắng, lạnh, tốt cho xương → sữa (milk). 3 manh mối loại trừ.',
    lo: 'Đoán đồ uống từ đặc điểm và lợi ích.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'can', d: 4,
    q: 'A bird ___ swim, but it ___ fly.', c: ['can - can', 'can - can\'t', 'can\'t - can', 'can\'t - can\'t'], a: 2,
    ex: 'Chim KHÔNG bơi được NHƯNG bay được → can\'t - can. Hai vế ngược nhau qua but.',
    lo: 'Dùng can/can\'t trong câu đối lập với but.' },
  { g: 2, skill: 'vocabulary-recognition', dom: 'vocabulary', top: 'clothes', d: 4,
    q: 'Which one do you wear on your FEET?', c: ['a hat', 'a scarf', 'shoes', 'a coat'], a: 2,
    ex: 'Đi ở chân → giày (shoes). Mũ đội đầu, khăn quàng cổ, áo khoác mặc người.',
    lo: 'Ghép trang phục với bộ phận cơ thể.' },
  { g: 2, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'On Mondays, Tom has English and Maths. On Wednesdays, he has Music and PE. He loves PE best.',
    statement: 'Tom has Music on Mondays.', bool: false,
    ex: 'Music học thứ TƯ (Wednesdays), thứ Hai là English và Maths. Bẫy đổi ngày.',
    lo: 'Đọc thời khóa biểu và ghép môn đúng ngày.' },
  { g: 2, skill: 'functional-language', dom: 'communication', top: 'polite', d: 4,
    q: 'You sneeze and your friend says "Bless you!". What do you say?', c: ['Thank you!', 'You are welcome.', 'Excuse me?', 'No problem.'], a: 0,
    ex: "Người khác nói 'Bless you' khi mình hắt hơi → đáp 'Thank you!'. Phép lịch sự đời thường.",
    lo: 'Đáp lại lời chúc xã giao.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'there-is', d: 4,
    q: '___ a park near my house.', c: ['There are', 'There is', 'There be', 'It are'], a: 1,
    ex: "'A park' số ít → There is. 'There are' dành cho số nhiều.",
    lo: 'Chọn there is cho danh từ số ít.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'days', d: 4,
    q: 'Yesterday was Sunday. Today is ___.', c: ['Saturday', 'Monday', 'Friday', 'Tuesday'], a: 1,
    ex: 'Hôm qua Chủ nhật → hôm nay thứ Hai (Monday).',
    lo: 'Suy ra hôm nay từ yesterday.' },
  { g: 2, skill: 'phonics-pronunciation', dom: 'phonics', top: 'rhymes', d: 4,
    q: 'Which word rhymes with "night"?', c: ['net', 'light', 'name', 'long'], a: 1,
    ex: "'Night' và 'light' cùng vần /ait/. Chọn từ cùng vần, không phải cùng chữ cái đầu.",
    lo: 'Nhận biết vần /ait/.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'house', d: 4,
    q: 'Mum cooks dinner here. There is a fridge and a stove. Where is it?', c: ['the bedroom', 'the bathroom', 'the kitchen', 'the garden'], a: 2,
    ex: 'Nấu ăn + tủ lạnh + bếp → nhà bếp (kitchen).',
    lo: 'Đoán phòng từ đồ vật và hoạt động.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'adjectives', d: 4,
    q: 'My sister is short, but my brother is ___.', c: ['short too', 'tall', 'small', 'little'], a: 1,
    ex: "'But' báo đối lập → thấp ngược với cao (tall). 'Short too' lặp ý, không đối lập.",
    lo: 'Chọn tính từ trái nghĩa sau but.' },
  { g: 2, skill: 'writing', dom: 'writing', top: 'word-order', d: 4, ro: true,
    tokens: ['is', 'She', 'reading', 'book', 'a'],
    text: 'She is reading a book.',
    ex: "Hiện tại tiếp diễn: chủ ngữ + is + V-ing + tân ngữ. 'She is reading a book.'",
    lo: 'Sắp xếp câu hiện tại tiếp diễn.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'weather', d: 5,
    q: 'You need an umbrella and boots today. What is the weather like?', c: ['It is sunny.', 'It is rainy.', 'It is snowy.', 'It is cloudy.'], a: 1,
    ex: 'Ô + ủng → trời MƯA (rainy). Tuyết cần áo ấm hơn là ô.',
    lo: 'Suy luận thời tiết từ đồ dùng cần mang.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'questions', d: 5,
    q: '___ is your favourite subject? - It is Music.', c: ['Who', 'What', 'Where', 'How'], a: 1,
    ex: "Đáp án là MÔN HỌC (vật/việc) → What. 'Who' hỏi người, 'Where' hỏi nơi.",
    lo: 'Chọn What cho câu hỏi về sự vật/môn học.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'jobs', d: 5,
    q: 'She works in a hospital and helps sick children. She is a ___.', c: ['teacher', 'farmer', 'doctor', 'driver'], a: 2,
    ex: 'Bệnh viện + giúp trẻ ốm → bác sĩ (doctor). 2 manh mối khớp nhau.',
    lo: 'Đoán nghề nghiệp từ nơi làm việc và công việc.' },
  { g: 2, skill: 'functional-language', dom: 'communication', top: 'requests', d: 5,
    q: 'The window is open and you are cold. What do you say politely?', c: [
      'Close it now!',
      'Can you close the window, please?',
      'I want window closed.',
      'Why window open?',
    ], a: 1,
    ex: "'Can you..., please?' - cách nhờ lịch sự. Câu đầu sai phép lịch sự, hai câu sau sai ngữ pháp.",
    lo: 'Nhờ người khác lịch sự với Can you...please.' },
  { g: 2, skill: 'reading', dom: 'reading', top: 'mini-read', d: 5, tf: true,
    passage: 'Lily is eight. She has a little brother. He is four. They both like ice cream, but Lily likes chocolate and her brother likes vanilla.',
    statement: 'Lily and her brother like different flavours of ice cream.', bool: true,
    ex: 'Lily thích sô-cô-la, em thích va-ni → vị KHÁC nhau = đúng. Câu này phải đọc hết câu cuối mới biết.',
    lo: 'Đọc câu cuối để so sánh sở thích hai nhân vật.' },
  { g: 2, skill: 'grammar-use-of-english', dom: 'grammar', top: 'possessives', d: 5,
    q: 'That is not my pencil. It is ___. (pointing to Lan)', c: ['her', 'hers', 'she', 'Lan pencil'], a: 1,
    ex: "Đứng một mình sau is cần đại từ sở hữu 'hers' - 'It is hers'. 'Her' phải đi kèm danh từ.",
    lo: 'Dùng đại từ sở hữu hers không kèm danh từ.' },
  { g: 2, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'routines', d: 4,
    q: 'I do this after dinner and before bed. I use a toothbrush. What do I do?', c: ['I wash my face.', 'I brush my teeth.', 'I comb my hair.', 'I take a bath.'], a: 1,
    ex: 'Dùng bàn chải đánh răng (toothbrush) → đánh răng (brush my teeth). Manh mối dụng cụ quyết định.',
    lo: 'Ghép hoạt động buổi tối với dụng cụ.' },
  { g: 2, skill: 'writing', dom: 'writing', top: 'word-order', d: 5, ro: true,
    tokens: ['there', 'Are', 'any', 'eggs', 'the', 'in', 'fridge', '?'],
    text: 'Are there any eggs in the fridge?',
    ex: "Câu hỏi có/không số nhiều: Are there + any + danh từ? 'Are there any eggs in the fridge?' - 8 từ.",
    lo: 'Sắp xếp câu hỏi Are there any.' },

  // ---------- GRADE 3 - CR-63 bo sung ----------
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'present-simple', d: 4,
    q: 'My dad ___ breakfast for us every morning.', c: ['cook', 'cooks', 'cooking', 'is cook'], a: 1,
    ex: "Ngôi 3 số ít (dad) + 'every morning' → cooks. 'Is cook' sai cấu trúc.",
    lo: 'Thêm s/es cho động từ ngôi 3 hiện tại đơn.' },
  { g: 3, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'months', d: 4,
    q: 'Tet holiday in Vietnam is usually in January or ___.', c: ['March', 'February', 'June', 'September'], a: 1,
    ex: 'Tết thường rơi vào tháng 1 hoặc tháng 2 (February). Kết hợp từ vựng tháng + văn hóa Việt.',
    lo: 'Ghép tháng với sự kiện thực tế.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'prepositions', d: 4,
    q: 'The pencil is ___ the box - open the lid and you will see it.', c: ['under', 'on', 'in', 'behind'], a: 2,
    ex: 'Mở nắp mới thấy → bút chì ở TRONG hộp (in). On là trên nắp - nhìn thấy ngay.',
    lo: 'Chọn in/on/under theo manh mối ngữ cảnh.' },
  { g: 3, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'Our school has Sports Day in April. Students run races, jump far and throw balls. The winner of each race gets a medal.',
    statement: 'Sports Day is in May.', bool: false,
    ex: "Bài ghi rõ 'in April' - tháng 4, không phải tháng 5. Chi tiết thời gian đầu bài.",
    lo: 'Đọc chi tiết thời gian trong bài thông báo.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'present-continuous', d: 4,
    q: 'Be quiet! The baby ___ upstairs.', c: ['sleeps', 'is sleeping', 'sleep', 'sleeping'], a: 1,
    ex: "'Be quiet!' báo hành động đang diễn ra → is sleeping. Baby ngôi 3 số ít dùng is.",
    lo: 'Hiện tại tiếp diễn với dấu hiệu Be quiet!.' },
  { g: 3, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'sports', d: 4,
    q: 'You need a racket and a small ball for this sport. What is it?', c: ['football', 'table tennis', 'swimming', 'running'], a: 1,
    ex: 'Vợt (racket) + bóng nhỏ → bóng bàn (table tennis). Bóng đá không cần vợt.',
    lo: 'Ghép môn thể thao với dụng cụ.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'questions', d: 4,
    q: '___ do you go to school? - By bike.', c: ['What', 'How', 'When', 'Who'], a: 1,
    ex: "Đáp án là PHƯƠNG TIỆN (by bike) → hỏi cách thức How. 'What' hỏi vật, 'When' hỏi giờ.",
    lo: 'Hỏi How cho phương tiện/cách thức.' },
  { g: 3, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'jobs', d: 4,
    q: 'He drives a big red truck and stops fires. He is a ___.', c: ['police officer', 'firefighter', 'doctor', 'pilot'], a: 1,
    ex: 'Xe đỏ lớn + dập lửa → lính cứu hỏa (firefighter).',
    lo: 'Đoán nghề từ phương tiện và nhiệm vụ.' },
  { g: 3, skill: 'functional-language', dom: 'communication', top: 'offers', d: 4,
    q: 'A: "Would you like some orange juice?"  B says NO politely: "___"', c: [
      'No, I hate it.',
      'No, thank you.',
      'Never!',
      'I do not want.',
    ], a: 1,
    ex: "Từ chối lịch sự: 'No, thank you.' Các câu khác thô hoặc sai ngữ pháp.",
    lo: 'Từ chối lời mời lịch sự.' },
  { g: 3, skill: 'writing', dom: 'writing', top: 'word-order', d: 4, ro: true,
    tokens: ['does', 'What', 'your', 'do', 'mother', '?'],
    text: 'What does your mother do?',
    ex: "Hỏi nghề nghiệp: What + does + chủ ngữ + do? 'What does your mother do?' - does đi với ngôi 3.",
    lo: 'Sắp xếp câu hỏi nghề nghiệp What does...do.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'adverbs', d: 5,
    q: 'He is a careful driver. He drives ___.', c: ['careful', 'carefully', 'care', 'caring'], a: 1,
    ex: 'Động từ (drives) cần TRẠNG TỪ carefully. Careful là tính từ - đứng sau is thì đúng.',
    lo: 'Đổi tính từ sang trạng từ bằng -ly.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'plurals-irregular', d: 5,
    q: 'The dentist says I have healthy ___.', c: ['tooths', 'teeth', 'teeths', 'toothes'], a: 1,
    ex: "Số nhiều bất quy tắc: tooth → teeth. 'Tooths' và 'teeths' đều sai.",
    lo: 'Danh từ số nhiều bất quy tắc tooth/teeth.' },
  { g: 3, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'weather', d: 5,
    q: 'It is not hot and not cold - about 20 degrees. The weather is ___.', c: ['freezing', 'warm', 'boiling', 'stormy'], a: 1,
    ex: 'Không nóng không lạnh, 20 độ → ấm áp (warm). Freezing là giá lạnh, boiling là nóng sôi.',
    lo: 'Chọn từ thời tiết theo nhiệt độ.' },
  { g: 3, skill: 'reading', dom: 'reading', top: 'mini-read', d: 5, tf: true,
    passage: 'The school trip is on Saturday. Students meet at the school gate at 7:30. They must bring a hat and a water bottle. Lunch is at the farm.',
    statement: 'Students eat lunch at school.', bool: false,
    ex: "Bài nói 'Lunch is at the farm' - ăn trưa ở TRANG TRẠI, không phải ở trường. Chi tiết cuối bài.",
    lo: 'Đọc kỹ địa điểm trong thông tin chuyến đi.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'frequency', d: 5,
    q: 'I ___ eat sweets - only on my birthday.', c: ['always', 'usually', 'often', 'rarely'], a: 3,
    ex: "Chỉ ngày sinh nhật = gần như không bao giờ → rarely (hiếm khi). Always/usually/often đều quá nhiều.",
    lo: 'Chọn trạng từ tần suất theo ngữ cảnh.' },
  { g: 3, skill: 'functional-language', dom: 'communication', top: 'opinions', d: 4,
    q: 'A: "I think maths is fun!"  B does NOT agree. B says: "___"', c: [
      'Me too!',
      'I think so too.',
      'I do not think so - it is boring!',
      'Yes, maths is fun!',
    ], a: 2,
    ex: "Không đồng ý → 'I do not think so'. Ba câu kia đều đồng thuận - đọc kỹ chữ NOT.",
    lo: 'Nhận biết câu bày tỏ bất đồng.' },
  { g: 3, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'school', d: 4,
    q: 'At school, the break between lessons is called ___.', c: ['homework', 'playtime', 'detention', 'assembly'], a: 1,
    ex: 'Giờ ra chơi giữa các tiết = playtime (break time). Homework là bài tập về nhà.',
    lo: 'Từ vựng đời sống học đường.' },
  { g: 3, skill: 'grammar-use-of-english', dom: 'grammar', top: 'countable', d: 5,
    q: 'How ___ water do you drink every day?', c: ['many', 'much', 'long', 'often'], a: 1,
    ex: "'Water' không đếm được → How much. 'How many' dành cho danh từ đếm được.",
    lo: 'Chọn how much cho danh từ không đếm được.' },
  { g: 3, skill: 'writing', dom: 'writing', top: 'word-order', d: 5, ro: true,
    tokens: ['sometimes', 'My', 'walks', 'dog', 'my', 'to', 'park', 'the', '.'],
    text: 'My dog sometimes walks to the park.',
    ex: "Trạng từ tần suất đứng trước động từ chính: 'My dog sometimes walks to the park.' - 9 từ khó.",
    lo: 'Đặt trạng từ tần suất đúng vị trí.' },
  { g: 3, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'animals', d: 4,
    q: 'This bird cannot fly but it swims very well in cold seas. What is it?', c: ['a parrot', 'a penguin', 'an eagle', 'a duck'], a: 1,
    ex: 'Chim không bay + bơi giỏi + biển lạnh → chim cánh cụt (penguin). Vịt bay được.',
    lo: 'Đoán động vật từ 3 đặc điểm.' },

  // ---------- GRADE 4 - CR-63 bo sung ----------
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'past-simple', d: 4,
    q: 'We ___ a great film at the cinema last weekend.', c: ['see', 'saw', 'seen', 'seeing'], a: 1,
    ex: "'Last weekend' → quá khứ: saw (bất quy tắc của see). 'Seen' cần have/has.",
    lo: 'Quá khứ bất quy tắc see/saw.' },
  { g: 4, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'nature', d: 4,
    q: 'It is taller than a hill but smaller than the sky. What is it?', c: ['a river', 'a mountain', 'a beach', 'a forest'], a: 1,
    ex: 'Cao hơn đồi (hill) → núi (mountain). Câu so sánh đoán địa hình.',
    lo: 'Đoán địa danh từ so sánh.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'comparatives', d: 4,
    q: 'A plane is ___ than a car.', c: ['more fast', 'most fast', 'faster', 'fastest'], a: 2,
    ex: "Tính từ ngắn 'fast' + er → faster than. 'More fast' sai - fast không cần more.",
    lo: 'So sánh hơn tính từ ngắn với -er.' },
  { g: 4, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'Da Nang is a city by the sea in central Vietnam. It has a famous Dragon Bridge. Every weekend the bridge breathes fire and water at 9 p.m.',
    statement: 'The Dragon Bridge show happens every morning.', bool: false,
    ex: "Show diễn ra '9 p.m.' - 9 giờ TỐI, không phải buổi sáng. Bẫy p.m. vs sáng.",
    lo: 'Đọc chi tiết giờ trong bài về địa danh.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'questions', d: 4,
    q: '___ did you go to bed last night? - At 9 o\'clock.', c: ['Where', 'What', 'When', 'Who'], a: 2,
    ex: "Đáp án là GIỜ (at 9 o'clock) → hỏi When. Where hỏi nơi, Who hỏi người.",
    lo: 'Chọn When cho câu trả lời về thời gian.' },
  { g: 4, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'food', d: 4,
    q: 'Pho is a famous Vietnamese ___.', c: ['drink', 'dessert', 'dish', 'fruit'], a: 2,
    ex: 'Phở là MÓN ĂN (dish). Drink là đồ uống, dessert là tráng miệng, fruit là trái cây.',
    lo: 'Phân loại dish/drink/dessert với món Việt.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'past-simple', d: 4,
    q: 'They ___ to school yesterday because it rained heavily.', c: ['didn\'t walk', 'don\'t walk', 'doesn\'t walk', 'not walk'], a: 0,
    ex: "Phủ định quá khứ: didn't + V nguyên mẫu → didn't walk. Yesterday báo quá khứ.",
    lo: 'Phủ định quá khứ với chủ ngữ số nhiều.' },
  { g: 4, skill: 'functional-language', dom: 'communication', top: 'apology', d: 4,
    q: 'You broke your friend\'s toy. What do you say?', c: [
      'It is not my fault!',
      'I am really sorry. Can I buy you a new one?',
      'Who cares?',
      'Your toy was bad anyway.',
    ], a: 1,
    ex: 'Làm hỏng đồ bạn → xin lỗi + đền bù: sorry + buy a new one. Các câu khác thô hoặc đổ lỗi.',
    lo: 'Xin lỗi kèm đền bù đúng tình huống.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'going-to', d: 4,
    q: 'We ___ visit Hue next holiday. We already booked the hotel.', c: ['is going to', 'are going to', 'going to', 'will to'], a: 1,
    ex: "'We' số nhiều → are going to. Đã đặt khách sạn = kế hoạch chắc chắn.",
    lo: 'Be going to với chủ ngữ số nhiều.' },
  { g: 4, skill: 'writing', dom: 'writing', top: 'word-order', d: 4, ro: true,
    tokens: ['did', 'What', 'you', 'do', 'weekend', 'last', '?'],
    text: 'What did you do last weekend?',
    ex: "Câu hỏi quá khứ: What + did + chủ ngữ + V nguyên mẫu? 'What did you do last weekend?'",
    lo: 'Sắp xếp câu hỏi quá khứ What did.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'present-perfect-feel', d: 5,
    q: 'I have ___ my keys! I cannot open the door.', c: ['lose', 'losing', 'lost', 'losed'], a: 2,
    ex: "Sau 'have' cần quá khứ phân từ: lost. 'Losed' không tồn tại - lose → lost bất quy tắc.",
    lo: 'Quá khứ phân từ bất quy tắc lose/lost.' },
  { g: 4, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'festivals', d: 5,
    q: 'At Mid-Autumn Festival, children carry ___ and eat mooncakes.', c: ['lanterns', 'flags', 'umbrellas', 'kites'], a: 0,
    ex: 'Trung thu rước ĐÈN LỒNG (lanterns) + ăn bánh trung thu (mooncakes). Văn hóa Việt qua tiếng Anh.',
    lo: 'Từ vựng lễ hội Việt Nam bằng tiếng Anh.' },
  { g: 4, skill: 'reading', dom: 'reading', top: 'mini-read', d: 5, tf: true,
    passage: 'Ha Long Bay has thousands of islands made of stone. The best way to see it is by boat. In summer it is very busy, so book tickets early.',
    statement: 'Ha Long Bay is quiet and empty in summer.', bool: false,
    ex: "Bài nói mùa hè 'very busy' - rất ĐÔNG, ngược với 'quiet and empty'. Đọc cả câu cuối.",
    lo: 'Đọc chi tiết mô tả mùa du lịch.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'wh-questions', d: 5,
    q: '___ bag is this? - It is Lan\'s.', c: ['Who', 'Whose', 'Who\'s', 'Which one'], a: 1,
    ex: "Đáp án chỉ SỞ HỮU (Lan's) → hỏi Whose. 'Who's' là viết tắt của who is - bẫy kinh điển.",
    lo: 'Phân biệt Whose vs Who\'s.' },
  { g: 4, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'transport', d: 5,
    q: 'It flies and carries hundreds of people between cities. What is it?', c: ['a train', 'a plane', 'a ferry', 'a coach'], a: 1,
    ex: 'Bay + chở hàng trăm người giữa các thành phố → máy bay (plane). Ferry đi biển, coach đi đường.',
    lo: 'Đoán phương tiện từ chức năng.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'subject-verb', d: 5,
    q: 'Neither my dad nor my mum ___ coffee in the evening.', c: ['drink', 'drinks', 'drinking', 'is drink'], a: 1,
    ex: 'Với neither/nor, động từ chia theo chủ ngữ GẦN nhất: mum (số ít) → drinks. Quy tắc proximity khó.',
    lo: 'Hòa hợp chủ-vị gần nhất với neither/nor.' },
  { g: 4, skill: 'functional-language', dom: 'communication', top: 'suggestions', d: 5,
    q: 'A: "I am bored this afternoon."  B suggests: "___"', c: [
      'Why don\'t we go swimming?',
      'I am happy for you.',
      'Bored is good.',
      'You will be bored.',
    ], a: 0,
    ex: "Đề nghị hoạt động → 'Why don't we...?' - cấu trúc gợi ý chuẩn.",
    lo: 'Đưa gợi ý với Why don\'t we.' },
  { g: 4, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'health', d: 4,
    q: 'If you have a fever, you should NOT ___.', c: ['rest in bed', 'drink water', 'play football outside', 'tell your parents'], a: 2,
    ex: 'Sốt thì không nên chạy đá bóng ngoài trời. Ba việc kia đều nên làm khi ốm.',
    lo: 'Chọn hành động sai cho tình huống sức khỏe.' },
  { g: 4, skill: 'grammar-use-of-english', dom: 'grammar', top: 'too-enough', d: 5,
    q: 'This bag is ___ heavy for me to carry.', c: ['enough', 'too', 'very much', 'so much'], a: 1,
    ex: "'Too + adj' = quá... không làm được. 'Enough' đứng SAU tính từ - vị trí khác.",
    lo: 'Dùng too + adjective cho vượt quá mức.' },
  { g: 4, skill: 'writing', dom: 'writing', top: 'word-order', d: 5, ro: true,
    tokens: ['were', 'there', 'many', 'How', 'people', 'the', 'at', 'party', '?'],
    text: 'How many people were there at the party?',
    ex: "Hỏi số lượng quá khứ: How many + danh từ + were there...? 'How many people were there at the party?' - 9 từ.",
    lo: 'Sắp xếp câu hỏi How many quá khứ dài.' },

  // ---------- GRADE 5 - CR-63 bo sung ----------
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'past-simple', d: 4,
    q: 'She ___ born in 2015.', c: ['is', 'was', 'were', 'did'], a: 1,
    ex: "Sinh năm 2015 → quá khứ: 'was born'. Cụm cố định be born, không dùng do/did.",
    lo: 'Dùng was/were born cho năm sinh.' },
  { g: 5, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'seasons', d: 4,
    q: 'In northern Vietnam, which season is cool and dry - good for trips?', c: ['summer', 'autumn', 'rainy season', 'winter storm'], a: 1,
    ex: 'Mùa thu (autumn) miền Bắc mát mẻ, khô ráo - thích hợp đi chơi. Hè nóng, mùa mưa ẩm.',
    lo: 'Ghép mùa với đặc điểm khí hậu miền Bắc.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'future', d: 4,
    q: 'The sky is clear and I have plans. I think I ___ go camping tomorrow.', c: ['am', 'will', 'did', 'was'], a: 1,
    ex: "Dự đoán/quyết định tương lai → will + V: 'I will go camping.' Tomorrow báo tương lai.",
    lo: 'Chọn will cho kế hoạch tương lai.' },
  { g: 5, skill: 'reading', dom: 'reading', top: 'mini-read', d: 4, tf: true,
    passage: 'The Mekong Delta is in southern Vietnam. Farmers there grow rice and fruit. Many people travel by boat because rivers are everywhere.',
    statement: 'In the Mekong Delta, boats are a common way to travel.', bool: true,
    ex: "Bài nói 'many people travel by boat because rivers are everywhere' → thuyền là phương tiện phổ biến = Đúng.",
    lo: 'Suy luận đúng từ nguyên nhân trong bài đọc.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'comparatives', d: 4,
    q: 'English is ___ subject for me - I get 10 every test.', c: ['the easiest', 'easier', 'more easy', 'most easy'], a: 0,
    ex: "So sánh NHẤT trong các môn → the easiest. 'More easy' sai: easy ngắn, dùng easier/easiest.",
    lo: 'So sánh nhất tính từ kết thúc -y.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'adverbs', d: 4,
    q: 'She sings ___. Everyone loves her voice.', c: ['beautiful', 'beautifully', 'beauty', 'more beautiful'], a: 1,
    ex: 'Động từ sings cần trạng từ beautifully. Beautiful là tính từ - chỉ đi với danh từ/be.',
    lo: 'Trạng từ -ly bổ nghĩa cho động từ.' },
  { g: 5, skill: 'functional-language', dom: 'communication', top: 'directions', d: 4,
    q: 'A tourist asks how to get to the museum. You say: "___"', c: [
      'I do not know anything.',
      'Go straight and turn right at the bank.',
      'The museum is old.',
      'I like museums.',
    ], a: 1,
    ex: "Hỏi đường → chỉ đường: 'Go straight and turn right...' Câu văn miêu tả không phải chỉ đường.",
    lo: 'Chỉ đường cho du khách.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'questions', d: 4,
    q: '___ does the film start? - At half past seven.', c: ['What time', 'How long', 'How far', 'How much'], a: 0,
    ex: "Đáp án là GIỜ CỤ THỂ (7:30) → What time. 'How long' hỏi độ dài thời gian, 'How far' hỏi khoảng cách.",
    lo: 'Phân biệt what time/how long/how far.' },
  { g: 5, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'environment', d: 4,
    q: 'We should plant more ___ to make the air cleaner.', c: ['plastic bags', 'trees', 'cars', 'buildings'], a: 1,
    ex: 'Trồng CÂY (trees) làm sạch không khí. Túi nilon, xe cộ, tòa nhà đều không lọc không khí.',
    lo: 'Từ vựng hành động bảo vệ môi trường.' },
  { g: 5, skill: 'writing', dom: 'writing', top: 'word-order', d: 4, ro: true,
    tokens: ['going', 'We', 'are', 'to', 'have', 'picnic', 'a', '.'],
    text: 'We are going to have a picnic.',
    ex: "Be going to + V cho kế hoạch: 'We are going to have a picnic.' - 8 từ.",
    lo: 'Sắp xếp câu kế hoạch be going to.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'relative-feel', d: 5,
    q: 'This is the book ___ my teacher gave me.', c: ['who', 'that', 'whom', 'where'], a: 1,
    ex: "'Book' là VẬT → dùng 'that' (hoặc which). 'Who/whom' chỉ dùng cho người, 'where' cho nơi chốn.",
    lo: 'Chọn đại từ quan hệ that cho vật.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'reported-feel', d: 5,
    q: 'He said he ___ tired, so he went to bed early.', c: ['is', 'was', 'will be', 'has been'], a: 1,
    ex: "Câu tường thuật quá khứ: said + was (lùi thì). 'Is' sai vì câu chính đã quá khứ.",
    lo: 'Lùi thì trong câu tường thuật đơn giản.' },
  { g: 5, skill: 'reading', dom: 'reading', top: 'mini-read', d: 5, tf: true,
    passage: 'Son Doong is the biggest cave in the world. It is in Quang Binh province. Inside, there are rivers, forests and even clouds. Only 1,000 visitors can enter each year.',
    statement: 'Anyone can visit Son Doong at any time.', bool: false,
    ex: "Bài nói 'only 1,000 visitors each year' - GIỚI HẠN số lượng, không phải ai cũng vào được bất cứ lúc nào.",
    lo: 'Đọc hiểu giới hạn trong bài về địa danh nổi tiếng.' },
  { g: 5, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'city-life', d: 5,
    q: 'In a big city, rush hour is when ___.', c: [
      'everyone sleeps',
      'traffic is heaviest - morning and evening',
      'shops close early',
      'it starts raining',
    ], a: 1,
    ex: 'Rush hour = giờ cao điểm, giao thông đông nhất sáng và chiều. Từ vựng đời sống đô thị.',
    lo: 'Hiểu thuật ngữ rush hour.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'should', d: 5,
    q: 'You ___ cheat in the exam. It is wrong and you learn nothing.', c: ['should', 'should not', 'must to', 'ought'], a: 1,
    ex: "Gian lận là SAI → should not (không nên). 'Must to' sai cấu trúc - must + V không to.",
    lo: 'Khuyên không nên làm việc sai với should not.' },
  { g: 5, skill: 'functional-language', dom: 'communication', top: 'congratulations', d: 5,
    q: 'Your friend won first prize in the English contest. You say: "___"', c: [
      'Better luck next time.',
      'Congratulations! You worked so hard!',
      'It was just luck.',
      'I wanted that prize.',
    ], a: 1,
    ex: "Bạn thắng giải → chúc mừng: 'Congratulations!' 'Better luck next time' dùng khi THUA.",
    lo: 'Chúc mừng thành tích đúng tình huống.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'quantifiers', d: 5,
    q: 'There are ___ students in the hall - I counted over five hundred!', c: ['a few', 'a little', 'lots of', 'much'], a: 2,
    ex: "500 học sinh = NHIỀU → lots of (đếm được số nhiều). 'A few' là ít, 'much/a little' không đếm được.",
    lo: 'Chọn lượng từ cho danh từ đếm được số lượng lớn.' },
  { g: 5, skill: 'writing', dom: 'writing', top: 'word-order', d: 5, ro: true,
    tokens: ['If', 'it', 'sunny', 'is', 'tomorrow', 'we', 'will', 'play', 'outside', '.'],
    text: 'If it is sunny tomorrow, we will play outside.',
    ex: "Điều kiện loại 1: If + hiện tại đơn, will + V ở vế chính. 'If it is sunny tomorrow, we will play outside.' - 10 từ khó.",
    lo: 'Sắp xếp câu điều kiện loại 1 hoàn chỉnh.' },
  { g: 5, skill: 'vocabulary-in-context', dom: 'vocabulary', top: 'technology', d: 4,
    q: 'You can use this device to call friends, play games and take photos. What is it?', c: ['a television', 'a smartphone', 'a radio', 'a camera'], a: 1,
    ex: 'Gọi điện + chơi game + chụp ảnh = điện thoại thông minh (smartphone). Camera không gọi được.',
    lo: 'Đoán thiết bị từ 3 chức năng.' },
  { g: 5, skill: 'grammar-use-of-english', dom: 'grammar', top: 'passive-feel', d: 5,
    q: 'The Temple of Literature ___ in 1070.', c: ['built', 'was built', 'is building', 'has built'], a: 1,
    ex: "Công trình ĐƯỢC xây năm 1070 → bị động quá khứ: was built. Văn miếu Quốc Tử Giam - sử Việt.",
    lo: 'Nhận biết thể bị động quá khứ đơn giản.' },
];
