/** CR-59 - authored ADVANCED science-in-English items (difficulty 4-5). */
export const ITEMS = [
  // ---------- GRADE 1 ----------
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'animals', d: 4,
    q: 'Which animal can FLY?', c: ['dog', 'fish', 'bird', 'cat'], a: 2,
    ex: 'Bird (chim) biết bay. Dog và cat đi trên đất, fish bơi dưới nước.',
    lo: 'Phân biệt đặc điểm di chuyển của động vật.' },
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'animals', d: 4,
    q: 'Which animal lives in the water?', c: ['elephant', 'fish', 'monkey', 'chicken'], a: 1,
    ex: 'Fish (cá) sống dưới nước. Elephant, monkey và chicken sống trên cạn.',
    lo: 'Nhận biết môi trường sống của động vật.' },
  { g: 1, skill: 'scientific-observation', dom: 'living-things', top: 'body', d: 4,
    q: 'We use our eyes to ___ and our ears to ___.', c: ['hear - see', 'see - hear', 'smell - see', 'see - taste'], a: 1,
    ex: 'Mắt (eyes) để nhìn - see; tai (ears) để nghe - hear. Ghép đúng giác quan với cơ quan.',
    lo: 'Ghép giác quan với chức năng đúng.' },
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'plants', d: 4,
    q: 'Which part of the plant is UNDER the ground?', c: ['leaf', 'flower', 'root', 'fruit'], a: 2,
    ex: 'Rễ (root) nằm dưới đất, hút nước cho cây. Lá, hoa, quả đều ở trên mặt đất.',
    lo: 'Nhận biết các bộ phận của cây.' },
  { g: 1, skill: 'scientific-observation', dom: 'materials', top: 'objects', d: 4,
    q: 'Which one is soft?', c: ['a rock', 'a pillow', 'a door', 'a spoon'], a: 1,
    ex: 'Pillow (gối) mềm. Đá, cửa và thìa đều cứng.',
    lo: 'Phân biệt vật liệu mềm - cứng.' },
  { g: 1, skill: 'science-concept', dom: 'earth', top: 'weather', d: 4,
    q: 'What do we wear when it Rains?', c: ['sunglasses', 'a raincoat', 'shorts', 'a hat for the sun'], a: 1,
    ex: 'Raincoat (áo mưa) mặc khi trời mưa. Kính râm và mũ nắng dùng khi trời nắng.',
    lo: 'Liên hệ thời tiết với trang phục phù hợp.' },
  { g: 1, skill: 'science-reasoning', dom: 'living-things', top: 'animals', d: 4,
    q: 'A duck has two legs and feathers. Which animal is most like a duck?', c: ['dog', 'chicken', 'fish', 'snake'], a: 1,
    ex: 'Chicken (gà) cũng có 2 chân và lông vũ - cùng nhóm chim với vịt. Các con khác không có lông.',
    lo: 'Phân loại động vật theo đặc điểm chung.' },
  { g: 1, skill: 'science-concept', dom: 'earth', top: 'day-night', d: 4,
    q: 'What do we see in the sky at NIGHT?', c: ['the sun', 'the moon', 'a rainbow', 'clouds only'], a: 1,
    ex: 'Ban đêm nhìn thấy mặt trăng (moon). Mặt trời chỉ thấy ban ngày.',
    lo: 'Phân biệt hiện tượng ngày - đêm.' },
  { g: 1, skill: 'science-reasoning', dom: 'living-things', top: 'needs', d: 4,
    q: 'A plant needs water, sunlight and ___ to grow.', c: ['candy', 'toys', 'air', 'milk'], a: 2,
    ex: 'Cây cần nước, ánh sáng và KHÔNG KHÍ (air) để sống. Kẹo, đồ chơi, sữa không giúp cây lớn.',
    lo: 'Biết điều kiện sống cơ bản của thực vật.' },
  { g: 1, skill: 'scientific-observation', dom: 'materials', top: 'objects', d: 4,
    q: 'Which object can float on water?', c: ['a coin', 'a wooden block', 'a key', 'a stone'], a: 1,
    ex: 'Gỗ (wooden block) nổi trên nước. Xu, chìa khóa và đá đều chìm vì nặng hơn nước.',
    lo: 'Dự đoán vật nổi - chìm theo vật liệu.' },
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'animals', d: 5,
    q: 'A baby cat is a kitten. A baby dog is a ___.', c: ['calf', 'puppy', 'chick', 'cub'], a: 1,
    ex: 'Con chó con là puppy. Calf là bò con, chick là gà con, cub là thú con như sư tử con.',
    lo: 'Biết tên con non của động vật quen thuộc.' },
  { g: 1, skill: 'science-reasoning', dom: 'living-things', top: 'food', d: 5,
    q: 'A rabbit eats carrots and grass. A lion eats meat. Which is TRUE?', c: [
      'The lion is a plant-eater',
      'The rabbit is a meat-eater',
      'The rabbit eats plants',
      'The lion eats grass',
    ], a: 2,
    ex: 'Thỏ ăn cà rốt và cỏ - tức ăn thực vật (plant-eater). Sư tử ăn thịt. Đọc kỹ từng đáp án.',
    lo: 'Phân biệt động vật ăn thực vật và ăn thịt.' },

  // ---------- GRADE 2 ----------
  { g: 2, skill: 'science-concept', dom: 'living-things', top: 'habitats', d: 4,
    q: 'A polar bear lives in a very cold place. Where does it live?', c: ['the desert', 'the Arctic', 'the jungle', 'the ocean'], a: 1,
    ex: 'Gấu Bắc Cực sống ở Arctic - vùng băng giá lạnh. Sa mạc nóng, rừng nhiệt đới ẩm nóng.',
    lo: 'Ghép động vật với môi trường sống phù hợp.' },
  { g: 2, skill: 'science-reasoning', dom: 'living-things', top: 'habitats', d: 4,
    q: 'A camel can live many days without water. Where does it live?', c: ['the sea', 'the forest', 'the desert', 'the mountain'], a: 2,
    ex: 'Lạc đà chịu khát rất lâu - thích nghi với sa mạc (desert) khô nóng.',
    lo: 'Suy luận môi trường sống từ đặc điểm thích nghi.' },
  { g: 2, skill: 'science-concept', dom: 'living-things', top: 'life-cycles', d: 4,
    q: 'What does a caterpillar become?', c: ['a bee', 'a butterfly', 'a bird', 'a spider'], a: 1,
    ex: 'Sâu bướm (caterpillar) biến thành bướm (butterfly) qua kén - chu kỳ sống của bướm.',
    lo: 'Biết chu kỳ biến thái của bướm.' },
  { g: 2, skill: 'science-concept', dom: 'earth', top: 'seasons', d: 4,
    q: 'Leaves fall from the trees and the weather gets cooler. Which season is it?', c: ['spring', 'summer', 'autumn', 'winter'], a: 2,
    ex: 'Lá rụng + trời mát dần = mùa thu (autumn). Mùa đông lạnh hơn nữa và nhiều cây đã trụi lá.',
    lo: 'Nhận diện đặc điểm các mùa.' },
  { g: 2, skill: 'science-reasoning', dom: 'materials', top: 'materials', d: 4,
    q: 'A raincoat is made of plastic because plastic is ___.', c: ['soft', 'waterproof', 'heavy', 'warm'], a: 1,
    ex: 'Áo mưa cần chống nước (waterproof) - nhựa không thấm nước. Mềm hay ấm không phải lý do chính.',
    lo: 'Liên hệ tính chất vật liệu với công dụng.' },
  { g: 2, skill: 'science-reasoning', dom: 'materials', top: 'materials', d: 4,
    q: 'Which material is best for a window?', c: ['wood', 'paper', 'glass', 'cloth'], a: 2,
    ex: 'Cửa sổ cần TRONG SUỐT để lấy sáng - chỉ có kính (glass) trong. Gỗ, giấy, vải không xuyên ánh sáng.',
    lo: 'Chọn vật liệu theo tính chất trong suốt.' },
  { g: 2, skill: 'scientific-observation', dom: 'living-things', top: 'senses', d: 4,
    q: 'Honey is sweet. Lemons are sour. We know this using our sense of ___.', c: ['sight', 'hearing', 'taste', 'smell'], a: 2,
    ex: 'Vị ngọt và chua nhận biết bằng vị giác (taste). Khứu giác ngửi mùi, không phân biệt được vị.',
    lo: 'Ghép hiện tượng với giác quan đúng.' },
  { g: 2, skill: 'science-concept', dom: 'earth', top: 'water', d: 4,
    q: 'Rain falls down to Earth from ___.', c: ['the sea only', 'clouds', 'the moon', 'rivers'], a: 1,
    ex: 'Mưa rơi từ mây (clouds) khi hơi nước ngưng tụ đủ nặng. Biển là nơi nước bốc hơi, không phải nơi mưa rơi xuống trực tiếp.',
    lo: 'Hiểu vòng tuần hoàn nước đơn giản.' },
  { g: 2, skill: 'science-reasoning', dom: 'living-things', top: 'animals', d: 4,
    q: 'Fish breathe with gills. Whales live in the sea but breathe with lungs. What must a whale do?', c: [
      'Stay underwater forever',
      'Come up to the surface to breathe air',
      'Grow gills like a fish',
      'Stop breathing',
    ], a: 1,
    ex: 'Cá voi thở bằng PHỔI (lungs) nên phải nổi lên mặt nước hít không khí - dù sống dưới nước.',
    lo: 'Suy luận hành vi từ đặc điểm sinh học.' },
  { g: 2, skill: 'science-concept', dom: 'living-things', top: 'plants', d: 4,
    q: 'Seeds need water and warmth to start growing. This is called ___.', c: ['germination', 'photosynthesis', 'hibernation', 'melting'], a: 0,
    ex: 'Hạt nảy mầm = germination. Photosynthesis là quang hợp, hibernation là ngủ đông - từ vựng nâng cao cần phân biệt.',
    lo: 'Dùng thuật ngữ nảy mầm đúng.' },
  { g: 2, skill: 'science-reasoning', dom: 'earth', top: 'weather', d: 5,
    q: 'The weather report says a storm is coming tomorrow. What should people do?', c: [
      'Go swimming at the beach',
      'Fly kites in the park',
      'Stay inside and close the windows',
      'Have a picnic outside',
    ], a: 2,
    ex: 'Bão đến cần ở trong nhà, đóng cửa sổ cho an toàn. Các hoạt động ngoài trời đều nguy hiểm khi có bão.',
    lo: 'Ra quyết định an toàn theo dự báo thời tiết.' },
  { g: 2, skill: 'scientific-observation', dom: 'living-things', top: 'groups', d: 5,
    q: 'Which one does NOT belong to the group?', c: ['a bee', 'an ant', 'a spider', 'a butterfly'], a: 2,
    ex: 'Ong, kiến, bướm đều là CÔN TRÙNG (6 chân). Nhện có 8 chân - không phải côn trùng.',
    lo: 'Phân loại côn trùng và động vật khác.' },

  // ---------- GRADE 3 ----------
  { g: 3, skill: 'science-concept', dom: 'living-things', top: 'skeleton', d: 4,
    q: 'What does our skeleton do?', c: [
      'It helps us breathe',
      'It holds our body up and protects organs',
      'It makes our blood',
      'It digests our food',
    ], a: 1,
    ex: 'Bộ xương đỡ cơ thể đứng vững và bảo vệ nội tạng (ví dụ xương sườn bảo vệ tim, phổi).',
    lo: 'Biết chức năng của bộ xương.' },
  { g: 3, skill: 'science-reasoning', dom: 'living-things', top: 'nutrition', d: 4,
    q: 'Which food group gives us the most ENERGY for running and playing?', c: [
      'sweets and cakes',
      'rice, bread and potatoes',
      'candy and chocolate',
      'butter and oil',
    ], a: 1,
    ex: 'Tinh bột (rice, bread, potatoes) là nguồn năng lượng chính. Kẹo bánh cũng cho năng lượng nhưng không tốt cho sức khỏe.',
    lo: 'Phân biệt nhóm thực phẩm theo dinh dưỡng.' },
  { g: 3, skill: 'science-concept', dom: 'earth', top: 'rocks', d: 4,
    q: 'Fossils are found inside rocks. What is a fossil?', c: [
      'A living animal',
      'The remains of a plant or animal from long ago',
      'A type of metal',
      'A kind of soil',
    ], a: 1,
    ex: 'Hóa thạch là phần còn lại/dấu vết của sinh vật sống từ rất lâu về trước, được giữ trong đá.',
    lo: 'Định nghĩa hóa thạch.' },
  { g: 3, skill: 'science-reasoning', dom: 'forces', top: 'forces', d: 4,
    q: 'You push a toy car and it rolls away. What made the car move?', c: ['gravity only', 'a push force', 'a magnet', 'light'], a: 1,
    ex: 'Xe chuyển động do LỰC ĐẨY (push) của tay. Trọng lực giữ xe trên mặt đất chứ không làm xe lăn đi.',
    lo: 'Nhận biết lực đẩy - kéo gây chuyển động.' },
  { g: 3, skill: 'science-concept', dom: 'forces', top: 'magnets', d: 4,
    q: 'Which object will a magnet pull?', c: ['a plastic ruler', 'a wooden pencil', 'an iron nail', 'a rubber eraser'], a: 2,
    ex: 'Nam châm chỉ hút kim loại sắt (iron). Nhựa, gỗ, cao su đều không bị hút.',
    lo: 'Biết vật liệu bị nam châm hút.' },
  { g: 3, skill: 'science-concept', dom: 'light', top: 'light', d: 4,
    q: 'A shadow is made when ___.', c: [
      'light goes through an object',
      'an object blocks the light',
      'the light is turned off',
      'the object is white',
    ], a: 1,
    ex: 'Bóng xuất hiện khi vật CHẮN ánh sáng. Vật trong suốt cho sáng xuyên qua thì không tạo bóng rõ.',
    lo: 'Giải thích sự hình thành bóng.' },
  { g: 3, skill: 'science-reasoning', dom: 'living-things', top: 'plants', d: 4,
    q: 'Two same plants are planted. One is put in sunlight, one in a dark cupboard. After one week, the plant in the dark is ___.', c: [
      'taller and healthier',
      'the same as the other',
      'weak and pale',
      'full of flowers',
    ], a: 2,
    ex: 'Cây thiếu sáng không quang hợp được nên yếu, nhợt nhạt (pale). Đây là thí nghiệm kinh điển về ánh sáng.',
    lo: 'Dự đoán kết quả thí nghiệm cây thiếu ánh sáng.' },
  { g: 3, skill: 'science-concept', dom: 'earth', top: 'soil', d: 4,
    q: 'Why is soil important for plants?', c: [
      'It makes the garden look nice',
      'It holds water and nutrients for the roots',
      'It keeps the air clean',
      'It stops the wind',
    ], a: 1,
    ex: 'Đất giữ nước và chất dinh dưỡng (nutrients) để rễ hút nuôi cây.',
    lo: 'Hiểu vai trò của đất với thực vật.' },
  { g: 3, skill: 'science-reasoning', dom: 'living-things', top: 'animals', d: 4,
    q: 'A snake has no legs but it is NOT a worm because a snake ___.', c: [
      'has bones inside its body',
      'is green',
      'is long',
      'can move fast',
    ], a: 0,
    ex: 'Rắn có xương sống (động vật có xương) - giun không có xương. Màu sắc và hình dáng không phân loại được.',
    lo: 'Phân loại động vật có xương - không xương.' },
  { g: 3, skill: 'scientific-observation', dom: 'light', top: 'light', d: 5,
    q: 'Your shadow is longest ___.', c: [
      'at noon when the sun is high',
      'in the early morning when the sun is low',
      'at midnight',
      'when it rains',
    ], a: 1,
    ex: 'Mặt trời thấp (sáng sớm/chiều muộn) → bóng kéo dài. Giữa trưa mặt trời cao → bóng ngắn nhất.',
    lo: 'Liên hệ vị trí mặt trời với độ dài bóng.' },
  { g: 3, skill: 'science-reasoning', dom: 'forces', top: 'friction', d: 5,
    q: 'It is easier to ride a bike on a road than on grass because grass has more ___.', c: ['light', 'air', 'friction', 'water'], a: 2,
    ex: 'Cỏ tạo MA SÁT (friction) lớn hơn mặt đường nên đạp xe nặng hơn. Ma sát là lực cản chuyển động.',
    lo: 'Hiểu ma sát qua ví dụ thực tế.' },
];
