/**
 * CR-59 - authored ADVANCED (difficulty 4-5) math-in-English items.
 * Hand-written: multi-step reasoning, word problems, near-miss
 * distractors. Each item: g(grade), skill, dom(domain), top(topic_key),
 * d(difficulty), q(prompt), c(choices 4), a(correct index),
 * ex(explanation_vi), lo(learning_objective).
 * For true-false items: {tf:true, passage, statement, bool}.
 * For text-answer: {ta:true, accept:[...]}.
 */
export const ITEMS = [
  // ---------- GRADE 1 ----------
  { g: 1, skill: 'number-sense', dom: 'number', top: 'number-sense', d: 4,
    q: 'Which number is one more than nineteen?', c: ['eighteen', 'twenty', 'ninety', 'nine'], a: 1,
    ex: "Nineteen (19) cộng thêm 1 là twenty (20). 'Ninety' là 90 - nhìn giống nhưng khác hẳn.",
    lo: 'Nhận biết số liền sau trong phạm vi 20 bằng tiếng Anh.' },
  { g: 1, skill: 'number-sense', dom: 'number', top: 'number-sense', d: 4,
    q: 'Count by twos: 2, 4, 6, ___. What comes next?', c: ['7', '8', '10', '12'], a: 1,
    ex: 'Đếm cách 2: 2, 4, 6 rồi đến 8. Nhiễu 10 và 12 cũng là số chẵn nhưng không liền sau 6 trong dãy này.',
    lo: 'Đếm nhảy cách 2 trong phạm vi 10.' },
  { g: 1, skill: 'number-operations', dom: 'number', top: 'addition', d: 4,
    q: 'Mai has 4 pencils. Nam gives her 3 more. How many pencils does Mai have now?', c: ['1', '6', '7', '8'], a: 2,
    ex: '4 + 3 = 7. Đề hỏi tổng sau khi được thêm, không phải 4 - 3 = 1.',
    lo: 'Giải bài toán cộng có lời văn đơn giản.' },
  { g: 1, skill: 'number-operations', dom: 'number', top: 'subtraction', d: 4,
    q: 'There are 9 birds in the tree. 2 birds fly away. How many birds are left?', c: ['7', '8', '9', '11'], a: 0,
    ex: '9 - 2 = 7 con chim còn lại. Nhiễu 11 là kết quả của phép cộng 9 + 2 - sai phép tính.',
    lo: 'Giải bài toán trừ có lời văn.' },
  { g: 1, skill: 'mathematical-reasoning', dom: 'problem-solving', top: 'reasoning', d: 4,
    q: 'Which number makes this true? 5 + ___ = 8', c: ['2', '3', '4', '13'], a: 1,
    ex: '5 + 3 = 8 nên số cần điền là 3. Nhiễu 13 là 5 + 8 - đọc nhầm đề.',
    lo: 'Tìm số hạng còn thiếu trong phép cộng.' },
  { g: 1, skill: 'mathematical-reasoning', dom: 'problem-solving', top: 'reasoning', d: 4,
    q: 'Which number makes this true? ___ - 2 = 6', c: ['4', '8', '6', '10'], a: 1,
    ex: '8 - 2 = 6 nên số cần điền là 8. Nhiễu 4 là 6 - 2 - đặt sai vị trí.',
    lo: 'Tìm số bị trừ còn thiếu trong phép trừ.' },
  { g: 1, skill: 'number-sense', dom: 'number', top: 'comparison', d: 4,
    q: 'Which is the BIGGEST number?', c: ['seventeen', 'seven', 'seventy', 'ten'], a: 2,
    ex: "Seventy = 70, lớn hơn seventeen (17), ten (10) và seven (7). 'Seventy' và 'seventeen' dễ nhầm vì đọc gần giống.",
    lo: 'So sánh các số trong phạm vi 100 bằng tên tiếng Anh.' },
  { g: 1, skill: 'number-sense', dom: 'number', top: 'comparison', d: 4,
    q: 'Which is the SMALLEST number?', c: ['twelve', 'twenty', 'two', 'ten'], a: 2,
    ex: "Two = 2, nhỏ nhất trong 4 số. 'Twelve' (12) và 'twenty' (20) là nhiễu hay nhầm.",
    lo: 'So sánh các số bằng tên tiếng Anh.' },
  { g: 1, skill: 'geometry', dom: 'geometry', top: 'shapes', d: 4,
    q: 'A triangle has 3 sides. How many sides do TWO triangles have together?', c: ['5', '6', '7', '9'], a: 1,
    ex: 'Mỗi tam giác có 3 cạnh, 2 tam giác có 3 + 3 = 6 cạnh. Câu hỏi 2 bước: hiểu hình rồi tính.',
    lo: 'Vận dụng đặc điểm hình học vào phép tính.' },
  { g: 1, skill: 'mathematical-reasoning', dom: 'problem-solving', top: 'patterns', d: 4,
    q: 'Look at the pattern: circle, square, circle, square, circle, ___. What comes next?', c: ['circle', 'square', 'triangle', 'star'], a: 1,
    ex: 'Mẫu lặp circle-square: sau circle là square. Tam giác và sao không nằm trong mẫu.',
    lo: 'Nhận diện và tiếp tục mẫu hình AB.' },
  { g: 1, skill: 'mathematical-reasoning', dom: 'problem-solving', top: 'patterns', d: 4,
    q: 'Look at the numbers: 10, 9, 8, 7, ___. What comes next?', c: ['5', '6', '8', '11'], a: 1,
    ex: 'Dãy đếm lùi 1: sau 7 là 6. Nhiễu 5 bỏ qua 6; 8 là đếm xuôi.',
    lo: 'Nhận diện dãy số đếm lùi.' },
  { g: 1, skill: 'problem-solving', dom: 'problem-solving', top: 'word-problems', d: 4,
    q: 'Lan has 6 balloons. She gives 2 to Hoa and 1 to Minh. How many balloons does Lan have left?', c: ['3', '4', '5', '9'], a: 0,
    ex: 'Cho đi tổng cộng 2 + 1 = 3 bóng, còn 6 - 3 = 3. Bài toán 2 bước.',
    lo: 'Giải bài toán trừ hai bước.' },
  { g: 1, skill: 'measurement', dom: 'measurement', top: 'length', d: 4,
    q: 'A pencil is longer than an eraser. A ruler is longer than a pencil. Which is the LONGEST?', c: ['eraser', 'pencil', 'ruler', 'They are the same'], a: 2,
    ex: 'Ruler > pencil > eraser nên thước (ruler) dài nhất. Đọc kỹ chuỗi so sánh.',
    lo: 'Suy luận thứ tự độ dài từ so sánh gián tiếp.' },
  { g: 1, skill: 'data', dom: 'data', top: 'sorting', d: 4,
    q: 'There are 3 cats, 5 dogs and 1 bird. How many pets are there in all?', c: ['8', '9', '10', '4'], a: 1,
    ex: '3 + 5 + 1 = 9 con thú cưng. Đề hỏi TỔNG cả 3 nhóm, không chỉ 2 nhóm.',
    lo: 'Tổng hợp dữ liệu nhiều nhóm đơn giản.' },
  { g: 1, skill: 'number-operations', dom: 'number', top: 'addition', d: 5,
    q: 'What is 7 + 3 + 5?', c: ['10', '12', '15', '18'], a: 2,
    ex: '7 + 3 = 10, rồi 10 + 5 = 15. Cộng 3 số cần làm từng bước.',
    lo: 'Cộng ba số có tổng hai chữ số.' },
  { g: 1, skill: 'number-sense', dom: 'number', top: 'place-value', d: 5,
    q: 'The number 14 has 1 ten and how many ones?', c: ['1', '4', '10', '14'], a: 1,
    ex: '14 = 1 chục + 4 đơn vị. Số 4 ở hàng đơn vị.',
    lo: 'Nhận biết giá trị hàng chục và hàng đơn vị.' },

  // ---------- GRADE 2 ----------
  { g: 2, skill: 'number-operations', dom: 'number', top: 'addition', d: 4,
    q: 'What is 38 + 25?', c: ['53', '63', '73', '513'], a: 1,
    ex: '38 + 25 = 63 (8+5=13 viết 3 nhớ 1; 3+2+1=6). Nhiễu 53 quên nhớ hàng chục.',
    lo: 'Cộng hai số có nhớ trong phạm vi 100.' },
  { g: 2, skill: 'number-operations', dom: 'number', top: 'subtraction', d: 4,
    q: 'What is 52 - 28?', c: ['24', '26', '34', '36'], a: 0,
    ex: '52 - 28 = 24 (mượn 1 chục: 12-8=4, 4-2=2). Nhiễu 36 là lỗi mượn sai.',
    lo: 'Trừ có nhớ trong phạm vi 100.' },
  { g: 2, skill: 'problem-solving', dom: 'problem-solving', top: 'word-problems', d: 4,
    q: 'A book costs 35,000 dong. Binh pays 50,000 dong. How much change does he get back?', c: ['15,000', '20,000', '25,000', '85,000'], a: 0,
    ex: '50,000 - 35,000 = 15,000 đồng tiền thối. Nhiễu 85,000 là phép cộng - đề hỏi tiền thừa.',
    lo: 'Giải bài toán tiền tệ có lời văn.' },
  { g: 2, skill: 'mathematical-reasoning', dom: 'problem-solving', top: 'reasoning', d: 4,
    q: 'Which number makes this true? 45 + ___ = 70', c: ['15', '25', '35', '115'], a: 1,
    ex: '45 + 25 = 70 nên số cần điền là 25. Kiểm tra: 70 - 45 = 25.',
    lo: 'Tìm số hạng còn thiếu trong phạm vi 100.' },
  { g: 2, skill: 'number-sense', dom: 'number', top: 'place-value', d: 4,
    q: 'In the number 63, the digit 6 stands for...', c: ['6 ones', '6 tens', '6 hundreds', '60 ones'], a: 1,
    ex: 'Chữ số 6 ở hàng chục = 6 tens = 60. Nhiễu "6 ones" nhầm hàng.',
    lo: 'Xác định giá trị chữ số theo hàng.' },
  { g: 2, skill: 'mathematical-reasoning', dom: 'problem-solving', top: 'patterns', d: 4,
    q: 'Look at the pattern: 5, 10, 15, 20, ___. What comes next?', c: ['21', '24', '25', '30'], a: 2,
    ex: 'Đếm nhảy 5: sau 20 là 25. Nhiễu 30 là bước tiếp theo sau 25 - đọc nhầm vị trí.',
    lo: 'Đếm nhảy cách 5 trong phạm vi 30.' },
  { g: 2, skill: 'mathematical-reasoning', dom: 'problem-solving', top: 'patterns', d: 4,
    q: 'Look at the pattern: 2, 4, 8, 16, ___. What comes next?', c: ['18', '20', '24', '32'], a: 3,
    ex: 'Mỗi số gấp đôi số trước: 16 x 2 = 32. Nhiễu 18-24 là cộng thêm - sai quy luật.',
    lo: 'Nhận diện dãy số nhân đôi.' },
  { g: 2, skill: 'problem-solving', dom: 'problem-solving', top: 'word-problems', d: 4,
    q: 'There are 4 rows of chairs. Each row has 6 chairs. How many chairs are there in all?', c: ['10', '20', '24', '46'], a: 2,
    ex: '4 x 6 = 24 ghế (hoặc 6+6+6+6=24). Nhiễu 10 là 4+6 - dùng sai phép tính.',
    lo: 'Giải bài toán nhân đơn giản bằng tổng lặp.' },
  { g: 2, skill: 'geometry', dom: 'geometry', top: 'shapes', d: 4,
    q: 'Which shape has 4 equal sides and 4 corners?', c: ['triangle', 'rectangle', 'square', 'circle'], a: 2,
    ex: 'Hình vuông (square) có 4 cạnh BẰNG NHAU. Rectangle có 4 cạnh nhưng không bằng nhau - đây là nhiễu chính.',
    lo: 'Phân biệt hình vuông và hình chữ nhật.' },
  { g: 2, skill: 'measurement', dom: 'measurement', top: 'time', d: 4,
    q: 'School starts at 7:00. It ends at 11:00. How many hours is the school day?', c: ['3', '4', '5', '11'], a: 1,
    ex: 'Từ 7 giờ đến 11 giờ là 4 giờ (11 - 7 = 4). Đếm khoảng, không phải lấy số cuối.',
    lo: 'Tính khoảng thời gian theo giờ.' },
  { g: 2, skill: 'problem-solving', dom: 'problem-solving', top: 'word-problems', d: 4,
    q: 'An reads 12 pages on Monday and 15 pages on Tuesday. How many pages does she read in two days?', c: ['3', '17', '27', '30'], a: 2,
    ex: '12 + 15 = 27 trang. Nhiễu 3 là 15-12 - đề hỏi tổng hai ngày.',
    lo: 'Cộng hai số có lời văn trong phạm vi 100.' },
  { g: 2, skill: 'number-sense', dom: 'number', top: 'comparison', d: 4,
    q: 'Which number is between 45 and 52?', c: ['44', '48', '53', '60'], a: 1,
    ex: 'Chỉ có 48 nằm giữa 45 và 52. 44 nhỏ hơn 45; 53 và 60 lớn hơn 52.',
    lo: 'Xác định số nằm giữa hai số cho trước.' },
  { g: 2, skill: 'number-operations', dom: 'number', top: 'mixed', d: 5,
    q: 'What is 100 - 45 - 20?', c: ['25', '35', '45', '55'], a: 1,
    ex: '100 - 45 = 55, rồi 55 - 20 = 35. Phép trừ liên tiếp làm từ trái sang phải.',
    lo: 'Trừ liên tiếp trong phạm vi 100.' },
  { g: 2, skill: 'mathematical-reasoning', dom: 'problem-solving', top: 'reasoning', d: 5,
    q: 'I am a number. I am greater than 40 and less than 50. I am an even number. My two digits are the same. What number am I?', c: ['44', '45', '46', '55'], a: 0,
    ex: '44: giữa 40-50, chẵn, hai chữ số giống nhau. 45 lẻ; 46 chữ số khác nhau; 55 lớn hơn 50.',
    lo: 'Suy luận số từ nhiều điều kiện kết hợp.' },

  // ---------- GRADE 3 ----------
  { g: 3, skill: 'number-operations', dom: 'number', top: 'multiplication', d: 4,
    q: 'What is 7 x 8?', c: ['54', '56', '63', '64'], a: 1,
    ex: '7 x 8 = 56. Nhiễu 54 là 6x9; 63 là 7x9; 64 là 8x8 - bẫy bảng nhân lân cận.',
    lo: 'Thuộc bảng nhân 7 và 8.' },
  { g: 3, skill: 'number-operations', dom: 'number', top: 'division', d: 4,
    q: 'What is 56 ÷ 8?', c: ['6', '7', '8', '9'], a: 1,
    ex: '56 ÷ 8 = 7 vì 7 x 8 = 56. Chia là phép ngược của nhân.',
    lo: 'Chia trong phạm vi bảng nhân 8.' },
  { g: 3, skill: 'problem-solving', dom: 'problem-solving', top: 'word-problems', d: 4,
    q: 'A pack has 8 crayons. Teacher buys 6 packs for the class. How many crayons are there in all?', c: ['14', '42', '48', '68'], a: 2,
    ex: '8 x 6 = 48 bút màu. Nhiễu 14 là 8+6; 68 ghép hai số - đều sai.',
    lo: 'Nhân có lời văn một bước.' },
  { g: 3, skill: 'problem-solving', dom: 'problem-solving', top: 'word-problems', d: 4,
    q: 'Huy has 45 stickers. He puts them equally into 5 albums. How many stickers are in each album?', c: ['8', '9', '40', '50'], a: 1,
    ex: '45 ÷ 5 = 9 sticker mỗi album. Chia đều = phép chia.',
    lo: 'Chia đều có lời văn.' },
  { g: 3, skill: 'fractions', dom: 'number', top: 'fractions', d: 4,
    q: 'A pizza is cut into 8 equal slices. Tuan eats 3 slices. What fraction of the pizza does he eat?', c: ['3/5', '3/8', '5/8', '8/3'], a: 1,
    ex: 'Ăn 3 trong 8 phần bằng nhau = 3/8. Nhiễu 5/8 là phần còn lại - đọc kỹ đề hỏi phần ĐÃ ăn.',
    lo: 'Đọc phân số từ tình huống chia phần bằng nhau.' },
  { g: 3, skill: 'mathematical-reasoning', dom: 'problem-solving', top: 'patterns', d: 4,
    q: 'Look at the pattern: 3, 6, 11, 18, 27, ___. What comes next?', c: ['36', '37', '38', '39'], a: 2,
    ex: 'Khoảng cách tăng dần: +3, +5, +7, +9 nên tiếp là +11: 27 + 11 = 38.',
    lo: 'Nhận diện dãy số có khoảng cách tăng dần.' },
  { g: 3, skill: 'measurement', dom: 'measurement', top: 'time', d: 4,
    q: 'A film starts at 2:30 and lasts 90 minutes. What time does it end?', c: ['3:30', '4:00', '4:30', '5:00'], a: 1,
    ex: '90 phút = 1 giờ 30 phút. 2:30 + 1:30 = 4:00. Nhiễu 4:30 cộng nhầm 2 giờ.',
    lo: 'Cộng thời gian vượt qua giờ chẵn.' },
  { g: 3, skill: 'number-sense', dom: 'number', top: 'place-value', d: 4,
    q: 'What is the value of digit 7 in the number 472?', c: ['7', '70', '700', '7000'], a: 1,
    ex: 'Chữ số 7 ở hàng chục = 70. 472 = 400 + 70 + 2.',
    lo: 'Giá trị chữ số theo hàng trong số có 3 chữ số.' },
  { g: 3, skill: 'problem-solving', dom: 'problem-solving', top: 'word-problems', d: 4,
    q: 'A farmer has 36 eggs. He sells 15 in the morning and 12 in the afternoon. How many eggs are left?', c: ['9', '21', '24', '63'], a: 0,
    ex: 'Bán tổng 15 + 12 = 27 quả; còn 36 - 27 = 9. Bài toán 2 bước: cộng rồi trừ.',
    lo: 'Giải bài toán hai bước cộng-trừ.' },
  { g: 3, skill: 'mathematical-reasoning', dom: 'problem-solving', top: 'reasoning', d: 4,
    q: 'Which number makes this true? 8 x ___ = 96', c: ['10', '11', '12', '14'], a: 2,
    ex: '96 ÷ 8 = 12 nên số cần điền là 12. Kiểm tra: 8 x 12 = 96.',
    lo: 'Tìm thừa số còn thiếu bằng phép chia.' },
  { g: 3, skill: 'geometry', dom: 'geometry', top: 'shapes', d: 4,
    q: 'How many corners (vertices) does a cube have?', c: ['4', '6', '8', '12'], a: 2,
    ex: 'Khối lập phương có 8 đỉnh (4 đỉnh mặt trên + 4 đỉnh mặt dưới). Nhiễu 6 là số mặt; 12 là số cạnh.',
    lo: 'Đếm đỉnh của khối lập phương.' },
  { g: 3, skill: 'data', dom: 'data', top: 'graphs', d: 4,
    q: 'A picture graph shows: Monday = 4 apples, Tuesday = 6 apples, Wednesday = 2 apples. On which day were the FEWEST apples sold?', c: ['Monday', 'Tuesday', 'Wednesday', 'All equal'], a: 2,
    ex: 'Wednesday chỉ 2 quả - ít nhất. Đề hỏi ÍT nhất, không phải nhiều nhất (Tuesday).',
    lo: 'Đọc và so sánh dữ liệu từ biểu đồ tranh.' },
  { g: 3, skill: 'problem-solving', dom: 'problem-solving', top: 'word-problems', d: 5,
    q: 'Each box holds 9 cakes. There are 52 cakes. How many boxes are needed to pack ALL the cakes?', c: ['5', '6', '7', '8'], a: 1,
    ex: '52 ÷ 9 = 5 dư 7. Còn dư 7 cái vẫn cần 1 hộp nữa: 5 + 1 = 6 hộp. Bẫy kinh điển của chia có dư.',
    lo: 'Chia có dư và làm tròn lên theo ngữ cảnh.' },
  { g: 3, skill: 'number-operations', dom: 'number', top: 'mixed', d: 5,
    q: 'What is 6 x 7 + 8?', c: ['42', '50', '56', '90'], a: 1,
    ex: 'Nhân trước cộng sau: 6 x 7 = 42, rồi 42 + 8 = 50.',
    lo: 'Thứ tự phép tính nhân trước cộng sau.' },

  // ---------- GRADE 4 ----------
  { g: 4, skill: 'number-operations', dom: 'number', top: 'multiplication', d: 4,
    q: 'What is 25 x 14?', c: ['300', '325', '350', '375'], a: 2,
    ex: 'Tách để nhân nhanh: 25 x 14 = 25 x 10 + 25 x 4 = 250 + 100 = 350.',
    lo: 'Nhân số hai chữ số bằng tách số.' },
  { g: 4, skill: 'problem-solving', dom: 'problem-solving', top: 'word-problems', d: 4,
    q: 'A stadium has 18 rows of seats. Each row has 24 seats. How many seats are there in all?', c: ['42', '342', '432', '480'], a: 2,
    ex: '18 x 24 = 18 x 20 + 18 x 4 = 360 + 72 = 432 ghế.',
    lo: 'Nhân hai chữ số có lời văn.' },
  { g: 4, skill: 'fractions', dom: 'number', top: 'fractions', d: 4,
    q: 'Which fraction is the BIGGEST?', c: ['1/2', '1/3', '1/4', '1/8'], a: 0,
    ex: 'Cùng tử số 1: mẫu càng nhỏ phân số càng LỚN. 1/2 lớn nhất - bẫy kinh điển là nghĩ 1/8 lớn vì 8 lớn.',
    lo: 'So sánh phân số cùng tử số.' },
  { g: 4, skill: 'fractions', dom: 'number', top: 'fractions', d: 4,
    q: 'What is 3/4 of 20?', c: ['12', '15', '16', '80'], a: 1,
    ex: '3/4 của 20 = 20 ÷ 4 x 3 = 5 x 3 = 15. Chia mẫu trước, nhân tử sau.',
    lo: 'Tính phân số của một số.' },
  { g: 4, skill: 'problem-solving', dom: 'problem-solving', top: 'word-problems', d: 4,
    q: 'A train travels 90 km every hour. How far does it travel in 3 hours and 30 minutes?', c: ['270 km', '300 km', '315 km', '360 km'], a: 2,
    ex: '3 giờ: 90 x 3 = 270 km. Nửa giờ: 90 ÷ 2 = 45 km. Tổng 270 + 45 = 315 km.',
    lo: 'Tính quãng đường với thời gian lẻ nửa giờ.' },
  { g: 4, skill: 'mathematical-reasoning', dom: 'problem-solving', top: 'reasoning', d: 4,
    q: 'The sum of two numbers is 50. Their difference is 10. What is the bigger number?', c: ['20', '25', '30', '40'], a: 2,
    ex: 'Hai số là 30 và 20: 30+20=50, 30-20=10. Số lớn là 30. Thử từng đáp án là cách nhanh nhất.',
    lo: 'Bài toán tổng-hiệu kinh điển.' },
  { g: 4, skill: 'measurement', dom: 'measurement', top: 'perimeter', d: 4,
    q: 'A rectangle is 12 cm long and 5 cm wide. What is its perimeter?', c: ['17 cm', '34 cm', '60 cm', '120 cm'], a: 1,
    ex: 'Chu vi = (dài + rộng) x 2 = (12 + 5) x 2 = 34 cm. Nhiễu 60 là DIỆN TÍCH (12x5) - bẫy điển hình.',
    lo: 'Tính chu vi hình chữ nhật, phân biệt với diện tích.' },
  { g: 4, skill: 'measurement', dom: 'measurement', top: 'area', d: 4,
    q: 'A square has sides of 9 cm. What is its area?', c: ['18 cm²', '36 cm²', '81 cm²', '90 cm²'], a: 2,
    ex: 'Diện tích hình vuông = cạnh x cạnh = 9 x 9 = 81 cm². Nhiễu 36 là chu vi (9x4).',
    lo: 'Tính diện tích hình vuông.' },
  { g: 4, skill: 'number-sense', dom: 'number', top: 'rounding', d: 4,
    q: 'Round 4,567 to the nearest hundred.', c: ['4,500', '4,600', '4,570', '5,000'], a: 1,
    ex: 'Làm tròn đến trăm: nhìn hàng chục là 6 ≥ 5 nên lên 4,600. Nhiễu 4,570 là làm tròn đến chục.',
    lo: 'Làm tròn số đến hàng trăm.' },
  { g: 4, skill: 'data', dom: 'data', top: 'averages', d: 5,
    q: 'Minh scores 8, 9 and 10 in three quizzes. What is his average score?', c: ['8', '9', '10', '27'], a: 1,
    ex: 'Trung bình = (8 + 9 + 10) ÷ 3 = 27 ÷ 3 = 9. Nhiễu 27 là tổng, quên chia.',
    lo: 'Tính trung bình cộng đơn giản.' },
];
