/** CR-59 - authored ADVANCED science-in-English items (difficulty 4-5). */
export const ITEMS = [
  // ---------- GRADE 1 ----------
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'animals', d: 4,
    q: 'Which animal can FLY?', c: ['dog', 'fish', 'bird', 'cat'], a: 2,
    ex: 'Bird (chim) biết bay. Dog và cat đi trên đất, fish bơi dưới nước.',
    lo: 'Phân biệt đặc điểm di chuyển của động vật.' },
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'animals', d: 4,
    q: 'Which animal lives in the water?', c: ['elephant', 'fish', 'monkey', 'chicken'], a: 1,
    ex: 'Fish (cá) sống dưới nước. Elephant, monkey và chicken sống trên cạn.',
    lo: 'Nhận biết môi trường sống của động vật.' },
  { g: 1, skill: 'scientific-observation', dom: 'living-things', top: 'body', d: 4,
    q: 'We use our eyes to ___ and our ears to ___.', c: ['hear - see', 'see - hear', 'smell - see', 'see - taste'], a: 1,
    ex: 'Mắt (eyes) để nhìn - see; tai (ears) để nghe - hear. Ghép đúng giác quan với cơ quan.',
    lo: 'Ghép giác quan với chức năng đúng.' },
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'plants', d: 4,
    q: 'Which part of the plant is UNDER the ground?', c: ['leaf', 'flower', 'root', 'fruit'], a: 2,
    ex: 'Rễ (root) nằm dưới đất, hút nước cho cây. Lá, hoa, quả đều ở trên mặt đất.',
    lo: 'Nhận biết các bộ phận của cây.' },
  { g: 1, skill: 'scientific-observation', dom: 'materials', top: 'objects', d: 4,
    q: 'Which one is soft?', c: ['a rock', 'a pillow', 'a door', 'a spoon'], a: 1,
    ex: 'Pillow (gối) mềm. Đá, cửa và thìa đều cứng.',
    lo: 'Phân biệt vật liệu mềm - cứng.' },
  { g: 1, skill: 'science-concept', dom: 'earth', top: 'weather', d: 4,
    q: 'What do we wear when it Rains?', c: ['sunglasses', 'a raincoat', 'shorts', 'a hat for the sun'], a: 1,
    ex: 'Raincoat (áo mưa) mặc khi trời mưa. Kính râm và mũ nắng dùng khi trời nắng.',
    lo: 'Liên hệ thời tiết với trang phục phù hợp.' },
  { g: 1, skill: 'science-reasoning', dom: 'living-things', top: 'animals', d: 4,
    q: 'A duck has two legs and feathers. Which animal is most like a duck?', c: ['dog', 'chicken', 'fish', 'snake'], a: 1,
    ex: 'Chicken (gà) cũng có 2 chân và lông vũ - cùng nhóm chim với vịt. Các con khác không có lông.',
    lo: 'Phân loại động vật theo đặc điểm chung.' },
  { g: 1, skill: 'science-concept', dom: 'earth', top: 'day-night', d: 4,
    q: 'What do we see in the sky at NIGHT?', c: ['the sun', 'the moon', 'a rainbow', 'clouds only'], a: 1,
    ex: 'Ban đêm nhìn thấy mặt trăng (moon). Mặt trời chỉ thấy ban ngày.',
    lo: 'Phân biệt hiện tượng ngày - đêm.' },
  { g: 1, skill: 'science-reasoning', dom: 'living-things', top: 'needs', d: 4,
    q: 'A plant needs water, sunlight and ___ to grow.', c: ['candy', 'toys', 'air', 'milk'], a: 2,
    ex: 'Cây cần nước, ánh sáng và KHÔNG KHÍ (air) để sống. Kẹo, đồ chơi, sữa không giúp cây lớn.',
    lo: 'Biết điều kiện sống cơ bản của thực vật.' },
  { g: 1, skill: 'scientific-observation', dom: 'materials', top: 'objects', d: 4,
    q: 'Which object can float on water?', c: ['a coin', 'a wooden block', 'a key', 'a stone'], a: 1,
    ex: 'Gỗ (wooden block) nổi trên nước. Xu, chìa khóa và đá đều chìm vì nặng hơn nước.',
    lo: 'Dự đoán vật nổi - chìm theo vật liệu.' },
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'animals', d: 5,
    q: 'A baby cat is a kitten. A baby dog is a ___.', c: ['calf', 'puppy', 'chick', 'cub'], a: 1,
    ex: 'Con chó con là puppy. Calf là bò con, chick là gà con, cub là thú con như sư tử con.',
    lo: 'Biết tên con non của động vật quen thuộc.' },
  { g: 1, skill: 'science-reasoning', dom: 'living-things', top: 'food', d: 5,
    q: 'A rabbit eats carrots and grass. A lion eats meat. Which is TRUE?', c: [
      'The lion is a plant-eater',
      'The rabbit is a meat-eater',
      'The rabbit eats plants',
      'The lion eats grass',
    ], a: 2,
    ex: 'Thỏ ăn cà rốt và cỏ - tức ăn thực vật (plant-eater). Sư tử ăn thịt. Đọc kỹ từng đáp án.',
    lo: 'Phân biệt động vật ăn thực vật và ăn thịt.' },

  // ---------- GRADE 2 ----------
  { g: 2, skill: 'science-concept', dom: 'living-things', top: 'habitats', d: 4,
    q: 'A polar bear lives in a very cold place. Where does it live?', c: ['the desert', 'the Arctic', 'the jungle', 'the ocean'], a: 1,
    ex: 'Gấu Bắc Cực sống ở Arctic - vùng băng giá lạnh. Sa mạc nóng, rừng nhiệt đới ẩm nóng.',
    lo: 'Ghép động vật với môi trường sống phù hợp.' },
  { g: 2, skill: 'science-reasoning', dom: 'living-things', top: 'habitats', d: 4,
    q: 'A camel can live many days without water. Where does it live?', c: ['the sea', 'the forest', 'the desert', 'the mountain'], a: 2,
    ex: 'Lạc đà chịu khát rất lâu - thích nghi với sa mạc (desert) khô nóng.',
    lo: 'Suy luận môi trường sống từ đặc điểm thích nghi.' },
  { g: 2, skill: 'science-concept', dom: 'living-things', top: 'life-cycles', d: 4,
    q: 'What does a caterpillar become?', c: ['a bee', 'a butterfly', 'a bird', 'a spider'], a: 1,
    ex: 'Sâu bướm (caterpillar) biến thành bướm (butterfly) qua kén - chu kỳ sống của bướm.',
    lo: 'Biết chu kỳ biến thái của bướm.' },
  { g: 2, skill: 'science-concept', dom: 'earth', top: 'seasons', d: 4,
    q: 'Leaves fall from the trees and the weather gets cooler. Which season is it?', c: ['spring', 'summer', 'autumn', 'winter'], a: 2,
    ex: 'Lá rụng + trời mát dần = mùa thu (autumn). Mùa đông lạnh hơn nữa và nhiều cây đã trụi lá.',
    lo: 'Nhận diện đặc điểm các mùa.' },
  { g: 2, skill: 'science-reasoning', dom: 'materials', top: 'materials', d: 4,
    q: 'A raincoat is made of plastic because plastic is ___.', c: ['soft', 'waterproof', 'heavy', 'warm'], a: 1,
    ex: 'Áo mưa cần chống nước (waterproof) - nhựa không thấm nước. Mềm hay ấm không phải lý do chính.',
    lo: 'Liên hệ tính chất vật liệu với công dụng.' },
  { g: 2, skill: 'science-reasoning', dom: 'materials', top: 'materials', d: 4,
    q: 'Which material is best for a window?', c: ['wood', 'paper', 'glass', 'cloth'], a: 2,
    ex: 'Cửa sổ cần TRONG SUỐT để lấy sáng - chỉ có kính (glass) trong. Gỗ, giấy, vải không xuyên ánh sáng.',
    lo: 'Chọn vật liệu theo tính chất trong suốt.' },
  { g: 2, skill: 'scientific-observation', dom: 'living-things', top: 'senses', d: 4,
    q: 'Honey is sweet. Lemons are sour. We know this using our sense of ___.', c: ['sight', 'hearing', 'taste', 'smell'], a: 2,
    ex: 'Vị ngọt và chua nhận biết bằng vị giác (taste). Khứu giác ngửi mùi, không phân biệt được vị.',
    lo: 'Ghép hiện tượng với giác quan đúng.' },
  { g: 2, skill: 'science-concept', dom: 'earth', top: 'water', d: 4,
    q: 'Rain falls down to Earth from ___.', c: ['the sea only', 'clouds', 'the moon', 'rivers'], a: 1,
    ex: 'Mưa rơi từ mây (clouds) khi hơi nước ngưng tụ đủ nặng. Biển là nơi nước bốc hơi, không phải nơi mưa rơi xuống trực tiếp.',
    lo: 'Hiểu vòng tuần hoàn nước đơn giản.' },
  { g: 2, skill: 'science-reasoning', dom: 'living-things', top: 'animals', d: 4,
    q: 'Fish breathe with gills. Whales live in the sea but breathe with lungs. What must a whale do?', c: [
      'Stay underwater forever',
      'Come up to the surface to breathe air',
      'Grow gills like a fish',
      'Stop breathing',
    ], a: 1,
    ex: 'Cá voi thở bằng PHỔI (lungs) nên phải nổi lên mặt nước hít không khí - dù sống dưới nước.',
    lo: 'Suy luận hành vi từ đặc điểm sinh học.' },
  { g: 2, skill: 'science-concept', dom: 'living-things', top: 'plants', d: 4,
    q: 'Seeds need water and warmth to start growing. This is called ___.', c: ['germination', 'photosynthesis', 'hibernation', 'melting'], a: 0,
    ex: 'Hạt nảy mầm = germination. Photosynthesis là quang hợp, hibernation là ngủ đông - từ vựng nâng cao cần phân biệt.',
    lo: 'Dùng thuật ngữ nảy mầm đúng.' },
  { g: 2, skill: 'science-reasoning', dom: 'earth', top: 'weather', d: 5,
    q: 'The weather report says a storm is coming tomorrow. What should people do?', c: [
      'Go swimming at the beach',
      'Fly kites in the park',
      'Stay inside and close the windows',
      'Have a picnic outside',
    ], a: 2,
    ex: 'Bão đến cần ở trong nhà, đóng cửa sổ cho an toàn. Các hoạt động ngoài trời đều nguy hiểm khi có bão.',
    lo: 'Ra quyết định an toàn theo dự báo thời tiết.' },
  { g: 2, skill: 'scientific-observation', dom: 'living-things', top: 'groups', d: 5,
    q: 'Which one does NOT belong to the group?', c: ['a bee', 'an ant', 'a spider', 'a butterfly'], a: 2,
    ex: 'Ong, kiến, bướm đều là CÔN TRÙNG (6 chân). Nhện có 8 chân - không phải côn trùng.',
    lo: 'Phân loại côn trùng và động vật khác.' },

  // ---------- GRADE 3 ----------
  { g: 3, skill: 'science-concept', dom: 'living-things', top: 'skeleton', d: 4,
    q: 'What does our skeleton do?', c: [
      'It helps us breathe',
      'It holds our body up and protects organs',
      'It makes our blood',
      'It digests our food',
    ], a: 1,
    ex: 'Bộ xương đỡ cơ thể đứng vững và bảo vệ nội tạng (ví dụ xương sườn bảo vệ tim, phổi).',
    lo: 'Biết chức năng của bộ xương.' },
  { g: 3, skill: 'science-reasoning', dom: 'living-things', top: 'nutrition', d: 4,
    q: 'Which food group gives us the most ENERGY for running and playing?', c: [
      'sweets and cakes',
      'rice, bread and potatoes',
      'candy and chocolate',
      'butter and oil',
    ], a: 1,
    ex: 'Tinh bột (rice, bread, potatoes) là nguồn năng lượng chính. Kẹo bánh cũng cho năng lượng nhưng không tốt cho sức khỏe.',
    lo: 'Phân biệt nhóm thực phẩm theo dinh dưỡng.' },
  { g: 3, skill: 'science-concept', dom: 'earth', top: 'rocks', d: 4,
    q: 'Fossils are found inside rocks. What is a fossil?', c: [
      'A living animal',
      'The remains of a plant or animal from long ago',
      'A type of metal',
      'A kind of soil',
    ], a: 1,
    ex: 'Hóa thạch là phần còn lại/dấu vết của sinh vật sống từ rất lâu về trước, được giữ trong đá.',
    lo: 'Định nghĩa hóa thạch.' },
  { g: 3, skill: 'science-reasoning', dom: 'forces', top: 'forces', d: 4,
    q: 'You push a toy car and it rolls away. What made the car move?', c: ['gravity only', 'a push force', 'a magnet', 'light'], a: 1,
    ex: 'Xe chuyển động do LỰC ĐẨY (push) của tay. Trọng lực giữ xe trên mặt đất chứ không làm xe lăn đi.',
    lo: 'Nhận biết lực đẩy - kéo gây chuyển động.' },
  { g: 3, skill: 'science-concept', dom: 'forces', top: 'magnets', d: 4,
    q: 'Which object will a magnet pull?', c: ['a plastic ruler', 'a wooden pencil', 'an iron nail', 'a rubber eraser'], a: 2,
    ex: 'Nam châm chỉ hút kim loại sắt (iron). Nhựa, gỗ, cao su đều không bị hút.',
    lo: 'Biết vật liệu bị nam châm hút.' },
  { g: 3, skill: 'science-concept', dom: 'light', top: 'light', d: 4,
    q: 'A shadow is made when ___.', c: [
      'light goes through an object',
      'an object blocks the light',
      'the light is turned off',
      'the object is white',
    ], a: 1,
    ex: 'Bóng xuất hiện khi vật CHẮN ánh sáng. Vật trong suốt cho sáng xuyên qua thì không tạo bóng rõ.',
    lo: 'Giải thích sự hình thành bóng.' },
  { g: 3, skill: 'science-reasoning', dom: 'living-things', top: 'plants', d: 4,
    q: 'Two same plants are planted. One is put in sunlight, one in a dark cupboard. After one week, the plant in the dark is ___.', c: [
      'taller and healthier',
      'the same as the other',
      'weak and pale',
      'full of flowers',
    ], a: 2,
    ex: 'Cây thiếu sáng không quang hợp được nên yếu, nhợt nhạt (pale). Đây là thí nghiệm kinh điển về ánh sáng.',
    lo: 'Dự đoán kết quả thí nghiệm cây thiếu ánh sáng.' },
  { g: 3, skill: 'science-concept', dom: 'earth', top: 'soil', d: 4,
    q: 'Why is soil important for plants?', c: [
      'It makes the garden look nice',
      'It holds water and nutrients for the roots',
      'It keeps the air clean',
      'It stops the wind',
    ], a: 1,
    ex: 'Đất giữ nước và chất dinh dưỡng (nutrients) để rễ hút nuôi cây.',
    lo: 'Hiểu vai trò của đất với thực vật.' },
  { g: 3, skill: 'science-reasoning', dom: 'living-things', top: 'animals', d: 4,
    q: 'A snake has no legs but it is NOT a worm because a snake ___.', c: [
      'has bones inside its body',
      'is green',
      'is long',
      'can move fast',
    ], a: 0,
    ex: 'Rắn có xương sống (động vật có xương) - giun không có xương. Màu sắc và hình dáng không phân loại được.',
    lo: 'Phân loại động vật có xương - không xương.' },
  { g: 3, skill: 'scientific-observation', dom: 'light', top: 'light', d: 5,
    q: 'Your shadow is longest ___.', c: [
      'at noon when the sun is high',
      'in the early morning when the sun is low',
      'at midnight',
      'when it rains',
    ], a: 1,
    ex: 'Mặt trời thấp (sáng sớm/chiều muộn) → bóng kéo dài. Giữa trưa mặt trời cao → bóng ngắn nhất.',
    lo: 'Liên hệ vị trí mặt trời với độ dài bóng.' },
  { g: 3, skill: 'science-reasoning', dom: 'forces', top: 'friction', d: 5,
    q: 'It is easier to ride a bike on a road than on grass because grass has more ___.', c: ['light', 'air', 'friction', 'water'], a: 2,
    ex: 'Cỏ tạo MA SÁT (friction) lớn hơn mặt đường nên đạp xe nặng hơn. Ma sát là lực cản chuyển động.',
    lo: 'Hiểu ma sát qua ví dụ thực tế.' },

  // ---------- GRADE 1 - CR-66 bo sung ----------
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'animals', d: 4,
    q: 'Which animal gives us milk?', c: ['a cat', 'a cow', 'a fish', 'a bird'], a: 1,
    ex: 'Bò (cow) cho sữa. Mèo, cá, chim không cho sữa uống được.',
    lo: 'Ghép động vật với sản phẩm cho con người.' },
  { g: 1, skill: 'scientific-observation', dom: 'living-things', top: 'body', d: 4,
    q: 'We smell flowers with our ___.', c: ['ears', 'nose', 'tongue', 'hands'], a: 1,
    ex: 'Ngửi hoa bằng mũi (nose). Lưỡi để nếm, tai để nghe.',
    lo: 'Giác quan khứu giác với mũi.' },
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'plants', d: 4,
    q: 'Which part of the plant is usually GREEN and makes food?', c: ['root', 'flower', 'leaf', 'seed'], a: 2,
    ex: 'Lá (leaf) xanh và quang hợp làm thức ăn cho cây. Rễ hút nước, hoa để ra quả.',
    lo: 'Chức năng của lá cây.' },
  { g: 1, skill: 'science-reasoning', dom: 'materials', top: 'objects', d: 4,
    q: 'Which one can you BEND without breaking?', c: ['a glass cup', 'a rubber band', 'a wooden ruler', 'a stone'], a: 1,
    ex: 'Dây thun (rubber band) co giãn uốn được. Thủy tinh, gỗ, đá cứng - bẻ là vỡ.',
    lo: 'Phân biệt vật liệu dẻo và cứng.' },
  { g: 1, skill: 'science-concept', dom: 'earth', top: 'weather', d: 4,
    q: 'Which season is the HOTTEST?', c: ['winter', 'summer', 'autumn', 'spring'], a: 1,
    ex: 'Mùa hè (summer) nóng nhất trong năm. Đông lạnh, thu mát, xuân ấm.',
    lo: 'Nhận biết mùa nóng nhất.' },
  { g: 1, skill: 'science-reasoning', dom: 'living-things', top: 'animals', d: 4,
    q: 'A bird has wings and feathers. Which animal is in the SAME group?', c: ['a bat', 'a duck', 'a butterfly', 'a fish'], a: 1,
    ex: 'Vịt (duck) là chim - có cánh và lông vũ. Dơi là thú, bướm là côn trùng (không có lông vũ).',
    lo: 'Nhóm chim: cánh + lông vũ.' },
  { g: 1, skill: 'scientific-observation', dom: 'materials', top: 'objects', d: 4,
    q: 'A magnet pulls things made of ___.', c: ['plastic', 'paper', 'metal', 'wood'], a: 2,
    ex: 'Nam châm hút KIM LOẠI (metal). Nhựa, giấy, gỗ không bị hút.',
    lo: 'Vật liệu bị nam châm hút.' },
  { g: 1, skill: 'science-concept', dom: 'earth', top: 'water', d: 4,
    q: 'Where does rain come from?', c: ['the sea', 'clouds', 'the moon', 'rivers'], a: 1,
    ex: 'Mưa rơi từ MÂY (clouds) - nước biển bay hơi thành mây rồi mưa xuống.',
    lo: 'Nguồn gốc của mưa.' },
  { g: 1, skill: 'science-reasoning', dom: 'living-things', top: 'needs', d: 4,
    q: 'What do humans AND animals BOTH need to live?', c: ['toys', 'books', 'air and water', 'TV'], a: 2,
    ex: 'Người và động vật đều cần không khí và nước để sống. Đồ chơi, sách, TV không cần thiết.',
    lo: 'Nhu cầu sống chung của sinh vật.' },
  { g: 1, skill: 'science-concept', dom: 'earth', top: 'day-night', d: 4,
    q: 'The sun rises in the ___.', c: ['morning', 'afternoon', 'evening', 'night'], a: 0,
    ex: 'Mặt trời mọc (rises) buổi SÁNG. Chiều/tối mặt trời lặn.',
    lo: 'Hiện tượng mặt trời mọc.' },
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'animals', d: 5,
    q: 'A tadpole grows into a ___.', c: ['fish', 'frog', 'turtle', 'snake'], a: 1,
    ex: 'Nòng nọc (tadpole) lớn thành ẾCH (frog). Vòng đời biến thái của lưỡng cư.',
    lo: 'Vòng đời nòng nọc - ếch.' },
  { g: 1, skill: 'scientific-observation', dom: 'materials', top: 'objects', d: 5,
    q: 'Which material is BEST for a raincoat?', c: ['paper', 'cotton', 'plastic', 'wool'], a: 2,
    ex: 'Nhựa (plastic) không thấm nước - hợp làm áo mưa. Giấy, vải cotton, len đều thấm.',
    lo: 'Chọn vật liệu chống nước.' },
  { g: 1, skill: 'science-reasoning', dom: 'living-things', top: 'food', d: 5,
    q: 'Which animal eats ONLY plants?', c: ['a lion', 'a rabbit', 'a cat', 'a dog'], a: 1,
    ex: 'Thỏ (rabbit) ăn toàn thực vật - cà rốt, cỏ. Sư tử ăn thịt, mèo và chó ăn tạp.',
    lo: 'Phân biệt động vật ăn cỏ và ăn thịt.' },
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'plants', d: 5,
    q: 'Where does a seed usually start to grow?', c: ['in the air', 'in the soil', 'on a rock', 'in the sea'], a: 1,
    ex: 'Hạt nảy mầm trong ĐẤT (soil) - cần đất, nước, hơi ấm.',
    lo: 'Điều kiện hạt nảy mầm.' },
  { g: 1, skill: 'scientific-observation', dom: 'living-things', top: 'body', d: 4,
    q: 'You taste ice cream with your ___.', c: ['nose', 'tongue', 'ears', 'eyes'], a: 1,
    ex: 'Nếm vị bằng LƯỠI (tongue). Mũi ngửi mùi, mắt nhìn.',
    lo: 'Giác quan vị giác với lưỡi.' },
  { g: 1, skill: 'science-concept', dom: 'earth', top: 'seasons', d: 4,
    q: 'Leaves fall from trees in ___.', c: ['spring', 'autumn', 'summer', 'winter storm'], a: 1,
    ex: 'Lá rụng vào mùa THU (autumn). Xuân lá non, hè lá xanh, đông cây đã trụi.',
    lo: 'Đặc điểm mùa thu.' },
  { g: 1, skill: 'science-reasoning', dom: 'materials', top: 'objects', d: 5,
    q: 'A glass falls on the floor. What happens?', c: ['it bounces', 'it breaks', 'it floats', 'it melts'], a: 1,
    ex: 'Thủy tinh (glass) giòn - rơi xuống sẽ VỠ (breaks). Nảy (bounces) là bóng.',
    lo: 'Tính chất giòn của thủy tinh.' },
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'animals', d: 4,
    q: 'Which animal has NO legs?', c: ['a bird', 'a snake', 'a frog', 'a spider'], a: 1,
    ex: 'Rắn (snake) không chân - bò bằng thân. Chim 2 chân, ếch 4, nhện 8.',
    lo: 'Đếm chân động vật.' },
  { g: 1, skill: 'science-reasoning', dom: 'earth', top: 'weather', d: 5,
    q: 'After heavy rain, you sometimes see a ___ in the sky.', c: ['moon', 'rainbow', 'star', 'cloud only'], a: 1,
    ex: 'Sau mưa có nắng → CẦU VỒNG (rainbow) xuất hiện do nước + ánh sáng.',
    lo: 'Điều kiện xuất hiện cầu vồng.' },
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'needs', d: 4,
    q: 'Fish breathe underwater using their ___.', c: ['lungs', 'gills', 'wings', 'legs'], a: 1,
    ex: 'Cá thở dưới nước bằng MANG (gills). Phổi (lungs) của người và thú.',
    lo: 'Cơ quan hô hấp của cá.' },
  { g: 1, skill: 'scientific-observation', dom: 'materials', top: 'water', d: 4,
    q: 'Ice turns into water when it gets ___.', c: ['cold', 'warm', 'dark', 'heavy'], a: 1,
    ex: 'Đá tan thành nước khi ẤM lên (warm). Lạnh thì nước đông thành đá.',
    lo: 'Đá tan khi ấm.' },
  { g: 1, skill: 'science-reasoning', dom: 'living-things', top: 'animals', d: 5,
    q: 'A chicken lays eggs. Which animal also lays eggs?', c: ['a cow', 'a duck', 'a dog', 'a goat'], a: 1,
    ex: 'Vịt (duck) cũng đẻ trứng - cùng nhóm chim. Bò, chó, dê là thú - đẻ con.',
    lo: 'Động vật đẻ trứng vs đẻ con.' },
  { g: 1, skill: 'science-concept', dom: 'earth', top: 'sky', d: 4,
    q: 'At night we can see the moon and ___.', c: ['the sun', 'stars', 'a rainbow', 'blue sky'], a: 1,
    ex: 'Ban đêm thấy trăng và SAO (stars). Mặt trời và cầu vồng chỉ ban ngày.',
    lo: 'Vật thể trên bầu trời đêm.' },
  { g: 1, skill: 'scientific-observation', dom: 'living-things', top: 'senses', d: 5,
    q: 'Which sense tells you the soup is HOT before you drink it?', c: ['sight', 'smell and steam', 'hearing', 'taste only'], a: 1,
    ex: 'Nhìn hơi bốc lên và ngửi nóng trước khi uống - sight + smell. Taste là nếm - đã muộn.',
    lo: 'Dùng giác quan an toàn trước khi ăn nóng.' },
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'habitats', d: 5,
    q: 'A polar bear lives where it is very ___.', c: ['hot', 'cold', 'dry and sandy', 'wet only'], a: 1,
    ex: 'Gấu Bắc Cực sống nơi LẠNH (cold) - Bắc Cực có tuyết băng.',
    lo: 'Ghép động vật với môi trường sống.' },
  { g: 1, skill: 'science-reasoning', dom: 'materials', top: 'recycling', d: 5,
    q: 'Which bin do we put a plastic bottle in?', c: ['food bin', 'recycling bin', 'garden bin', 'any bin'], a: 1,
    ex: 'Chai nhựa tái chế được → thùng RECYCLING. Thùng food cho rác thức ăn.',
    lo: 'Phân loại rác tái chế.' },
  { g: 1, skill: 'science-concept', dom: 'living-things', top: 'plants', d: 4,
    q: 'Bees visit flowers to collect ___.', c: ['nectar', 'leaves', 'soil', 'rain'], a: 0,
    ex: 'Ong hút MẬT HOA (nectar) từ hoa, từ đó làm mật ong.',
    lo: 'Ong và mật hoa.' },
  { g: 1, skill: 'science-reasoning', dom: 'earth', top: 'day-night', d: 5,
    q: 'We have day and night because ___.', c: [
      'the sun goes to sleep',
      'the Earth spins around',
      'the moon is big',
      'stars push the sky',
    ], a: 1,
    ex: 'Trái Đất TỰ QUAY (spins) - phần quay về mặt trời là ngày, phần khuất là đêm.',
    lo: 'Nguyên nhân ngày - đêm: Trái Đất tự quay.' },

  // ---------- GRADE 2 - CR-66 bo sung ----------
  { g: 2, skill: 'science-concept', dom: 'living-things', top: 'life-cycles', d: 4,
    q: 'A caterpillar changes into a ___.', c: ['bee', 'butterfly', 'bird', 'bat'], a: 1,
    ex: 'Sâu bướm (caterpillar) biến thành BƯỚM (butterfly) qua nhộng. Vòng đời biến thái hoàn toàn.',
    lo: 'Vòng đời sâu - nhộng - bướm.' },
  { g: 2, skill: 'science-reasoning', dom: 'materials', top: 'states', d: 4,
    q: 'Water turns into ice when the temperature is ___ 0 degrees.', c: ['above', 'below', 'exactly 100', 'hot'], a: 1,
    ex: 'Nước đông thành đá khi DƯỚI 0 độ (below). Trên 100 độ nước sôi thành hơi.',
    lo: 'Nhiệt độ đông đá của nước.' },
  { g: 2, skill: 'science-concept', dom: 'living-things', top: 'habitats', d: 4,
    q: 'A camel lives in the ___ where it is hot and dry.', c: ['ocean', 'desert', 'forest', 'arctic'], a: 1,
    ex: 'Lạc đà sống ở SA MẠC (desert) - nóng và khô, có bướu chứa mỡ.',
    lo: 'Môi trường sống của lạc đà.' },
  { g: 2, skill: 'scientific-observation', dom: 'forces', top: 'push-pull', d: 4,
    q: 'To open a door, you can ___ it or pull it.', c: ['push', 'eat', 'throw', 'draw'], a: 0,
    ex: 'Mở cửa: đẩy (push) hoặc kéo (pull) - hai lực ngược chiều cơ bản.',
    lo: 'Hai lực cơ bản push và pull.' },
  { g: 2, skill: 'science-reasoning', dom: 'living-things', top: 'food-chain', d: 4,
    q: 'Grass → rabbit → fox. The fox is the ___.', c: ['producer', 'prey', 'predator', 'plant'], a: 2,
    ex: 'Cáo ăn thỏ → cáo là THÚ SĂN MỒI (predator). Cỏ là producer, thỏ là prey (con mồi).',
    lo: 'Chuỗi thức ăn: nhận biết predator.' },
  { g: 2, skill: 'science-concept', dom: 'earth', top: 'seasons', d: 4,
    q: 'In which season do we wear the warmest clothes?', c: ['summer', 'winter', 'spring', 'autumn'], a: 1,
    ex: 'Mùa đông (winter) lạnh nhất → mặc ấm nhất.',
    lo: 'Mùa lạnh nhất và trang phục.' },
  { g: 2, skill: 'science-reasoning', dom: 'living-things', top: 'plants', d: 4,
    q: 'Why do plants grow TOWARDS the window?', c: [
      'they want fresh air',
      'they need sunlight to make food',
      'they like looking outside',
      'they are scared of the dark',
    ], a: 1,
    ex: 'Cây vươn về phía cửa sổ vì cần ÁNH SÁNG quang hợp làm thức ăn.',
    lo: 'Cây hướng sáng - phototropism.' },
  { g: 2, skill: 'science-concept', dom: 'materials', top: 'water', d: 4,
    q: 'Water boils and becomes ___ at 100 degrees.', c: ['ice', 'steam', 'snow', 'rain'], a: 1,
    ex: 'Nước sôi ở 100 độ → hóa hơi nước (steam). Đá, tuyết là thể rắn lạnh.',
    lo: 'Ba thể của nước: sôi thành hơi.' },
  { g: 2, skill: 'scientific-observation', dom: 'living-things', top: 'senses', d: 4,
    q: 'Your skin feels if something is hot, cold, soft or hard. Which sense is it?', c: ['sight', 'touch', 'hearing', 'taste'], a: 1,
    ex: 'Da cảm nhận nóng/lạnh/mềm/cứng → xúc giác (touch).',
    lo: 'Giác quan xúc giác qua da.' },
  { g: 2, skill: 'science-reasoning', dom: 'earth', top: 'space', d: 4,
    q: 'The moon we see does NOT make its own light. Where does its light come from?', c: [
      'the stars',
      'it reflects sunlight',
      'lamps on the moon',
      'the ocean',
    ], a: 1,
    ex: 'Mặt trăng không tự phát sáng - nó PHẢN CHIẾU ánh sáng mặt trời.',
    lo: 'Mặt trăng phản chiếu ánh sáng.' },
  { g: 2, skill: 'science-concept', dom: 'living-things', top: 'health', d: 4,
    q: 'Which food gives us strong bones?', c: ['candy', 'milk', 'chips', 'soda'], a: 1,
    ex: 'Sữa (milk) nhiều canxi → xương chắc. Kẹo, chips, soda không tốt cho xương.',
    lo: 'Thực phẩm tốt cho xương.' },
  { g: 2, skill: 'science-reasoning', dom: 'materials', top: 'states', d: 5,
    q: 'You leave a cold drink outside on a hot day. Drops appear on the glass. Why?', c: [
      'the glass is leaking',
      'water in the air turns to liquid on the cold glass',
      'the ice inside escapes',
      'someone spilled water on it',
    ], a: 1,
    ex: 'Hơi nước trong KHÔNG KHÍ gặp cốc lạnh → ngưng tụ thành giọt nước. Ly không bị rò.',
    lo: 'Hiện tượng ngưng tụ hơi nước.' },
  { g: 2, skill: 'science-concept', dom: 'living-things', top: 'animals', d: 4,
    q: 'Which group do humans belong to?', c: ['reptiles', 'insects', 'mammals', 'birds'], a: 2,
    ex: 'Người là THÚ (mammals) - đẻ con, nuôi con bằng sữa, có lông/tóc.',
    lo: 'Người thuộc nhóm động vật có vú.' },
  { g: 2, skill: 'science-reasoning', dom: 'forces', top: 'gravity', d: 5,
    q: 'You drop a ball and it falls DOWN, not up, because of ___.', c: ['wind', 'gravity', 'light', 'sound'], a: 1,
    ex: 'Vật rơi xuống do TRỌNG LỰC (gravity) - Trái Đất hút mọi vật về phía nó.',
    lo: 'Trọng lực kéo vật xuống.' },
  { g: 2, skill: 'science-concept', dom: 'earth', top: 'environment', d: 5,
    q: 'Cutting down too many trees is bad because trees ___.', c: [
      'make the air dirty',
      'give us oxygen and homes for animals',
      'block all sunlight forever',
      'drink all the water in the sea',
    ], a: 1,
    ex: 'Cây cho OXYGEN và là nhà của động vật - chặt nhiều cây hại môi trường.',
    lo: 'Vai trò của cây với môi trường.' },
  { g: 2, skill: 'scientific-observation', dom: 'materials', top: 'objects', d: 4,
    q: 'Which object is TRANSPARENT - you can see through it?', c: ['a wooden door', 'a glass window', 'a brick wall', 'a book'], a: 1,
    ex: 'Kính cửa sổ (glass window) TRONG SUỐT - nhìn xuyên qua được. Cửa gỗ, tường, sách không.',
    lo: 'Vật liệu trong suốt.' },
  { g: 2, skill: 'science-reasoning', dom: 'living-things', top: 'habitats', d: 4,
    q: 'Fish cannot live on land because they need ___ to breathe.', c: ['air', 'water', 'soil', 'leaves'], a: 1,
    ex: 'Cá thở bằng mang - chỉ lấy oxygen từ NƯỚC. Lên bờ thiếu nước sẽ chết.',
    lo: 'Điều kiện sống của cá.' },
  { g: 2, skill: 'science-concept', dom: 'living-things', top: 'life-cycles', d: 5,
    q: 'Put the stages in order: egg → ___ → butterfly.', c: ['caterpillar and pupa', 'bird and chick', 'tadpole and frog', 'seed and flower'], a: 0,
    ex: 'Bướm: trứng → sâu bướm (caterpillar) → nhộng (pupa) → bướm. 4 giai đoạn biến thái.',
    lo: 'Đúng thứ tự vòng đời bướm.' },
  { g: 2, skill: 'science-reasoning', dom: 'earth', top: 'weather-tools', d: 5,
    q: 'A thermometer measures ___.', c: ['wind speed', 'temperature', 'rainfall', 'time'], a: 1,
    ex: 'Nhiệt kế (thermometer) đo NHIỆT ĐỘ. Gió đo bằng cốc quay, mưa đo bằng vũ kế.',
    lo: 'Dụng cụ đo nhiệt độ.' },
  { g: 2, skill: 'science-concept', dom: 'materials', top: 'objects', d: 4,
    q: 'Which keeps food cold and fresh?', c: ['an oven', 'a fridge', 'a lamp', 'a radio'], a: 1,
    ex: 'Tủ lạnh (fridge) giữ đồ ăn LẠNH và tươi. Lò (oven) làm nóng.',
    lo: 'Công dụng đồ điện trong nhà.' },
  { g: 2, skill: 'science-reasoning', dom: 'living-things', top: 'health', d: 5,
    q: 'Why should we wash hands before eating?', c: [
      'to make hands smell nice',
      'to remove germs that make us sick',
      'to make food taste better',
      'to warm our hands',
    ], a: 1,
    ex: 'Rửa tay loại bỏ VI KHUẨN (germs) gây bệnh - vệ sinh trước khi ăn.',
    lo: 'Vệ sinh tay và vi khuẩn.' },
  { g: 2, skill: 'science-concept', dom: 'earth', top: 'day-night', d: 4,
    q: 'The sun seems to set (go down) in the ___.', c: ['morning', 'evening', 'at noon', 'at midnight'], a: 1,
    ex: 'Mặt trời lặn (set) buổi TỐI (evening). Mọc buổi sáng, đứng bóng buổi trưa.',
    lo: 'Mặt trời lặn buổi tối.' },
  { g: 2, skill: 'science-reasoning', dom: 'forces', top: 'floating', d: 4,
    q: 'A heavy metal ship can float but a small metal coin sinks. Why?', c: [
      'the ship is lighter',
      'the ship shape pushes away enough water',
      'the coin is too shiny',
      'ships have engines',
    ], a: 1,
    ex: 'Thuyền nổi vì HÌNH DẠNG rộng chiếm chỗ nhiều nước (lực đẩy Archimedes). Đồng xu nhỏ chìm vì đặc.',
    lo: 'Vì sao tàu nổi dù nặng.' },
  { g: 2, skill: 'science-concept', dom: 'living-things', top: 'plants', d: 5,
    q: 'Where do most plants get energy to grow?', c: ['the soil only', 'sunlight', 'other plants', 'the wind'], a: 1,
    ex: 'Cây lấy năng lượng từ ÁNH SÁNG MẶT TRỜI qua quang hợp. Đất chỉ cung cấp nước và chất khoáng.',
    lo: 'Quang hợp - nguồn năng lượng của cây.' },
  { g: 2, skill: 'scientific-observation', dom: 'materials', top: 'recycling', d: 5,
    q: 'Which item can be RECYCLED?', c: ['a banana peel', 'a plastic bottle', 'a tissue', 'a broken biscuit'], a: 1,
    ex: 'Chai nhựa tái chế được. Vỏ chuối compost được (rác hữu cơ), khăn giấy không.',
    lo: 'Vật liệu tái chế được.' },
  { g: 2, skill: 'science-reasoning', dom: 'living-things', top: 'animals', d: 5,
    q: 'Penguins have fat under their skin. It helps them ___.', c: [
      'swim faster',
      'stay warm in cold places',
      'fly higher',
      'hide from foxes',
    ], a: 1,
    ex: 'Lớp mỡ dưới da cách nhiệt → giữ ẤM ở vùng lạnh. Chim cánh cụt sống ở Nam Cực.',
    lo: 'Thích nghi của động vật vùng lạnh.' },
  { g: 2, skill: 'science-concept', dom: 'earth', top: 'safety', d: 4,
    q: 'Before crossing the road, you should ___.', c: [
      'run fast',
      'look left and right',
      'close your eyes',
      'shout loudly',
    ], a: 1,
    ex: 'Qua đường phải nhìn TRÁI và PHẢI trước - an toàn giao thông cơ bản.',
    lo: 'An toàn qua đường.' },
  { g: 2, skill: 'science-reasoning', dom: 'materials', top: 'states', d: 4,
    q: 'In the morning you see water drops on grass and leaves. This is called ___.', c: ['rain', 'dew', 'snow', 'smoke'], a: 1,
    ex: 'Giọt nước sáng sớm trên cỏ là SƯƠNG (dew) - hơi nước ngưng tụ đêm khuya.',
    lo: 'Hiện tượng sương đọng.' },
  { g: 2, skill: 'science-concept', dom: 'living-things', top: 'senses', d: 4,
    q: 'Dogs hear sounds we cannot hear. Their sense of hearing is ___ than ours.', c: ['worse', 'better', 'the same', 'gone'], a: 1,
    ex: 'Chó nghe tốt HƠN người (better) - bắt được tần số cao con người không nghe được.',
    lo: 'So sánh giác quan người và động vật.' },
  { g: 2, skill: 'science-reasoning', dom: 'earth', top: 'environment', d: 5,
    q: 'Which action helps the Earth?', c: [
      'throwing plastic in the river',
      'planting trees and saving water',
      'leaving lights on all day',
      'burning rubbish',
    ], a: 1,
    ex: 'Trồng cây + tiết kiệm nước giúp Trái Đất. Xả rác, để đèn sáng, đốt rác đều hại.',
    lo: 'Hành động bảo vệ môi trường.' },
  { g: 2, skill: 'science-concept', dom: 'forces', top: 'magnets', d: 4,
    q: 'Two magnets push away when the same poles face each other. This is called ___.', c: ['attract', 'repel', 'melt', 'freeze'], a: 1,
    ex: 'Cùng cực → ĐẨY nhau (repel). Khác cực → hút (attract).',
    lo: 'Nam châm cùng cực đẩy nhau.' },

  // ---------- GRADE 3 - CR-66 bo sung ----------
  { g: 3, skill: 'science-concept', dom: 'light', top: 'shadows', d: 4,
    q: 'A shadow forms when an object ___ light.', c: ['makes', 'blocks', 'eats', 'follows'], a: 1,
    ex: 'Bóng hình thành khi vật CHẶN (blocks) ánh sáng - phần sau vật không nhận sáng.',
    lo: 'Nguyên nhân hình thành bóng.' },
  { g: 3, skill: 'science-reasoning', dom: 'living-things', top: 'skeletons', d: 4,
    q: 'Why do humans need a skeleton?', c: [
      'to look scary',
      'to support the body and protect organs',
      'to make us taller at night',
      'to store water',
    ], a: 1,
    ex: 'Xương ĐỠ cơ thể đứng vững và BẢO VỆ nội tạng (sọ bảo vệ não, xương sườn bảo vệ tim).',
    lo: 'Chức năng của bộ xương.' },
  { g: 3, skill: 'science-concept', dom: 'materials', top: 'rocks', d: 4,
    q: 'Which rock can float because it is full of tiny holes?', c: ['granite', 'pumice', 'marble', 'chalk'], a: 1,
    ex: 'Đá bọt (pumice) có lỗ rỗng chứa khí nên NỔI trên nước - đá duy nhất nổi được.',
    lo: 'Đá pumice và đặc tính rỗng.' },
  { g: 3, skill: 'scientific-observation', dom: 'light', top: 'reflection', d: 4,
    q: 'You can see your face in a mirror because light ___.', c: [
      'goes through it',
      'bounces off it',
      'stays inside it',
      'turns into sound',
    ], a: 1,
    ex: 'Gương phẳng PHẢN XẠ (bounces off) ánh sáng → ta thấy hình của mình.',
    lo: 'Phản xạ ánh sáng trên gương.' },
  { g: 3, skill: 'science-reasoning', dom: 'living-things', top: 'nutrition', d: 4,
    q: 'A balanced lunch should have carbohydrates, protein and ___.', c: [
      'only sugar',
      'vitamins and water',
      'nothing else',
      'only fat',
    ], a: 1,
    ex: 'Bữa ăn cân bằng cần tinh bột + đạm + VITAMIN và nước. Chỉ đường hoặc chỉ mỡ thì thiếu chất.',
    lo: 'Thành phần bữa ăn cân bằng.' },
  { g: 3, skill: 'science-concept', dom: 'forces', top: 'friction', d: 4,
    q: 'Bike brakes work by using ___ to slow the wheels.', c: ['light', 'friction', 'sound', 'magnetism'], a: 1,
    ex: 'Phanh xe ép má phanh vào bánh → MA SÁT (friction) làm bánh chậm lại.',
    lo: 'Ma sát trong phanh xe đạp.' },
  { g: 3, skill: 'science-reasoning', dom: 'light', top: 'shadows', d: 5,
    q: 'Your shadow is SHORTEST when the sun is ___.', c: [
      'low in the morning',
      'high in the sky at noon',
      'behind clouds',
      'rising',
    ], a: 1,
    ex: 'Mặt trời CAO (giữa trưa) → bóng NGẮN nhất. Mặt trời thấp → bóng dài.',
    lo: 'Vị trí mặt trời và độ dài bóng.' },
  { g: 3, skill: 'science-concept', dom: 'living-things', top: 'plants', d: 4,
    q: 'Which part of a flower makes seeds?', c: ['petals', 'the centre after pollination', 'the stem', 'the thorns'], a: 1,
    ex: 'Sau thụ phấn (pollination), phần GIỮA hoa tạo hạt. Cánh hoa chỉ thu hút côn trùng.',
    lo: 'Hoa tạo hạt sau thụ phấn.' },
  { g: 3, skill: 'science-reasoning', dom: 'materials', top: 'rocks', d: 4,
    q: 'Chalk and limestone both came from ___.', c: [
      'dead sea creatures long ago',
      'melted plastic',
      'tree roots',
      'burnt wood',
    ], a: 0,
    ex: 'Đá phấn và đá vôi hình thành từ xác sinh vật biển cổ đại nén lại hàng triệu năm.',
    lo: 'Nguồn gốc đá vôi từ sinh vật biển.' },
  { g: 3, skill: 'science-concept', dom: 'forces', top: 'magnets', d: 4,
    q: 'Which metal is magnetic?', c: ['aluminium', 'iron', 'copper', 'gold'], a: 1,
    ex: 'Sắt (iron) bị nam châm hút. Nhôm, đồng, vàng KHÔNG hút - bẫy kinh điển vì đều là kim loại.',
    lo: 'Kim loại từ tính: iron.' },
  { g: 3, skill: 'science-reasoning', dom: 'living-things', top: 'muscles', d: 4,
    q: 'When you bend your arm, your bicep muscle ___.', c: ['gets longer', 'gets shorter and pulls', 'disappears', 'turns to bone'], a: 1,
    ex: 'Cơ nhị đầu CO LẠI (shorter) và kéo cẳng tay lên. Cơ chỉ kéo được, không đẩy được.',
    lo: 'Cơ bắp co lại để kéo xương.' },
  { g: 3, skill: 'science-concept', dom: 'light', top: 'sources', d: 4,
    q: 'Which one is NOT a light source?', c: ['the sun', 'a candle', 'a mirror', 'a torch'], a: 2,
    ex: 'Gương (mirror) chỉ PHẢN XẠ ánh sáng, không tự phát sáng. Mặt trời, nến, đèn pin đều phát sáng.',
    lo: 'Phân biệt nguồn sáng và vật phản xạ.' },
  { g: 3, skill: 'science-reasoning', dom: 'living-things', top: 'skeletons', d: 5,
    q: 'A worm has no bones. It is called an ___.', c: ['invertebrate', 'vertebrate', 'mammal', 'amphibian'], a: 0,
    ex: 'Động vật không xương sống = invertebrate. Có xương sống = vertebrate.',
    lo: 'Invertebrate vs vertebrate.' },
  { g: 3, skill: 'science-concept', dom: 'materials', top: 'soil', d: 4,
    q: 'Plants grow best in soil that is ___.', c: ['only sand', 'rich with nutrients', 'only stones', 'dry and dead'], a: 1,
    ex: 'Đất GIÀU DINH DƯỠNG (rich with nutrients) cho cây lớn tốt. Cát và đá trơ không giữ nước/chất.',
    lo: 'Đất tốt cho cây trồng.' },
  { g: 3, skill: 'science-reasoning', dom: 'light', top: 'safety', d: 5,
    q: 'You should never look directly at the sun because it can ___.', c: [
      'make you sneeze',
      'damage your eyes',
      'turn you invisible',
      'make you sleepy',
    ], a: 1,
    ex: 'Nhìn mặt trời trực tiếp LÀM TỔN THƯƠNG MẮT (damage eyes) - võng mạc bị bỏng.',
    lo: 'An toàn với ánh sáng mặt trời.' },
  { g: 3, skill: 'science-concept', dom: 'forces', top: 'magnets', d: 5,
    q: 'A compass needle points north because it is attracted by the Earth\'s ___.', c: [
      'magnetic field',
      'oceans',
      'mountains',
      'gravity alone',
    ], a: 0,
    ex: 'La bàn là nam châm nhỏ - bị TỪ TRƯỜNG Trái Đất (magnetic field) hút về phương Bắc.',
    lo: 'La bàn và từ trường Trái Đất.' },
  { g: 3, skill: 'science-reasoning', dom: 'living-things', top: 'nutrition', d: 5,
    q: 'Too much sugar and no exercise can lead to ___.', c: [
      'stronger muscles',
      'health problems like obesity',
      'better eyesight',
      'faster running',
    ], a: 1,
    ex: 'Nhiều đường + ít vận động → BÉO PHÌ (obesity) và bệnh. Đường là năng lượng thừa.',
    lo: 'Tác hại đường quá mức.' },
  { g: 3, skill: 'science-concept', dom: 'materials', top: 'fossils', d: 4,
    q: 'A fossil of a fish found on a mountain tells us the mountain was once ___.', c: [
      'under the sea',
      'a volcano only',
      'a forest',
      'made of ice',
    ], a: 0,
    ex: 'Hóa thạch cá trên núi → nơi đó TỪNG Ở DƯỚI BIỂN (under the sea), nâng lên do địa chất.',
    lo: 'Hóa thạch chứng minh biến đổi địa hình.' },
  { g: 3, skill: 'scientific-observation', dom: 'forces', top: 'surfaces', d: 5,
    q: 'A toy car rolls fastest on ___.', c: ['carpet', 'smooth tile floor', 'grass', 'sand'], a: 1,
    ex: 'Sàn gạch PHẲNG/NHẴN ít ma sát nhất → xe lăn nhanh nhất. Thảm, cỏ, cát cản nhiều.',
    lo: 'Ma sát theo bề mặt.' },
  { g: 3, skill: 'science-concept', dom: 'living-things', top: 'plants', d: 4,
    q: 'Roots hold the plant in the ground AND take in ___.', c: ['sunlight', 'water and minerals', 'air for photosynthesis', 'insects'], a: 1,
    ex: 'Rễ neo cây VÀ hút nước + khoáng chất từ đất. Ánh sáng lá lo, không phải rễ.',
    lo: 'Hai chức năng của rễ.' },
  { g: 3, skill: 'science-reasoning', dom: 'light', top: 'shadows', d: 5,
    q: 'A solid object makes a dark shadow, but a glass window makes almost none because glass is ___.', c: [
      'heavy',
      'transparent',
      'cold',
      'soft',
    ], a: 1,
    ex: 'Kính TRONG SUỐT (transparent) - ánh sáng xuyên qua nên gần như không có bóng.',
    lo: 'Bóng chỉ xuất hiện khi vật chặn sáng.' },
  { g: 3, skill: 'science-concept', dom: 'living-things', top: 'teeth', d: 4,
    q: 'Which teeth cut food - the sharp flat ones at the front?', c: ['molars', 'incisors', 'canines', 'wisdom'], a: 1,
    ex: 'Răng CỬA (incisors) phẳng và sắc ở phía trước - cắn cắt thức ăn. Răng hàm nghiền.',
    lo: 'Các loại răng và chức năng.' },
  { g: 3, skill: 'science-reasoning', dom: 'materials', top: 'states', d: 4,
    q: 'When steam touches a cold mirror it becomes water again. This is called ___.', c: ['melting', 'condensation', 'evaporation', 'freezing'], a: 1,
    ex: 'Hơi nước gặp lạnh → giọt nước = NGƯNG TỤ (condensation). Evaporation là bay hơi - ngược lại.',
    lo: 'Ngưng tụ hơi nước.' },
  { g: 3, skill: 'science-concept', dom: 'forces', top: 'push-pull', d: 4,
    q: 'Opening a drawer uses a ___ force.', c: ['pull', 'push only', 'magnetic', 'electric'], a: 0,
    ex: 'Kéo ngăn kéo ra = lực KÉO (pull). Đóng lại mới là đẩy (push).',
    lo: 'Nhận diện lực kéo trong đời sống.' },
  { g: 3, skill: 'science-reasoning', dom: 'living-things', top: 'skeletons', d: 5,
    q: 'A crab has a hard cover on the OUTSIDE. This is called ___.', c: ['a skeleton', 'an exoskeleton', 'a muscle', 'a shell only - not bones'], a: 1,
    ex: 'Giáp ngoài cứng của cua = EXOSKELETON (xương ngoài). Người có xương TRONG - endoskeleton.',
    lo: 'Xương ngoài vs xương trong.' },
  { g: 3, skill: 'science-concept', dom: 'light', top: 'sources', d: 5,
    q: 'The moon is bright at night but it is NOT a light source because it ___.', c: [
      'is too far away',
      'only reflects the sun\'s light',
      'turns off during day',
      'is made of rock',
    ], a: 1,
    ex: 'Trăng sáng vì PHẢN CHIẾU ánh mặt trời - không tự phát sáng nên không phải nguồn sáng.',
    lo: 'Mặt trăng không phải nguồn sáng.' },
  { g: 3, skill: 'science-reasoning', dom: 'materials', top: 'rocks', d: 5,
    q: 'Which rock is formed when hot melted rock (lava) cools down?', c: ['sedimentary', 'igneous', 'metamorphic', 'sandstone'], a: 1,
    ex: 'Đá từ dung nham nguội = IGNEOUS (đá mác-ma). Sedimentary do trầm tích, metamorphic do biến chất.',
    lo: 'Ba loại đá: đá magma.' },
  { g: 3, skill: 'science-concept', dom: 'living-things', top: 'plants', d: 5,
    q: 'If a plant gets NO sunlight for a long time, it will ___.', c: [
      'grow faster',
      'turn pale and die',
      'make more seeds',
      'become a tree',
    ], a: 1,
    ex: 'Thiếu sáng → không quang hợp được → cây nhạt màu (etiolation) rồi chết.',
    lo: 'Cây thiếu sáng sẽ chết.' },
  { g: 3, skill: 'scientific-observation', dom: 'forces', top: 'friction', d: 5,
    q: 'Why do football shoes have studs on the bottom?', c: [
      'to look nice',
      'to grip the grass and not slip',
      'to run faster on ice',
      'to make the shoes lighter',
    ], a: 1,
    ex: 'Đinh giày BÁM cỏ tốt hơn - tăng ma sát, chống trượt. Không liên quan tốc độ trên băng.',
    lo: 'Tăng ma sát bằng đinh giày.' },
  { g: 3, skill: 'science-concept', dom: 'earth', top: 'water-cycle', d: 5,
    q: 'In the water cycle, water from rivers and seas goes up into the air by ___.', c: [
      'rain',
      'evaporation',
      'condensation',
      'collection',
    ], a: 1,
    ex: 'Nước BAY HƠI (evaporation) lên trời → ngưng tụ thành mây → mưa rơi xuống. Vòng tuần hoàn nước.',
    lo: 'Bay hơi trong vòng tuần hoàn nước.' },
  { g: 3, skill: 'science-reasoning', dom: 'living-things', top: 'health', d: 4,
    q: 'Which exercise is BEST for a strong heart?', c: ['sleeping', 'running and swimming', 'watching TV', 'eating fast food'], a: 1,
    ex: 'Chạy và bơi là bài tập TIM MẠCH (cardio) - tim đập nhanh hơn, khỏe hơn.',
    lo: 'Vận động tốt cho tim.' },
  { g: 3, skill: 'science-concept', dom: 'materials', top: 'objects', d: 4,
    q: 'A raincoat should be waterproof AND a warm coat should be ___.', c: ['heavy metal', 'thick and insulating', 'transparent', 'made of glass'], a: 1,
    ex: 'Áo ấm cần DÀY và CÁCH NHIỆT (insulating) giữ hơi cơ thể. Áo mưa cần không thấm.',
    lo: 'Vật liệu giữ nhiệt.' },
];
