import type { GrammarBankItem } from '../../data/grammarBank';
import type {
  GrammarMcqQuestion,
  MissingLetterQuestion,
  TrueFalseQuestion,
  ExamQuestion,
} from '../../types/exam';
import { seededShuffleIndices } from '../prng';
import { grammarBankForGrade } from '../../data/grammarBank';
import { ioeBanksForGrade } from '../../data/ioeBanks';
import { ioeBankForGrade } from '../../data/ioeRealBank';
import { readingBankForGrade } from '../../data/readingBank';

/**
 * CR-24 - wraps an authored MCQ bank into ExamQuestion objects.
 * Option order is shuffled deterministically per item so the stored
 * `answer` index never leaks position.
 */
function toMcqQuestions(
  items: readonly GrammarBankItem[],
  gradeId: string,
  topicId: string,
  idPrefix: string,
): GrammarMcqQuestion[] {
  return items.map((item, i) => {
    const order = seededShuffleIndices(4, `${idPrefix}-${gradeId}-${i}`);
    const options = order.map((ix) => item.options[ix]!) as [string, string, string, string];
    const correctIndex = order.indexOf(item.answer) as 0 | 1 | 2 | 3;
    return {
      id: `q-${idPrefix}-${gradeId}-${i}`,
      topicId,
      kind: 'grammar-mcq',
      prompt: item.prompt,
      options,
      correctIndex,
      explanation: item.explanationVi,
    };
  });
}

export function generateGrammarMcqQuestions(gradeId: string): GrammarMcqQuestion[] {
  return toMcqQuestions(grammarBankForGrade(gradeId), gradeId, 'grammar', 'gmcq');
}

/**
 * CR-26 - the extra IOE types observed in a real G4 exam, all MCQ-
 * shaped: masked-word spelling, reference-letter pronunciation, error
 * correction, which-is-correct and calendar facts. Grade 1-2 only gets
 * the spelling masks (the rest is above their level).
 */
export function generateIoeMcqQuestions(gradeId: string): GrammarMcqQuestion[] {
  const banks = ioeBanksForGrade(gradeId);
  return [
    ...toMcqQuestions(banks.spelling, gradeId, 'spelling', 'spell'),
    ...toMcqQuestions(banks.pronunciation, gradeId, 'pronunciation', 'pron'),
    ...toMcqQuestions(banks.error, gradeId, 'grammar', 'err'),
    ...toMcqQuestions(banks.correct, gradeId, 'grammar', 'corr'),
    ...toMcqQuestions(banks.facts, gradeId, 'facts', 'fact'),
  ];
}

/**
 * Real IOE question bank harvested from authorized Thi thử / Tu luyện
 * sessions per grade (scripts/ioe-convert-all.mjs). Coverage is
 * grade-specific: G4 is the deepest (Thi thử bank), G1-3/G5 come from
 * Tu luyện rounds. Grade 5 also falls back to the G4 bank - same band.
 */
export function ioeRealBankForGrade(gradeId: string) {
  return ioeBankForGrade(gradeId);
}

/** Pick up to `n` distractor words of similar length from the same bank. */
function makeWordDistractors(word: string, others: readonly { word: string }[]): string[] {
  return others
    .filter((o) => o.word !== word && Math.abs(o.word.length - word.length) <= 2)
    .slice(0, 3)
    .map((o) => o.word);
}

export function generateIoeRealMcqQuestions(gradeId: string): GrammarMcqQuestion[] {
  const bank = ioeRealBankForGrade(gradeId);
  if (!bank) return [];
  const mcqs = [...bank.mcq];
  // Grade 5 reuses the G4 mcq pool - same curriculum band.
  if (gradeId === 'grade-5') mcqs.push(...(ioeBankForGrade('grade-4')?.mcq ?? []));
  const makeWordBank: GrammarBankItem[] = bank.makeWord
    .map((item) => ({
      prompt: `Ghép các mảnh sau thành từ đúng: ${item.chunks.join(' - ')}`,
      options: [item.word, ...makeWordDistractors(item.word, bank.makeWord)] as [string, string, string, string],
      answer: 0 as const,
      explanationVi: `Các mảnh ghép lại được từ "${item.word}".`,
    }))
    .filter((i) => i.options.length === 4);
  const makeWordItems = toMcqQuestions(makeWordBank, gradeId, 'makeword', 'mkw');
  return [...toMcqQuestions(mcqs, gradeId, 'ioe', 'ioe-mcq'), ...makeWordItems];
}

export function generateIoeRealMaskedQuestions(gradeId: string): MissingLetterQuestion[] {
  const bank = ioeRealBankForGrade(gradeId);
  if (!bank) return [];
  const items = gradeId === 'grade-5'
    ? [...bank.masked, ...(ioeBankForGrade('grade-4')?.masked ?? [])]
    : bank.masked;
  return items.map((item, i) => {
    const maskedToken = item.displaySentence.match(/[\w'-]*(?:_ )+_?[\w'-]*/)?.[0] ?? item.displaySentence;
    return {
      id: `q-ioe-ml-${i}`,
      topicId: 'ioe',
      kind: 'missing-letter' as const,
      word: item.word,
      wordId: `ioe-${i}`,
      maskedWord: maskedToken,
      missing: item.missing,
      sentence: item.sentence,
      displaySentence: item.displaySentence,
      explanation: `Điền "${item.missing}" để được từ "${item.word}".`,
    };
  });
}

/**
 * CR-35 - harvested IOE listening transcripts become real listening
 * questions. Short items (<= 2 words) are "hear it, type it" dictation;
 * longer lines blank one content word - "hear the sentence, type the
 * missing word" exactly like the IOE type-12/13 games they came from.
 * Audio is generated by the app's TTS at render time, so no external
 * media is needed.
 */
export function generateIoeRealListenQuestions(gradeId: string): ExamQuestion[] {
  const bank = ioeRealBankForGrade(gradeId);
  if (!bank) return [];
  const items = gradeId === 'grade-5'
    ? [...bank.listen, ...(ioeBankForGrade('grade-4')?.listen ?? [])]
    : bank.listen;
  const questions: ExamQuestion[] = [];
  items.forEach((raw, i) => {
    const sentence = raw.trim().replace(/\s+/g, ' ');
    const tokens = sentence.split(' ');
    if (tokens.length <= 2) {
      // Dictation of a word or two-word chunk ("Thank you", "Bye").
      const word = sentence.replace(/[.!?,]+$/g, '');
      if (!word) return;
      questions.push({
        id: `q-ioe-lf-${gradeId}-${i}`,
        topicId: 'ioe-listening',
        kind: 'listening-fill-blank',
        word,
        explanation: `Nghe kỹ rồi gõ lại: "${word}".`,
      });
      return;
    }
    // Pick the blank: the LAST alphabetic token of length >= 3 (content
    // words sit at the end in these lines), never a leading "I"/"I'm".
    let blankIndex = -1;
    for (let t = tokens.length - 1; t >= 0; t--) {
      const bare = tokens[t]!.replace(/[^A-Za-z']/g, '');
      if (bare.length >= 3) {
        blankIndex = t;
        break;
      }
    }
    if (blankIndex === -1) {
      for (let t = tokens.length - 1; t >= 0; t--) {
        if (/[A-Za-z]/.test(tokens[t]!)) {
          blankIndex = t;
          break;
        }
      }
    }
    if (blankIndex === -1) return;
    const word = tokens[blankIndex]!.replace(/[^A-Za-z']/g, '');
    if (!word) return;
    // Keep the token's punctuation - "pizza." renders "___.".
    const display = tokens
      .map((tok, t) => (t === blankIndex ? tok.replace(/[A-Za-z']+/g, '___') : tok))
      .join(' ');
    questions.push({
      id: `q-ioe-ls-${gradeId}-${i}`,
      topicId: 'ioe-listening',
      kind: 'listening-sentence-fill-blank',
      word,
      wordId: `ioe-ls-${gradeId}-${i}`,
      sentence,
      displaySentence: display,
      explanation: `Nghe kỹ câu nói - từ còn thiếu là "${word}".`,
    });
  });
  return questions;
}

export function generateIoeRealTfQuestions(gradeId: string): TrueFalseQuestion[] {
  const bank = ioeRealBankForGrade(gradeId);
  if (!bank) return [];
  const items = gradeId === 'grade-5'
    ? [...bank.tf, ...(ioeBankForGrade('grade-4')?.tf ?? [])]
    : bank.tf;
  return items.map((item, i) => ({
    id: `q-ioe-tf-${i}`,
    topicId: 'reading',
    kind: 'true-false-reading' as const,
    passage: item.passage,
    statement: item.statement,
    answer: item.answer,
    explanation: 'Đối chiếu câu này với thông tin trong đoạn văn.',
  }));
}

/** Reading comprehension True/False questions from the passage bank. */
export function generateTrueFalseQuestions(gradeId: string): TrueFalseQuestion[] {
  const questions: TrueFalseQuestion[] = [];
  let n = 0;
  for (const passage of readingBankForGrade(gradeId)) {
    for (const stmt of passage.statements) {
      questions.push({
        id: `q-tf-${gradeId}-${n++}`,
        topicId: 'reading',
        kind: 'true-false-reading',
        passage: passage.passage,
        statement: stmt.text,
        answer: stmt.answer,
        explanation: passage.explanationVi,
      });
    }
  }
  return questions;
}
