import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.goto('https://ea.vieschool.com', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(2500);
await page.locator('[data-testid="login-username"]').fill('demo_hs');
await page.locator('[data-testid="login-pin"]').fill('demo2026');
await page.locator('[data-testid="login-submit"]').click();
await page.waitForTimeout(4000);
console.log('IDS:', await page.locator('[data-testid]').evaluateAll(els => els.map(e => e.getAttribute('data-testid')).slice(0, 15)));
await page.locator('[data-testid="grade-card-grade-4"]').click();
await page.waitForTimeout(3500);
const card = page.locator('[data-testid="leaderboard-card"]');
console.log('CARD TEXT:', (await card.textContent())?.slice(0, 300));
await browser.close();
