import { chromium } from 'playwright';
const browser = await chromium.launchPersistentContext('/tmp/ioe-real-profile2', { headless: true });
const page = browser.pages()[0] || await browser.newPage();
await page.goto('https://edu.go.vn/user/dang-nhap', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(10000);
console.log('inputs:', await page.locator('input').count());
console.log('iframes:', await page.locator('iframe').count());
const html = await page.content();
console.log(html.slice(0, 3000));
await browser.close();
