import { chromium } from 'playwright';
const browser = await chromium.launchPersistentContext('/tmp/vio-probe', { headless: false });
const page = browser.pages()[0] || await browser.newPage();
await page.goto('https://violympic.vn/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(5000);
await page.locator('text=Đăng ký').first().click().catch(()=>{});
await page.waitForTimeout(5000);
console.log('url:', page.url());
const txt = await page.locator('body').innerText().catch(()=>'');
console.log(txt.slice(0, 2000));
const inputs = await page.locator('input').evaluateAll(els => els.map(e => ({type: e.type, ph: e.placeholder, name: e.name})));
console.log(JSON.stringify(inputs));
await page.screenshot({ path: '/tmp/vio-reg.png' });
await browser.close();
