import { chromium } from 'playwright';
const browser = await chromium.launchPersistentContext('/tmp/vio-probe', { headless: false });
const page = browser.pages()[0] || await browser.newPage();
await page.goto('https://violympic.vn/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(5000);
await page.locator('button:has-text("Đăng ký")').first().click();
await page.waitForTimeout(6000);
console.log('url:', page.url());
const inputs = await page.locator('input').evaluateAll(els => els.map(e => ({type: e.type, ph: e.placeholder, name: e.name, id: e.id})));
console.log(JSON.stringify(inputs, null, 1));
const txt = await page.locator('body').innerText().catch(()=>'');
console.log(txt.slice(txt.indexOf('Đăng ký'), txt.indexOf('Đăng ký')+1500));
await page.screenshot({ path: '/tmp/vio-reg-modal.png' });
await browser.close();
