#!/usr/bin/env python3
"""CR-24 - generate src/data/ipaMap.ts: word -> IPA for the whole vocab bank.

Uses the `eng-to-ipa` package (bundled CMUdict, offline after install):
    pip3 install eng-to-ipa

Words are extracted from the TS vocab data (regex on `word:`/'word' tuple
entries is fragile, so we let Node dump the word list instead - see
scripts/dump-words.mjs which this script invokes).
"""
import json
import subprocess
import sys
from pathlib import Path

import eng_to_ipa as ipa

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "data" / "ipaMap.ts"

# Dump all vocab words via tsx so we read the real bank, not regexes.
result = subprocess.run(
    ["npx", "tsx", "scripts/dump-words.ts"],
    cwd=ROOT, capture_output=True, text=True, check=True,
)
words = json.loads(result.stdout)

mapping = {}
missing = []
for word in words:
    text = word.strip().lower()
    conv = ipa.convert(text)
    # eng_to_ipa echoes unknown tokens with '*' - fall back to per-word.
    if "*" in conv:
        parts = [ipa.convert(tok) for tok in text.split()]
        if all("*" not in p for p in parts):
            conv = " ".join(parts)
        else:
            missing.append(word)
            continue
    mapping[text] = conv

OUT.write_text(
    "/** Generated by scripts/gen-ipa.py - do not edit by hand.\n"
    " *  word (lowercase) -> American IPA without slashes. */\n"
    "export const WORD_IPA: Record<string, string> = "
    + json.dumps(mapping, ensure_ascii=False, indent=2)
    + ";\n",
    encoding="utf-8",
)
print(f"wrote {len(mapping)} IPA entries -> {OUT.relative_to(ROOT)}")
if missing:
    print("missing:", ", ".join(missing))
